### PR TITLE
[Feature Fix] Put correct private component name in file tree

### PR DESCRIPTION
**Pull request by haoyuchen1992**
### Purpose
Display correct name for private project 
Resolved Issue https://github.com/CenterForOpenScience/osf.io/issues/3621

### Change
Delete the old code which only do simple if-statement judgement and replace it with a function to get the display name of project. 

### Side Effect
It is not a general solution and only apply in rubeus.py. Currently, the similar code that deal with the same issue is used in render_node.mako.  It may be better to put into node.py. Because it will be very likely to be used in many other places in future.

Code in render_node.mako
 
        %if summary['is_registration']:
            Private Registration
        %elif summary['is_fork']:
            Private Fork
        %elif not summary['primary']:
            Private Link
        %else:
            Private Component
        %endif

### CODE REVIEW

**Comment by caileyfitz** [comment]
@sloria This is what I was referring to re: @haoyuchen1992's PR. It goes along with his other PR (https://github.com/CenterForOpenScience/osf.io/pull/3760) that was merged into 0.44. I think this should be merged as part of 0.44 as well. Cards are already written -- we just need to test.

**Comment by lbanner** [comment]
+1 from me on that, as long as there are no issues of clarity or expectations.

**Comment by caileyfitz** [comment]
@lbanner This implements the same logic that is already in place for the components widget, so there should not be any questions about wording or otherwise.

**Comment by lbanner** [comment]
Cool :baby_chick:

**Comment by sloria** [comment]
@haoyuchen1992 Can you add a regression test for this in `test_rubeus.py`?

**Pull request merged**
