### PR TITLE
Allow category to be set from the project dashboard page [OSF-5362]

### PR DESCRIPTION
**Pull request by abought**
Requested to be merged with #5592 

## Purpose
Add a widget to change project category from the project dashboard page.

screen shot 2016-05-06 at 12 11 30 pm

### Visible
- Allow category to be set by clicking "Category" on the project dashboard page
- Allow description to be changed without forcing an entire page reload (this was bugging me)
- Automatically update icon when category changes

### Internal
- Update API endpoint used by `nodeControl` widgets, so that it returns the resulting value (to reflect changes made by sanitizer)
  - For example, a description of `p < 0.05` will be mangled by bleach. Now, this will be displayed correctly in the description field, without having to reload the page
- Remove redundant import of `osfHelpers`

## Side effects
None expected. Keep an eye out for other ways the description is used on the page, since refresh behavior was changed.

Relies on the `Array.find` method as made available by es6 shims (added to base.mako on March 30, 2016).

## Ticket
https://openscience.atlassian.net/browse/OSF-5362

### CODE REVIEW

**Comment by abought** [comment]
Previous CI failures appear to be unrelated and may be fixed in #5624. 

Requesting CI restart as part of review process.

**Comment by sloria** [comment]
@abought , yes that PR you linked fixed the tests. Can you please update this with develop?

**Comment by abought** [comment]
PR updated and tests passing.

**Comment by brianjgeiger** [comment]
This isn't working for me. Specifically, it's not loading the node categories into the list.

screen shot 2016-05-10 at 4 32 51 pm

screen shot 2016-05-10 at 4 32 57 pm

**Comment by abought** [comment]
Interesting- let me see if something in the last PR update broke it.

**Comment by brianjgeiger** [comment]
Looks good other than the not working. Pass finished. 🐧

**Comment by abought** [comment]
Thanks for the catch; I've traced the issue to a pebkac error and pushed a fix.

**Comment by abought** [comment]
This time, CI failures were unrelated; I've restarted the build.

**Comment by brianjgeiger** [comment]
Ready to merge once checks are done and #5592 is merged. Because you can't change the project category from the settings page without 5592, but you can on the main page with this, this definitely can't be merged first. 🎉 🐧 🎉

**Comment by brianjgeiger** [comment]
Yay, tests passed!

**Pull request merged**
