### PR TITLE
[ENG-5339] Bump dependency group - crypto

### PR DESCRIPTION
**Pull request by opaduchak**
## Purpose
Bump dependency group crypto (security and cryptgraphy related stuff)

## Changes

Bumped cryto dependencies, swapped `oath` library for `pyotp`

## QA Notes

Changed OTP implementation, as OTP library was swapped, need to test it, through after python and dependency upgrade is complete

What are the areas of risk?

## Ticket
[ENG-5339](https://openscience.atlassian.net/browse/ENG-5339)

[ENG-5339]: https://openscience.atlassian.net/browse/ENG-5339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by felliott — CHANGES_REQUESTED** [review]
Hey @opaduchak,

The oath => pyotp conversion looks sane to me.  I'm going to get another dev more familiar with 2FA to also take a look.

I think you're missing some updates for pyjwt. Check out the requirements changelog[1]; pyjwt renamed an error class, changed the `algorithm` kwarg to `algorithms` (and made it take a list), and renamed some of the option keys.

And from the requirements changelog for `itsdangerous`[2]: do we need to change how we do signing?

Cheers,
@felliott

[1] https://www.notion.so/cos/Requirements-Changelog-Notes-e4d7067f1ab541058dac758de12c9a7b?pvs=4#4f0d798cb5db4a2eb7586687c0f36298
[2] https://www.notion.so/cos/Requirements-Changelog-Notes-e4d7067f1ab541058dac758de12c9a7b?pvs=4#6033599046d740ea808a755c92c570d3

**Comment by felliott** [comment]
Another one: `oauthlib`[1] had a breaking change[2] in v3.0.0 where an `invalid_grant` error now has a 400 status code instead of a 401.  We test something with that same name in `tests/test_oauth.py`. Can you verify that that test is not affected?

[1] https://www.notion.so/cos/Requirements-Changelog-Notes-e4d7067f1ab541058dac758de12c9a7b?pvs=4#629906e0aa1a4eef9f5c120e8d79bbad
[2] https://github.com/oauthlib/oauthlib/blob/master/CHANGELOG.rst#300-2019-01-01

**Comment by opaduchak** [comment]
> And from the requirements changelog for `itsdangerous`[2]: do we need to change how we do signing?

Tested on different versions of library, haven't noticed any changes  to signed payload

**Comment by opaduchak** [comment]
> Another one: `oauthlib`[1] had a breaking change[2] in v3.0.0 where an `invalid_grant` error now has a 400 status code instead of a 401. We test something with that same name in `tests/test_oauth.py`. Can you verify that that test is not affected?
> 
Looked through stuff, and found no sign of dependence on status code (even when raising errors in library internals), so this should not affect us in any way. I think we should be good, but we may revisit this during tests phase

**Comment by felliott** [comment]
Looks good! Merged.

**Pull request merged**
