### PR TITLE
[ENG-1598] Add burst rate throttling

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

Stop isolated madmen from bringing down our humble server by unleashing bursts of unthrottled requests.

## Changes

- create burst rate throttle class
- add that burst throttle class to relevant views and routes.

## QA Notes

- no migration
- no user facing changes

## Documentation

Not user facing, no new docs.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-1598

### CODE REVIEW

**Comment by Johnetordoff** [comment]
The current tests at `api_tests/base/test_throttling.py` don't really cover this case and frankly don't really seem to test for anything. It's possible I'm just missing the point but it seems like `TestUserRateThrottle` and other similar tests in that file aren't really testing for anything. We might want to look at an analysis ticket to address the throttle tests, because [they are being skipped on Travis anyway](https://github.com/CenterForOpenScience/osf.io/blob/develop/api_tests/base/test_throttling.py#L11-L13).

**Comment by brianjgeiger** [comment]
Harrumph. Okay. Did you verify locally that it works the way we expect?

**Comment by Johnetordoff** [comment]
@brianjgeiger yes tested it locally, plus it throttles itself to death on travis if unchecked, so it definitely works.

**Comment by Johnetordoff** [comment]
Merged into staging and tested

**Comment by brianjgeiger** [comment]
Reopening; this was tested on staging, but hadn't been merged yet.

**Pull request merged**
