### PR TITLE
Fixed youtube errors in getting started page

### PR DESCRIPTION
**Pull request by PatrickEGorman**
## Purpose
FIx to allow youtube videos on getting started page to have functioning menus
Closes Issue #2640

## Changes
Fixed bootstrap row/column structure in getting started page and subtemplates

## Side effects
Youtube menus are now functional

### CODE REVIEW

**Comment by GaryKriebel** [comment]
@PatrickEGorman ... be sure to comment what issue the PR fixes.

**Comment by PatrickEGorman** [comment]
Edited request.  Should be good now

**Comment by PatrickEGorman** [comment]
Problems with resizing page.  Will reopen when solved

**Comment by PatrickEGorman** [comment]
Made a few edits on resizing issues

**Comment by samanehsan** [comment]
Going to close this PR since these commits have been pulled into #2864. Thanks @PatrickEGorman! :whale2:

**Pull request closed without merging**
