### PR TITLE
fix the time_zone

### PR DESCRIPTION
**Pull request by chennan47**
<b>Purpose</b>
fix the timezone display error in logs.

<b>Changes</b>
before the fix 
screen shot 2015-04-13 at 1 32 09 pm
after:
screen shot 2015-04-13 at 1 32 34 pm

### CODE REVIEW

**Comment by chennan47** [comment]
@sloria rdy for review

**Comment by lbanner** [comment]
@sloria -- Can this be a Hot Fix? ..... added this to 0.32.0 as priority in case not. Thanks.

**Comment by sloria** [comment]
@lbanner This is already a hotfix (see branch name).

**Comment by lbanner** [comment]
Ah! ... silly me ... Thanks @sloria

**Pull request merged**
