### PR TITLE
Fix link and spacing issue in License text

### PR DESCRIPTION
**Pull request by jolene-esposito**

### CODE REVIEW

**Comment by sloria** [comment]
The link is still unclickable. I think this is an issue with the CSS. I will look into it.

**Comment by jolene-esposito** [comment]
Really?! Sorry! - we want it to open in a new window/tab.. that might have
something to do with it. If it's an ordeal I can just take it out.

--------------------------
*Jolene Esposito*
Project Manager
Center for Open Science
jolene@cos.io

Need stats help? COS offers free Statistical and Methodological Consulting
services on reproducible research practices. Learn more here
<http://cos.io/stats_consulting/?utm_source=email_sig&utm_medium=email&utm_campaign=stats>
.

**Comment by sloria** [comment]
No it's not because of that. The problem is the anchor elements that make the sidebar nav links work.

**Comment by jolene-esposito** [comment]
Let me know if I can help on getting this fixed. We want to send out a
user's email next week that is linked to the License section of the Getting
Started page.

**Comment by sloria** [comment]
@caneruguz Is working on the fix for the link.

**Comment by caneruguz** [comment]
@sloria @jolene-esposito the PR linked above should be able to fix that.

**Comment by sloria** [comment]
Thanks Caner. @jolene-esposito This should now be fixed on production.

**Pull request closed without merging**
