### PR TITLE
[Hotfix] Send request to import account iff user does not cancel.

### PR DESCRIPTION
**Pull request by mfraezz**
[#OSF-5756]

### CODE REVIEW

**Comment by sloria** [comment]
I don't understand why this is necessary; don't we prevent the request if the user cancels here: https://github.com/CenterForOpenScience/osf.io/pull/5055/files#diff-780e22e6e487060eaba79b328e4c746cR156 ?

**Comment by mfraezz** [comment]
That's a different case -- it's hit when the user has only one ExternalAccount connected for the addon

**Comment by mfraezz** [comment]
[This](https://github.com/CenterForOpenScience/osf.io/pull/5055/files#diff-780e22e6e487060eaba79b328e4c746cR130) is the troublesome case. `connectExistingAccount` is being `.bind`-ed as the callback function. The dropdown's `value` (an `external_account_id`) is passed in if the user clicks `Import`, `null` if `Cancel`. The case where they have only one account assumes that their only account is the one that they choose, and *is* checking that they confirmed the import, but is doing so before `connectExistingAccount` is called.

**Comment by sloria** [comment]
Thanks for the clarification.

**Pull request merged**
