### PR TITLE
[OSF-8268] Update language in engagement email

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

Improve engagement with better email that links to COS help resources.

## Changes

Adds static html links

### Before:

<div style="margin: 40px;">
        <br>
        Hello ${fullname},
        <br><br>
        We’ve noticed it’s been a while since you used the Open Science Framework (OSF). We are constantly adding and improving features, so we thought it might be time to check in with you.
        Most researchers begin using the OSF by creating a project to organize their files and notes. Projects are equipped with powerful features to help you manage your research:
        <br>
        <ul>
            <li>You can keep your work private, or make it public and share it with others</li>
            <li>You can use the wiki to live-edit content with your collaborators</li>
            <li>You can connect to third-party services like Dropbox or Google Drive</li>
        </ul>
        To get started now, visit your dashboard and click on “Create a project.”
        If you have specific questions, or would like to set up a free training session for you and your colleagues, please do not hesitate to <a href="mailto:support@osf.io">get in touch with us!</a>
        <br><br>
        Best,
        <br>
        COS Support Team
    </div>

### After:

<div style="margin: 40px;">
        <br>
        Hello ${fullname},
        <br><br>
        We’ve noticed it’s been a while since you used the Open Science Framework (OSF). We are constantly adding and improving features, so we thought it might be time to check in with you.
        Most researchers begin using the OSF by creating a project to organize their files and notes. Projects are equipped with powerful features to help you manage your research:
        <br>
        <ul>
            <li>You can keep your work private, or make it public and share it with others</li>
            <li>You can use the wiki to live-edit content with your collaborators</li>
            <li>You can connect to third-party services like Dropbox or Google Drive</li>
        </ul>
        To get started now, visit your dashboard and click on “Create a project.”
        Need help getting started with a project? Check out the <a href="http://help.osf.io">OSF Help Guides</a> or one of our recent <a href="https://www.youtube.com/channel/UCGPlVf8FsQ23BehDLFrQa-g">OSF 101 webinars</a>.
        <br><br>
        Best,
        <br>
        COS Support Team
</div>

## Side effects

None that I know of.

## Tests

Design oriented changes with no new tests.

## Ticket

https://openscience.atlassian.net/browse/OSF-8268

### CODE REVIEW

**Comment by Johnetordoff** [comment]
How do I mock this up so I actually receive these emails in full html?

**Comment by brianjgeiger** [comment]
It doesn't have to be completely styled.

screen shot 2017-08-16 at 2 24 30 pm

**Comment by Johnetordoff** [comment]
Is the above copy/paste before/after ok? not technically a screenshot but github's HTML markdown should capture the pertinent details.

**Comment by brianjgeiger** [comment]
Yup, looks good, thank you.

**Pull request merged**
