### PR TITLE
[ENG-5011] Fix/subject iri

### PR DESCRIPTION
**Pull request by aaxelb**
## Purpose
fix "browse by subject" links on osf preprints landing pages

## Changes
fix bug in `Subject.get_semantic_iri` -- a custom subject should identified by the bepress-subject iri when its text is identical to the bepress-subject, and by its own iri when its text is different (not the other way 'round)

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify 
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Ticket
[ENG-5011]

[ENG-5011]: https://openscience.atlassian.net/browse/ENG-5011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Johnetordoff — APPROVED** [review]
Looks good to fix the filtering issues!

**Review by mfraezz — APPROVED** [review]
LGTM, but will this require a `recatalog_metadata --preprints` to fix?

**Comment by aaxelb** [comment]
@mfraezz no recatalog needed, tho i agree it should have been -- `get_semantic_iri` is used when querying subjects but not when [gathering metadata to index](https://github.com/CenterForOpenScience/osf.io/blob/45029e47ff98d8ba57b8f3ab9ebf7be04c191cd0/osf/metadata/osf_gathering.py#L538-L542) (with this pr, that code comment is made truthful)

that duplicated logic seems like a bug, even tho it's convenient at the moment -- added a one-line "fix" to use `get_semantic_iri` there instead of `absolute_api_v2_subject_url`, and any future breaking changes to `get_semantic_iri` will (correctly?) require `recatalog_metadata` for whatever's affected

**Comment by mfraezz** [comment]
Squashed in as 754e0627c6d903314f13c3852b029c8e7fdf0ab0, consider this merged 🦦

**Pull request closed without merging**
