### PR TITLE
add notification clarify

### PR DESCRIPTION
**Pull request by chennan47**
<b>Purpose</b>
Add clarification for notification settings. Solves https://github.com/CenterForOpenScience/osf.io/issues/2725

<b>Changes</b>
before change:
screen shot 2015-05-15 at 10 07 14 am

after change:
screen shot 2015-05-15 at 10 07 45 am

### CODE REVIEW

**Comment by chennan47** [comment]
@saradbowman @bnosek need a language review.

**Comment by saradbowman** [comment]
This language is okay by me.

**Comment by bnosek** [comment]
yes, fine.

**Comment by sloria** [comment]
For proper plurality, how about:

"These settings only apply to you. They do not affect any other contributor on this project."

**Comment by chennan47** [comment]
screen shot 2015-05-15 at 12 57 29 pm

**Pull request merged**
