### PR TITLE
Fix Getting Started page / youtube videos

### PR DESCRIPTION
**Pull request by PatrickEGorman**
Purpose
Currently, a number of youtube videos in the Getting Started Page have menu bars that disappear on mouseover and have non-functional buttons.  Additionally the page is very improperly formatted with rows and columns extremely disorganized.

Closes Issue #2640

Changes
Organized rows and columns into proper formats.

Side Effects
Fixes youtube problem and improves page organization

### CODE REVIEW

**Comment by lbanner** [comment]
@PatrickEGorman -- This actually should be a merge request to develop -- i.e. not a "HotFix" -- Think you had it right the first time! : )

**Comment by chennan47** [comment]
@PatrickEGorman It's a hotfix then you don't need to merge develop into this pr.

**Comment by PatrickEGorman** [comment]
Oops...  I thought I pulled from master but I actually pulled from develop.  Still figuring out Gitflow

**Comment by PatrickEGorman** [comment]
Actually I think this is the wrong branch...

**Pull request closed without merging**
