### PR TITLE
Removes Broken Two-factor Auth Link

### LINKED ISSUE #3901: 'Activate your device' link not working for two-factor authentication
# Steps
1. Log in to osf.io
2. Go to user settings
3. Click on Account Settings on the left navbar
4. Click to enable two-factor authentication
5. Scan the barcode using a google authenticator on your phone and put in your code
4. Hit submit
5. Now go to your Dashboard to navigate away from the User Settings page
6. Notice the blue alert message at the top and click on 'Activate your device' link

# Expected
The link should redirect the user to the appropriate page. (Not too sure where it should redirect or that if the link is even necessary)

# Actual
Clicking on the link does nothing

activate your device link does not work

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h1> Purpose </h1>
Remove unnecessary link for Two-factor Auth message. Close #3901.
<h1> Changes </h1>
Deletes link tag
<h1> Side Effect </h1>
None that I know of.

### CODE REVIEW

**Comment by sloria** [comment]
This doesn't seem to address the root of the issue, which is that the alert shouldn't display outside of the user  settings page (see https://github.com/CenterForOpenScience/osf.io/issues/3901#issuecomment-127384824). 

@Johnetordoff Can you look into this further?

**Comment by nicipfeiffer** [comment]
@sloria Still seeing this (the issue mentioned in the comment), has this been merged?

**Comment by sloria** [comment]
No, this wasn't merged because it did not address the root of the issue. Ping @Johnetordoff for follow-up on this.

**Comment by Johnetordoff** [comment]
@sloria I got to say I'm totally stumped by this, does the page have to refresh for this to work, because that would be an easy fix.

**Pull request closed without merging**
