### PR TITLE
[feature-fix][#2687]Fix figshare showing Delete button with only read permissions

### PR DESCRIPTION
**Pull request by hmoco**
#2687 

## Purpose
 For all folders and files under a project in which one has only read access, when selecting anything, the 'Delete' button (previously an 'X' under actions column), does not appear. Although in read-only figshare files and folders cannot be deleted, the 'Delete' button is shown and gives an error. This fix checks for edit permission for Figshare folder and files to show the button, preventing it from showing if the user cannot actually delete the file/folder, fixing #2867.

## Changes
Selecting a figshare folder or file only shows the 'Delete' button if the user has edit access to the project.
'Delete' button not showing

## Side Effects
Any feature that uses the fangorn system to get a 'Delete' button for figshare will only do so if the user has edit privilege.

### CODE REVIEW

**Comment by samanehsan** [comment]
Awesome! The delete button does not show up in the files grid for figshare, but I found that read-only contributors also see a delete button on the file view page for draft figshare files.  

screen shot 2015-06-01 at 2 39 16 pm


Would you mind changing that so read-only contributors do not see the delete button on the figshare file view page? Thanks!

**Comment by samanehsan** [comment]
First pass complete! Let me know if you have any questions! :tada:

**Comment by hmoco** [comment]
Done!

**Comment by samanehsan** [comment]
I just checked this out and the delete button on the file view page is gone for read-only contributors, but it is also gone for administrators. Can you look into this? :sunny:

**Comment by hmoco** [comment]
Well that's not good at all, I will take a look at it.

**Comment by hmoco** [comment]
The other problem you mentioned, the Delete button on MFR, has been fixed by Chris with the new MFR on .38, so I think this is good to go.

**Comment by samanehsan** [comment]
Oh, okay! In that case, I think this is good to go @sloria! :cake:

**Pull request merged**
