### PR TITLE
Update API README.md

### PR DESCRIPTION
**Pull request by alexschiller**
Remove broken route and fixed 8000 route to current version

### CODE REVIEW

**Comment by samanehsan** [comment]
Can you look into the failing tests?

**Comment by brianjgeiger** [comment]
I expect those a Chris's fault. Check the 0.38 branch. If they are the same failing tests, then it's him. 

.:Brian J. Geiger

**Comment by samanehsan** [comment]
Since 0.38 has been released, please re-submit to 0.39 or develop. Thanks!

**Comment by alexschiller** [comment]
@brianjgeiger Is this change still relevant or have the general osf.io develop docs been updated to include this information? In other words, should I send a PR to develop with this minor change?

**Comment by brianjgeiger** [comment]
Let's skip this. We'll probably want to do a more comprehensive docs change in a week or so.

**Pull request closed without merging**
