### PR TITLE
Feature/Zotero Restrict Citations to Unfiled Items at Root Level[PLAT-730]

### PR DESCRIPTION
**Pull request by pattisdr**
## Purpose
Zotero citations appear to be duplicated when a user connects their root library (All Documents ) to a project.  The desired OSF behavior is that references appear only once, and aren't displayed at both the root, and a collection, if applicable. 

## Changes

- Zotero has no API call to fetch unfiled items; calls to fetch the root return all items.  Zotero displays all citations at the root level, but because of our hierarchical display of zotero citations, this looks like a bug on our end. On the OSF-side, we now exclude items that have been filed in one or more collections, and only display unfiled items and collections at the root.  
- Second change involves only returning top-level items at both the root and within collections. To explain, you can have a citation, and can upload a pdf to that citation.  The citation is the top-level item and that PDF is a child.  Zotero is only returning top-level items in their UI, and this would bring our UI in line with that. 
- Pyzotero has been upgraded to the latest version to allow returning top-level items only within collections.

## Before:
Film.txt is an attachment stored on This is a film.
screen shot 2018-03-16 at 12 52 22 pm

## After:
Unfiled items have been removed from the root, and we are no longer showing child items
screen shot 2018-03-16 at 12 55 07 pm

For comparison, this is what Zotero's UI shows:
Root level (Zotero shows all top-level items, filed and unfiled at root).  This is a film is filed under Films collection, but root shows everything. The attachment on This is a film is not visible.
screen shot 2018-03-16 at 12 52 36 pm

Within film collections folder:
screen shot 2018-03-16 at 12 52 43 pm

## QA Notes

Follow Becca's instructions in the ticket, creating several nested folders with several citations apiece, and verify that only unfiled items show up at the root.  I would add some tests with the same citation appearing in multiple collections, and verify that the citation shows up in both collections, but is absent from the root.  Also add attachments to the citations in zotero and verify that they no longer appear in either root or collections.  Test across personal library and group libraries.

## Ticket

https://openscience.atlassian.net/browse/PLAT-730

### CODE REVIEW

**Comment by Johnetordoff** [comment]
I got the following when trying to load citations from the Project overview page.
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/framework/routing/__init__.py", line 117, in wrapped
    data = fn(*args, **kwargs)
  File "/code/website/project/decorators.py", line 239, in wrapped
    return response or func(*args, **kwargs)
  File "/code/framework/auth/decorators.py", line 41, in wrapped
    return func(*args, **kwargs)
  File "/code/website/project/decorators.py", line 285, in wrapped
    return func(*args, **kwargs)
  File "/code/website/citations/views.py", line 180, in _citation_list
    return Provider().citation_list(node_addon, auth.user, list_id, show)
  File "/code/addons/zotero/provider.py", line 134, in citation_list
    for each in node_addon.api.get_list(list_id=list_id, library_id=attached_library_id)
  File "/code/addons/zotero/models.py", line 66, in get_list
    return self._citations_for_user(library_id)
  File "/code/addons/zotero/models.py", line 162, in _citations_for_user
    unfiled_keys = [citation['data']['key'] for citation in client.items() if not citation['data']['collections']]
KeyError: 'collections'
```
Here's some resources in my library if that helps.
screen shot 2018-03-14 at 9 55 02 am

**Comment by pattisdr** [comment]
ah, thanks @Johnetordoff, I assumed collections would always be there.

**Comment by pattisdr** [comment]
@Johnetordoff, the bug you caught was that top-level items only have a collections key.  (If you have a citation and then upload a PDF to that citation, the citation is top-level and the PDF is a child). Ran this by product, and we have agreed to not show top-level items at the root level or within collections.  Zotero's UI isn't showing top-level so this brings this more in line with that.  Also if you delete an attachment they still show up, so this gets rid of that issue.

**Comment by Johnetordoff** [comment]
I now get the following console error when trying to expand any folder:
screen shot 2018-03-19 at 8 56 21 am

**Comment by pattisdr** [comment]
*smacks head* thanks @Johnetordoff

**Comment by pattisdr** [comment]
question for you @Johnetordoff,  I can't duplicate, and I am wondering if you saw that pyzotero was upgraded and installed requirements.  Without the upgrade, certain Zotero calls won't work.

**Comment by Johnetordoff** [comment]
@pattisdr ug, sorry I didn't rebuild my requirement outside rebuilding the assets, I'll retry this.

**Comment by Johnetordoff** [comment]
@pattisdr Looks good ✅

**Comment by sloria** [comment]
Looks some of the Zotero API calls aren't being mocked. See the failing addons job: https://travis-ci.org/CenterForOpenScience/osf.io/jobs/354442105

**Comment by pattisdr** [comment]
Anticipating conflict here, zotero/tests/utils/ https://github.com/CenterForOpenScience/osf.io/pull/8219

**Comment by sloria** [comment]
Looks good. Confirmed; the failing test is unrelated to this PR.

**Pull request merged**
