### PR TITLE
Changes for importing contributors from parent project

### PR DESCRIPTION
**Pull request by arpitar**
Created a new variable that stores binary value true/false
The 'import from parent' anchor link is changed to a button
The button alternatively displays or hides the list of contributors upon clicking, based on the value of the binary variable
Allows users the option to hide or show the list of contributors

### CODE REVIEW

**Comment by lbanner** [comment]
@arpitar Is there a JIRA ticket number for this PR? Thanks.

**Comment by arpitar** [comment]
Hi Larry,

The JIRA ticket is 4673. I entered it in the commit but I’m not sure why it didn’t get automatically linked to the ticket.

**Comment by lbanner** [comment]
:+1: Thank you!

**Comment by arpitar** [comment]
Hi Larry, sorry for the typing mistake. The JIRA ticket is 4763. I probably entered the wrong one earlier, really sorry about it!

**Comment by sloria** [comment]
This appears to be redundant with https://github.com/CenterForOpenScience/osf.io/pull/4932 ; closing this for now.

**Pull request closed without merging**
