### PR TITLE
Change Tag Styling

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h1> Purpose </h1>
Makes tag styling more consistent, closes issue  #3783.
<h1> Changes </h1>
Simple html and JS changes that create a new standard .tag class.
<h1> Side Effects </h1>
Html with arbitrarily applied class="tag" tags will be displayed with the new style or those tags will be destyled.

### CODE REVIEW

**Comment by sloria** [comment]
Is there any way you can avoid the duplication? Can you re-use the CSS rules applied to the search tags?

**Comment by Johnetordoff** [comment]
A side effect of making the tags CSS more consistent is that the logs will now display tag styling. So there few aesthetic decisions around this. 
**Option One:**
screen shot 2015-07-28 at 2 19 30 pm

Display tags with the same space, but they overlap.
**Option Two:**
screen shot 2015-07-28 at 3 01 52 pm
Uneven vertical space, but no overlap. 
**Option Three:**
Keep it the same, just change the appearance for the search page and tag input.
Any thoughts @caneruguz, @GaryKriebel, @lbanner ?

**Comment by brianjgeiger** [comment]
I would eliminate the blue background on the tags in the log list, personally.

**Comment by caneruguz** [comment]
@Johnetordoff this PR description needs a better way of conveying information, especially if you are saying that it closes an issue. And with issues that include significant CSS changes it is immensely important to add a screenshot. So first let's improve this I think
- Add a screenshot about the new versions
- Describe the changes more specifically i.e. the styling for the tags input in project summary page were changes to align with....
- If logs may appear differently explain why and why should that be considered not a side issue.

**Comment by caneruguz** [comment]
@Johnetordoff  About the tags in the activity list, I don't think this was the intention of the issue when it was created. There was no need to change it since it wasn't required or described in the issue.  Let's keep it as it is, I think in terms of style it's also the right thing to do.

**Comment by lbanner** [comment]
So, basically the desire is an implementation of change in Tag Style (color), consistent with the Guide (i.e., at minimum utilizing a color that is one of our colors), but not implicating the "tag" style as presented in the activity log. Correct?

**Comment by sloria** [comment]
I agree with Caner--let's defer changing the activity log. It can be changed in another PR after we've decided on what it should look like.

**Comment by Johnetordoff** [comment]
I agree Recent Activity shouldn't be changed, it just happened to have a class="tag" tag, so I figured some styling was to be implemented there at some point. I took those tags out now.

**Comment by Johnetordoff** [comment]
As of this PR tags looks like this:
screen shot 2015-07-29 at 9 26 23 am
screen shot 2015-07-29 at 9 26 02 am

**Comment by caneruguz** [comment]
Thanks @Johnetordoff ; it definitely does look uniform and addresses the issue.

**Comment by sloria** [comment]
Looking good. Just a couple more things.

- Since the tags are clickable, the cursor should turn to "pointer"
- Would it be difficult to make the delete buttons consistent between search and the tags input?

osf___addons_example


osf___search

**Comment by sloria** [comment]
Once the above fixes are made, this is good to merge.

**Comment by Johnetordoff** [comment]
I thought about making to buttons the same, but they do different things and I thought it would be better not to confuse people. Also adding the corner buttons would mean messing with the third-party jquery-tagsinput package, so it would be kinda work...

**Comment by sloria** [comment]
OK, don't worry about the "x" button for now.

**Comment by sloria** [comment]
Looks good. Merged into develop

**Pull request closed without merging**
