### PR TITLE
[Enhancement] [OSF Meeting] Add date created column to conference page 

### PR DESCRIPTION
**Pull request by haoyuchen1992**
## Purpose
Based on the discussion with community, add date column for conference page

Resolve [OSF-4694]

### Before Change:
screenshot 2015-10-26 17 29 36

### After Change:
screenshot 2015-10-27 09 32 08

## Side Effect 
None

### CODE REVIEW

**Comment by samanehsan** [comment]
Looks good to me @haoyuchen1992! Done with code review 1 :sunny:

**Comment by whit537** [comment]
Pretty straightforward, looks good on first blush. I'll stand it up after lunch and make sure it looks good through the web.

**Comment by whit537** [comment]
I've restored a db dump I received from @cwisecarver under https://github.com/CenterForOpenScience/osf.io/pull/4745#issuecomment-167835356. Happily, it includes conferences and submissions. :-)

I am seeing the new column:

screen shot 2016-01-22 at 1 17 41 pm
screen shot 2016-01-22 at 1 17 56 pm

**Comment by whit537** [comment]
The widths could be balanced a bit better (`Category` could use +5% from `Downloads`), but otherwise this is fine. :shipit:

**Comment by whit537** [comment]
[OSF-4694](https://openscience.atlassian.net/browse/OSF-4694)

**Comment by whit537** [comment]
> The submissions table on the /meetings page needs to be updated with the following:
>
 - Add dates
 - Handle use case of single names (eg: see Japanese submissions)

**Comment by whit537** [comment]
> :shipit:

Erm, actually ... this PR adds dates, but I don't see anything about single names. It's not obvious to me from the PR description here or on the Jira ticket what the requirement is there. The names on [JSSP2015](https://osf.io/view/JSSP2015/) (the meeting screencapped above, and the only instance of "japan" on the [meetings](https://osf.io/meetings/) page) look fine to me:

screen shot 2016-01-22 at 1 27 11 pm

**Comment by whit537** [comment]
Oops! Found this update in Jira:

> Handling use case of single name has been recorded in another ticket.

**Comment by whit537** [comment]
Okay! :shipit: after all! :-)

**Pull request merged**
