### PR TITLE
[Fix] #1678 "view file" tooltip text positioning switch to mouse position 

### PR DESCRIPTION
**Pull request by caneruguz**
## Purpose
This PR initially set out to resolve issue #1678 . Tooltips automatic placement was causing problems for long files in any case  so a solution was to show the tooltip where the mouse hovered over the item name which would eliminate the problem with the long file tooltips not being visible. 

## Changes
- Separated function to reapplyTooltips which assigns tooltips and takes care of placement
- Added this function to Fangorn.Utils for use by others
- Additionally found out that Dataverse file names did not have tooltips so added them as well. 

## Side Effects
- None, placement is working everytime provided there is a hover which is the same as previous tooltip requirement. 
- Tested in Chrome, Safari, Firefox, IE 9, 10, 11: All work as expected, tooltip shows where the mouse is. 
- One caveat is that sometimes (not always and not as often) there will be a minor difference between mosue position and tooltip but it is often because tooltip appears where mouse first entered and if the mouse position is slid a little bit they will be slightly off (a couple of pixels); I think this isn't an issue and does not harm the feature.

### CODE REVIEW

**Comment by sloria** [comment]
@caneruguz Can you please resend this as a feature branch?

**Comment by caneruguz** [comment]
So branch this into a branch called feature/.... 
Do I change anything in the commits?

**Comment by sloria** [comment]
@caneruguz You should just be able to send a new PR based off of develop

**Comment by caneruguz** [comment]
@Steve are you waiting for me to resend this? Was this not the one you were going to add in?

**Pull request closed without merging**
