### PR TITLE
[PLAT-627] Improve Opt out in notification emails + Update OSF name

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

It's a Gates' suggestion that we add a link on emails to unsubscribe from node specific notifications as well as user specific notifications. While we're at it let's update the image we use too.

## Changes

- Changes base notification template to send node link.
- Add new image

## QA Notes

This won't necessarily effect all notification emails, only ones that pertain to specific nodes.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/PLAT-627

### CODE REVIEW

**Comment by chennan47** [comment]
https://github.com/CenterForOpenScience/osf.io/blob/32c8b2980d3ac19d6ae0849eb5a18881c02bfc77/website/templates/emails/file_operation_success.html.mako#L22
https://github.com/CenterForOpenScience/osf.io/blob/32c8b2980d3ac19d6ae0849eb5a18881c02bfc77/website/templates/emails/file_operation_success.html.mako#L22
Those two templates do not include notify_base.mako, but they have the same old logo and a different footer with no link about update your settings or project settings. You probably want to change those two templates as well.

**Comment by chennan47** [comment]
https://github.com/CenterForOpenScience/osf.io/blob/4331d6d8159582dd28e2310f63f76c17d5ac7bd5/website/templates/emails/file_operation_failed.html.mako#L75
https://github.com/CenterForOpenScience/osf.io/blob/32c8b2980d3ac19d6ae0849eb5a18881c02bfc77/website/templates/emails/file_operation_success.html.mako#L74
The link here only goes to the user settings. You might want to update the language and give them a link to project settings for email notification as well.

**Comment by Johnetordoff** [comment]
Good catch I've now templated the file operation emails with base notify and made them send their html versions. Thusly 
screen shot 2018-01-31 at 4 24 01 pm

**Comment by chennan47** [comment]
Pass done. Nice email templates improvement.

**Comment by erinspace** [comment]
Only one small comment -- looks like we're no longer using `cos-white2.png` so that can be removed from static images. An update with develop should also fix travis issues!

**Comment by Johnetordoff** [comment]
@erinspace should be g2g now.

**Pull request merged**
