### PR TITLE
Use yarn bootstrap instead of bower bootstrap [PLAT-510]

### PR DESCRIPTION
**Pull request by cameronblandford**
## Purpose
These commits remove the bower bootstrap import in the base mako template, and add bootstrap to webpack. The purpose of this PR is to remove the need for bootstrap to load independently from the rest of the webpacked CSS, hopefully reducing page load time.

## Changes
* Installed bootstrap via yarn
* Added bootstrap CSS to webpack config
* Changed reference to bootstrap JS from bower copy to yarn copy
* Removed bower bootstrap import from base mako template

## QA Notes
N/A

## Side Effects
None that I can think of.

## Ticket
[https://openscience.atlassian.net/browse/PLAT-510](https://openscience.atlassian.net/browse/PLAT-510)

### CODE REVIEW

**Comment by sloria** [comment]
drive-by: We should be able to remove bootstrap from bower.json, yes?

**Comment by cameronblandford** [comment]
Two other bower packages rely on bower bootstrap (`bootstrap.growl` and `osf-panel`). I was under the impression that removing it completely would break those packages (I got a warning when I tried to).

**Comment by sloria** [comment]
As long as those two packages are importing bootstrap correctly, then they should just be using the NPM bootstrap.

What warning were you getting?

**Comment by cameronblandford** [comment]
```
$ bower uninstall bootstrap
bower conflict      bootstrap.growl, osf-panel depends on bootstrap
? Continue anyway? (Y/n)
```
Maybe it's just a shallow kind of name-checking?

**Comment by sloria** [comment]
@cameronblandford Possibly. Do those packages still work without the bower-installed bootstrap?

**Comment by cameronblandford** [comment]
Huh, they do! I'll push that change.

**Comment by sloria** [comment]
@cameronblandford Cool. Does the assets container start up without that warning? You may need to update the command in docker-compose.yml to ignore it.

**Comment by cameronblandford** [comment]
@sloria no warnings on container startup. Warning only appeared when I was tried to uninstall the bower package. :+1:

**Comment by sloria** [comment]
Ah, cool.

**Comment by sloria** [comment]
Any improvement in the Lighthouse results?

**Comment by cameronblandford** [comment]
Unclear - lighthouse has been giving me wonky results (9-30 seconds per render) with and without bower bootstrap.

**Comment by Johnetordoff** [comment]
@cameronblandford LGTM ! 🎉

**Pull request merged**
