### PR TITLE
Feature/email notify language

### PR DESCRIPTION
**Pull request by chennan47**
<b>Purpose</b>
Add texts to alert user for update notify settings. Closes[#OSF-4422]

### CODE REVIEW

**Comment by HarryRybacki** [comment]
Clean and simple, CR 1 good-to-go @chennan47 :+1:

**Comment by abought** [comment]
CR2 complete; no changes needed here. Email works and style matches. :octopus:

**Comment by sloria** [comment]
There's a lot of inline styling here; I wonder if there's a better way that leverages Bootstrap; pinging @caneruguz for review.

**Comment by sloria** [comment]
Ah, cancel that, I just realized this was an email template. Disregard previous comment.

**Pull request merged**
