### PR TITLE
[Fix] Prevent `addon_added` NodeLogs during migration

### PR DESCRIPTION
**Pull request by mfraezz**
Purpose
=======
When overriding the creation of an addon for a node, a `NodeLog` with no auth (and consequently, no template) is generated. 

Changes
=======
* prevent log creation

Side Effects
=========
None

### CODE REVIEW

**Comment by sloria** [comment]
Rather than hiding the created log, can you modify `add_addon`/`get_or_add_addon` to prevent the log from being created in the first place?

**Comment by samchrisinger** [comment]
:+1:, see `Node#set_visible`

**Comment by sloria** [comment]
@samchrisinger That's for bibliographic contributors; here we're trying to prevent a log from being created for adding an addon.

**Comment by samchrisinger** [comment]
@sloria I mean the `log=True` kwarg pattern for optionally disabling logs.

**Comment by sloria** [comment]
Ah, ok. Good call.

**Comment by mfraezz** [comment]
Yeah, I realized it was using the `add_addon` *with* a `log` kwarg a little while ago. Testing has shown it to work locally for me

**Comment by sloria** [comment]
Cherry-picked this change into `release/0.60.0`.

**Pull request closed without merging**
