### PR TITLE
Hotfix/add contributor text hangover

### LINKED ISSUE #1778: [staging & production] Text hangover in contributors modal
# Steps
1. Go to a project on which you have admin access
2. Click on the sharing tab and then Add Contributors
3. Search for a person with a long name (you can have someone in the office temporarily change their last name to make it longer)
4. Click the plus sign to add them to your project 

# Expected
I expect that all text will stay within the modal outlines

# Actual
Some text hangs over if the name is long: 
screen shot 2015-02-12 at 3 43 12 pm

Tagging @caneruguz for a fix

### PR DESCRIPTION
**Pull request by chennan47**
<b>Purpose</b>
fix the problem that some text hangs over if the name is long in add contributor page: 
image

<b>Changes</b>

image

resolves #1778

### CODE REVIEW

**Comment by caneruguz** [comment]
I’m not sure if all that code is necessary. Couldn’t it be all done with style=“word-wrap:break-word” or class=“break-word". I added a .break-word class to site.css a while ago. This will break words if they don't fit the length of the container.

**Comment by chennan47** [comment]
@caneruguz I am trying to strict the case that it will break the name. since break-word is not smart enough and our input is a fullname, it will ruin one situation which is not necessary to break-word as the system will start from new line itself when the user's name is long but his either firstname, middlename or familyname doesn't exceed 18 characters by itself.

to be more clear, before we make any change
the name display is like
Firstname
Middlename
Familyname

which the situation we want to fix is that 
firstname
middlename
superlongfamilynamewhichbreakstheview

however, apply breakword along might make case 1 looks like
Firstname M
iddlename Fa
milyname

the code I added check the length of each part of his name which narrow the situation that break-word will happen and make them appear on the situation they are really needed.

**Comment by caneruguz** [comment]
If I'm not mistaken that's the difference between ```word-wrap``` and ```word-break```

```word-wrap: break-word``` should start the breaking word in a new line. 

Try it out in this jsfiddle: 
https://jsfiddle.net/j6fmckx4/1/

**Comment by chennan47** [comment]
@caneruguz is looking into the issue to see if there is any easier fix. Hold on this pull request.

**Comment by caneruguz** [comment]
@chennan47, @sloria  take a look at this potential solution:
https://github.com/CenterForOpenScience/osf.io/pull/2093

**Comment by sloria** [comment]
Merged #2093, so closing this one.

**Pull request closed without merging**
