### PR TITLE
[ENG-6571][hotfix] recatalog_metadata --also-decatalog

### PR DESCRIPTION
**Pull request by aaxelb**
## Purpose
speedier `manage.py recatalog_metadata` by skipping private/deleted

## Changes
- update `recatalog_metadata` to skip private/deleted items by default
- add `--also-decatalog` to include private/deleted items
- update tests...
- remove `--datacite-custom-types` (comment describes it as a "temporary arg for datacite 4.5 migration" and updating tests for it became annoying)

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

### CODE REVIEW

**Comment by Johnetordoff** [comment]
No reason to make this a hotfix. Don't want to rush. Please make a ticket and come back.

**Comment by Johnetordoff** [comment]
@brianjgeiger @felliott @bp-cos  I think we need more review for these PRs, we keep dealing with the same type of sloppy hotfixes. The inaccurate numbers being reported by SHARE are causing problems for me and my daily work. Why not make a ticket for this? It's a management command it can be run whenever.

**Comment by Johnetordoff** [comment]
Like this ticket: https://openscience.atlassian.net/browse/ENG-6506 Could have been avoided https://openscience.atlassian.net/browse/ENG-6506 but we just rushed, so not opening this without more discussion.

**Review by mfraezz — APPROVED** [review]
LGTM

**Pull request merged**
