### PR TITLE
[OSF-7582] Add date_created to file version serializer for API

### PR DESCRIPTION
**Pull request by binoculars**
## Purpose

Adds date_created for APIv2 file versions, Needed for:
* CenterForOpenScience/ember-preprints#285
* CenterForOpenScience/ember-osf#192

## Changes

* Add field to the file versions serializer
* Update view docs

screen shot 2017-03-08 at 14 05 27

## Side effects

N/A

## Ticket

https://openscience.atlassian.net/browse/OSF-7582

### CODE REVIEW

**Comment by alexschiller** [comment]
@caseyrollins This requires api docs updating, right?

**Comment by binoculars** [comment]
@alexschiller Where do those docs live?

**Comment by alexschiller** [comment]
@binoculars https://github.com/CenterForOpenScience/developer.osf.io

**Comment by binoculars** [comment]
@alexschiller
bitmoji

**Pull request merged**
