### PR TITLE
[WIP]Paginator for add pointer

### PR DESCRIPTION
**Pull request by chennan47**
related issue:https://github.com/CenterForOpenScience/osf.io/issues/1695

### CODE REVIEW

**Comment by lbanner** [comment]
Hi @chennan47 -- Does this relate to any current, submitted issues? Thanks.

**Comment by chennan47** [comment]
@lbanner update comment part: put the related issue in. But this pr is still working in process. Will update the comment as required when finished.

**Comment by lbanner** [comment]
Sounds good -- Thank you @chennan47

**Comment by chennan47** [comment]
Has to use odm to search since elastic search doesn't work on private infos.

**Pull request closed without merging**
