### PR TITLE
Hotfix/column row fix

### PR DESCRIPTION
**Pull request by PatrickEGorman**
Purpose
Currently, a number of youtube videos in the Getting Started Page have menu bars that disappear on mouseover and have non-functional buttons. Additionally the page is very improperly formatted with rows and columns extremely disorganized.

Closes Issue #2640

Changes
Organized rows and columns into proper formats.

Side Effects
Fixes youtube problem and improves page organization

### CODE REVIEW

**Comment by chennan47** [comment]
@PatrickEGorman Please send your pull request to the correct branch.

**Comment by lbanner** [comment]
@PatrickEGorman - Should be submitted as merge to 'Develop' - Also wondering if your branching is off, as I would expect to see only your commits here. Am I correct on that @nanchen47 ?

**Comment by lbanner** [comment]
@PatrickEGorman - Should be submitted as merge to 'Develop' - Also wondering if your branching is off, as I would expect to see only your commits here. Am I correct on that @nanchen47 ?

**Comment by brianjgeiger** [comment]
@lbanner, he submitted this as a feature fix before and @nanchen47 told him to make it a hotfix. @nanchen47 can you look at what he did to make this? He should have used the gitflow feature of SourceTree to start a new hotfix, which should have been able to do nothing buy branch from master. It's comparing to master, so something is going wrong here.

**Comment by chennan47** [comment]
@PatrickEGorman Pls take a look at http://cosdev.readthedocs.org/en/latest/process/pull_requests.html about sending pull request. If you have other question, you are welcome to ask me through flowdock or find me inside office.

**Comment by GaryKriebel** [comment]
@PatrickEGorman @nanchen47 @brianjgeiger .... does this PR need to be resubmitted based on  the discussions above?

**Comment by GaryKriebel** [comment]
@PatrickEGorman @nanchen47 @brianjgeiger ... nevermind ... there is a followup PR https://github.com/CenterForOpenScience/osf.io/issues/2801

I will close this one

**Pull request closed without merging**
