### PR TITLE
OSF-5265 Opens the link in a new tab

### PR DESCRIPTION
**Pull request by adlius**
<h3>Purpose</h3>
Changes the template file so that new links open in new tabs.

<h3>Changes</h3>
Add "target= "_blank"" to the url.

### CODE REVIEW

**Comment by mfraezz** [comment]
Confirmed that the links now open in a new tab in FF/Chrome/IE.

The images should also be center aligned, as detailed in the [Jira ticket](https://openscience.atlassian.net/browse/OSF-5265). When that is done this will be ready to merge. :octopus:

**Comment by adlius** [comment]
Center align images done.

**Comment by whit537** [comment]
Looks like flexbox is [IE 10+](http://caniuse.com/#feat=flexbox), and buggy at that.

@adlius What's our browser support policy? Does this at least work in IE 10 and 11?

**Comment by mfraezz** [comment]
@whit537 we don't have a formal browser support policy yet, but a proposal is in the works and should be through the review process within a few days.

**Comment by adlius** [comment]
@mfraezz @whit537 I use the flexbox feature as it seems to be a more "modern" way of aligning responsive elements in CSS. However that does depend on what browsers and which versions we eventually decide to support.
Tell me when we have a standard on browser compatibility. I can make changes that supports older browsers. The current fix works on both the newest Safari and the newest Chrome. I do not have IE so I can't speak to how my changes render in IEs.

**Comment by whit537** [comment]
> a proposal is in the works and should be through the review process within a few days.

Bump.

**Pull request closed without merging**
