### PR TITLE
Feature/Waffle Conditional Routing to Ember App[PLAT-692]

### PR DESCRIPTION
**Pull request by pattisdr**
## Purpose
Figure out how to conditionally route to Ember app if the corresponding flag is active for the given user.

❗️ Note: I recommend just using flags for everything, rather than a mix of switches and flags, as the ticket described.  I believe this is actually simpler.  Flags have an `everyone` boolean field. This setting overrides all other potential toggles on the flag, making it behave identically to a switch.   For example, I set 'everyone' to True, and it is active for everyone, all the time.  This way we just have to deal with the `Flag` model.

❗️Note: specific ember flags that are being added to the db should be verified by Embosf to make sure they match with the views they are planning on implementing in Ember. See google doc on ticket.

## Changes
- Upgrades django-waffle to 0.13 which has some bugfixes
- Used naming convention `ember_<page_name>_page` for waffle flags
- Created a decorator for the flask views called `ember_flag_is_active`.  Pass in the flag name.  If ember flag is active, calls the `use_ember_app` view.  Otherwise, calls the specified view.
Sample usage:
```
@ember_flag_is_active('ember_support_page')
def support():
    return {}

```
- Created a data migration to add flags for the pages specified in [Product Page:EmbOSF](https://openscience.atlassian.net/wiki/spaces/PRODUC/pages/56451563/Product+Page+EmbOSF) 
- Added decorator to views for pages on list to be emberized.

## Ticket

https://openscience.atlassian.net/browse/PLAT-692

### CODE REVIEW

**Comment by brianjgeiger** [comment]
@pattisdr So you know, there's a testing/build problem

```
ProgrammingError: relation "waffle_flag" does not exist
E   LINE 1: INSERT INTO "waffle_flag" ("name", "everyone", "percent", "t...
```

**Comment by pattisdr** [comment]
thanks @brianjgeiger, working on this more today.

**Comment by pattisdr** [comment]
@brianjgeiger @binoculars can you verify that the flags I am putting in the db are sufficient for this first batch of pages you are converting? Here are a few url's that I am not sure which view they should match to - [see spreadsheet for details](https://docs.google.com/spreadsheets/d/13wKa6WtqEvOU0ITes6byU6gpaGByVUEy7ije66DKcT0/edit?usp=sharing).  Orange I am unsure of.

**Comment by pattisdr** [comment]
mainly the draft registration stuff, I am not sure which pages you are actually changing from the description.  Also, the landing page/dashboard/views, (home logged in/logged out), multiple views OSF side direct to these pages, depending on whether you're logged in/logged out.

**Comment by binoculars** [comment]
@pattisdr I think this is a sufficient start. We have the /support page and the logged-in (dashboard) page now. The logged-out (home) dashboard is in-progress. We should keep those flags as you have them in the spreadsheet. CAS is out of scope for this, since it lives in the CAS repo. I'm unsure abou the registration GUID (not familiar). @aaxelb is working on the GUID routing.

**Comment by pattisdr** [comment]
thanks @binoculars, and we can always change the flags later once you get around to implementing the later pages, if needed.

**Comment by brianjgeiger** [comment]
Agreed, I think the way it's broken out with tags looks good to me. The registration-guid hierarchy won't be the same as project-guid; it will eventually go to the Registries team.

**Comment by binoculars** [comment]
@sloria is it ready to merge? Need this on develop more than next-platform

**Comment by pattisdr** [comment]
Closing in favor of https://github.com/CenterForOpenScience/osf.io/pull/8208

**Pull request closed without merging**
