### PR TITLE
Fix Visible Contributor Swap Bug

### LINKED ISSUE #3765: Sharing Tab: incorrect error 'Must have at least one visible contributor'
## Steps
1. Go to a project you are admin on
2. Go to the project sharing tab
3. Add another contributor, preferably one that is also you
4. On the sharing tab, in the contributor table give the contributor that is not you read only permissions and save the changes
5. Now uncheck the box for yourself to be bibliographic, but do not change you admin status. Save the changes
6. Reorder the contributors so that the read access bibliographic contributor is first and the admin non-bibliographic contributor is second. Save the changes
7. Now drag to reorder the contributors, moving the first into the second position

## Expected
I would expect the reorder would not initiate the error message and would only show the save changes button.

## Actual
The reorder causes an error on the page the 'Must have at least one visible contributor', which is incorrect.
screenshot 2015-07-23 09 22 35

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h1> Purpose </h1>
Fix bug where changing the first contributors visibility would raise unnecessary error. Close #3765.
<h1> Changes </h1>
set_visible now can accept a list of user dicts being modified and check against that to see whether an error should be raised.
<h1> Side Effects </h1>
None that I know of.

### CODE REVIEW

**Comment by sloria** [comment]
`set_visible`'s responsibility is to toggle the visibility of a single user, so it feels incorrect to do a check over multiple contributors in that method. It might make more sense to do the check for >= 1 visible contrib in the `manage_contributors` method instead.

**Comment by sloria** [comment]
Pass finished.

**Comment by Johnetordoff** [comment]
The problem using manage_contributors to do the check is that it breaks a few tests, should I just change them?

**Comment by sloria** [comment]
The tests should reflect the expected behavior. If the expected behavior is changed, then the failing tests should be changed accordingly. If not, then there's a bug that needs to be addressed.

**Comment by Johnetordoff** [comment]
I think someone using the ```set_visible``` function has a reason expectation that the result will be validated. Also there are a few instance where validation is already done this way on the site that I don't want to root around and change. This new solution keeps the check in ```set_visible``` but ensure the end user can throw an error using ```manage_contributor```

**Comment by sloria** [comment]
Great. @Johnetordoff Can you please add a regression test to verify the fix?

**Comment by Johnetordoff** [comment]
@sloria How's about that? Am I good?

**Comment by sloria** [comment]
Looks good

**Pull request merged**
