### PR TITLE
Fix Node.objects.get_children [OSF-7395]

### PR DESCRIPTION
**Pull request by cwisecarver**
## Purpose

Make node.objects.get_children stop killing the postgres server.

## Changes

Switch from recursive CTE to python.

## Side effects

Node links will not be followed or returned by this implementation. This was my understanding of the correct behavior. That makes it so that you can never create at circular loop that will run until maximum recursion depth.

Places where this is likely to affect:

- Anything in the API using node filters on root
- Probably the bulk change privacy for node and its children that was updated a year or so ago
- Showing orphaned children in the file viewer and component list
- Institution affiliation settings for projects

## Ticket
[#OSF-7395](https://openscience.atlassian.net/browse/OSF-7395)

### CODE REVIEW

**Comment by cwisecarver** [comment]
Dis? https://openscience.atlassian.net/browse/OSF-7395?filter=16800

**Comment by cwisecarver** [comment]
I tried several ways to include Jira in on the secret of my pull request. It's not listening to me.

**Comment by cwisecarver** [comment]
I see.

**Comment by sloria** [comment]
Implementation looks correct.

Looks like the only place we use get_children is for filtering by `root` in APIv2. @brianjgeiger Do you know which OSF features do this? Would be good to know where QA should look for any performance problems.

**Comment by cwisecarver** [comment]
These are also not intentionally ordered. So ... someone should say that's okay.

**Comment by sloria** [comment]
Found one usage of `root` filtering: https://github.com/CenterForOpenScience/osf.io/blob/63669eab5fcc10e8ebd2d5353f32defc8ce52038/website/static/js/institutionProjectSettings.js#L12 , which is used on the Institutions affiliation settings on project "Settings" pages.

**Comment by cwisecarver** [comment]
Wait for tests to pass and ask for forgiveness rather than permission?

**Comment by brianjgeiger** [comment]
I've updated the PR description with things to test.

**Pull request merged**
