### PR TITLE
make institution.find not get deleted_insts

### PR DESCRIPTION
**Pull request by hmoco**
## Purpose

prevent deleted institutions from being accidently found.

## Changes

added argument to .find on institution that by default adds ` Q('is_deleted', 'ne', True) `

## Side effects

To find a deleted inst, one would have to call `.find` with a deleted=True argument.

### CODE REVIEW

**Comment by hmoco** [comment]
@icereval, let me know if there was a ticket for this

**Comment by sloria** [comment]
Hm, I'm not sure if it's desirable to add an arbitrary query (`is_deleted=False`) by default. After all, `Institution.find()` is meant to behave like `StoredObject.find()`. It might be slightly better to just add the `is_deleted=False` query to the `Institution.find(..)` calls where appropriate.

That said, I don't feel strongly against this PR's approach.

**Comment by hmoco** [comment]
although I agree that ` .find ` methods should behave similarly (ideally exactly the same), I can't think of a single scenario where returning a deleted institution is desired, and there isn't one in the current institutions codebase, meaning ` is_deleted=False ` would have to be added to every ` Institution.find() ` call.

**Comment by hmoco** [comment]
@sloria ^ that's my thought process for this, only added the deleted argument to prevent completely disallowing returning deleted Institutions. Ultimately, your call, I can see the benefits of both.

**Comment by sloria** [comment]
Your rationale is valid. You could also argue that `is_deleted` is an implementation detail and that deleted Institutions/Nodes should be treated as if they didn't exist in the database, in which case excluding them by default makes sense. Let's go with that.

Can you add a test for your change? Once that's done, this is good to merge.

**Comment by hmoco** [comment]
added an api test, do you think there should be a model test for the deleted find argument?

**Comment by sloria** [comment]
A model test wouldn't hurt; would be good to test the default (Institition.find() doesn't return deleted institutions) as well as the non-default (.find(deleted=True)).

**Comment by hmoco** [comment]
there they are!

**Comment by sloria** [comment]
Thanks; good to merge when build passes.

**Comment by GaryKriebel** [comment]
@sloria .... I'm guessing 0.66.0 is no longer valid?

**Comment by sloria** [comment]
@GaryKriebel Hotfixes are going into 0.66.0

**Comment by GaryKriebel** [comment]
Ah, yes... makes sense

**Pull request merged**
