### PR TITLE
[Feature Fix] project settings config notifications icons

### PR DESCRIPTION
**Pull request by leb2dg**
# Purpose

This resolves issue #3033. The icons that are displayed on the the project settings page in the *Configure Notifications* widget display only folders.

# Changes

`resolveIcon` in *notificationsTreebeard.js* now calls `resolveIconView` from *fangorn.js*. The category of the node, the read permission, and the nodeType is added to what is returned by `format_data` in *utils.py*. This is necessary so that `resolveIconView` can return the proper icon. The old resolveIcon code was removed from *notificationsTreebeard.js*. Five tests in *test_notifications.py* were updated to include the added data.

# Side effects

Due to the addition of data being returned by `format_data` in `website/notifications/utils.py`, multiple tests fail that are checking the format. The added data was added to the tests. Under *Configure Notifications* on the project setting page, the correct icon is displayed next to the title of the component.

# Screen Shots
Fix:
screen shot 2015-06-12 at 10 41 27 am

Problem:
screen shot 2015-06-12 at 10 41 50 am

### CODE REVIEW

**Comment by leb2dg** [comment]
@sloria There are a bunch of tests that are failing because they are checking the format of the data returned by notifications. I added to the data so that I could render the icons...do I need to update the tests or try and find another solution?

**Comment by samanehsan** [comment]
@leb2dg, you will need to update the tests to include the data that you added.

**Comment by leb2dg** [comment]
Will do, thanks!

**Comment by leb2dg** [comment]
@samanehsan my tests pass now :smile:

**Comment by samanehsan** [comment]
Great! This looks good to me @sloria :sunglasses:

**Pull request merged**
