### PR TITLE
Include api relationships even if embedding [OSF-6488]

### PR DESCRIPTION
**Pull request by brianjgeiger**
## Purpose

Keep the relationship link when embedding the relationship

## Changes

1. Pull the relationship link creation out of the else block in the serializer
2. Add a test

## Side effects

No

## Ticket

https://openscience.atlassian.net/browse/OSF-6488

### CODE REVIEW

**Comment by pattisdr** [comment]
I would update this outdated comment https://github.com/brianjgeiger/osf.io/blob/51e4a55d05da3b04206213f6d553a345cc75ebd1/api/base/serializers.py#L1012

**Comment by pattisdr** [comment]
Pass finished - just the one comment, looks great!

**Comment by pattisdr** [comment]
Looks good!

**Comment by samchrisinger** [comment]
🚢 it

**Pull request merged**
