### PR TITLE
Add "All my preprints" as permanent collection to My Projects [OSF-7032]

### PR DESCRIPTION
**Pull request by caneruguz**
## Purpose
To support the preprint pages, add a section to MyProjects to show a system collection with user preprints and highlight preprints with separate color. 

## Changes
1. Add "All my preprints" as system collection
2. Add fa-file-text icon to indicate which projects are preprints wherever they are rendered in the project organizer
3. Add small box in information panel to denote a project is a preprint
4. Preprint links go to ```preprints/guid``` rather than project page. 

_See numbers shown in attached screenshot._

## Ticket
https://openscience.atlassian.net/browse/OSF-7032

## Screenshot
osf___my_projects

## TODO
- [x] No preprints empty message 
- Orphaned Preprints (No api endpoint for this yet)

### CODE REVIEW

**Comment by brianjgeiger** [comment]
🎉 🐧 🎉 This is good once it passes Travis.

**Comment by caneruguz** [comment]
@brianjgeiger I don't think this Travis fail is due to the code here but I'm not sure, can you check? 
```
 ✗ creates new identifiers
	TypeError: Fake XHR onreadystatechange handler threw exception: 'undefined' is not an object (evaluating 'response.data.map') (/home/travis/build/CenterForOpenScience/osf.io/website/static/js/tests/tests.webpack.js:131124:0 <- webpack:///website/static/js/contribAdder.js:257:0)
```

**Comment by brianjgeiger** [comment]
It's not. I restarted https://travis-ci.org/CenterForOpenScience/osf.io/jobs/160243422

**Comment by caneruguz** [comment]
hey @brianjgeiger is this good to go?

**Comment by brianjgeiger** [comment]
Yup. If you need me to do merging etc, switch it to an OSF Ticket with a component of "improvement" and put it into the Passed CR column in the current sprint.

**Comment by caneruguz** [comment]
@brianjgeiger I updated the PR to show the correct ticket information for the ticket on OSF

**Pull request merged**
