### PR TITLE
[Feature Fix] Fixed un-init-ed github repo not displaying master branch in hgrid/tr…

### PR DESCRIPTION
**Pull request by bdyetton**
…eebeard  dropdown

Closes part of #3122 a commit (#55) to waterbutler closes the other part of that issue 

An un-init-ed repo returns an empty list of branches, now we check this and make sure the default branch populates the list if its empty.
No sideeffects

### CODE REVIEW

**Comment by bdyetton** [comment]
Why is this failing a test somewhere i have not touched or changed?

**Comment by sloria** [comment]
Don't worry about the failing tests. Those were already on develop when you branched off of it, and have since been addressed.

**Comment by bdyetton** [comment]
Coolio Stevio

On Tue, Jun 30, 2015 at 9:49 AM, Steven Loria <notifications@github.com>
wrote:

> Don't worry about the failing tests. Those were already on develop when
> you branched off of it, and have since been addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/pull/3378#issuecomment-117190601>
> .
>



-- 
Regards,
*Ben Yetton*

Graduate Student,
Mednick Sleep and Cognition Lab,
University Of California, Riverside
900 University Ave
Riverside, CA 92521
benjamin.yetton@email.ucr.edu

**Comment by sloria** [comment]
Will wait until https://github.com/CenterForOpenScience/waterbutler/pull/55 is merged before merging this PR.

**Comment by bdyetton** [comment]
Ok, thats probably not going to happen until next week... This could be
merged now, but i guess the issue cant be closed until #55 is merged. Ill
remind you then.

**Comment by bdyetton** [comment]
Ste-v-e. This is ready to be merged now the the water butler fix is in too

**Comment by sloria** [comment]
Merged into release/0.43.0

**Pull request closed without merging**
