### PR TITLE
[RFR] Refactor user/me/nodes to hold onto the queryset as long as possible

### PR DESCRIPTION
**Pull request by cwisecarver**
## Purpose

Speedup dashboard page load by reducing number of queries needed for /user/me/nodes api requests.

## Changes

Used SQL annotations to gather necessary data in one query.

## Side effects

Possible that the query is only working and the tests passing because there is a limited amount of data in the database during testing and the `SELECT CASE WHEN` `JOIN` could be working randomly.

### CODE REVIEW

**Comment by cwisecarver** [comment]
- Not 100% confident about the `LIMIT 1` in the subquery being the right solution.
   - If the tests pass it might be because of a limited amount of data in the database and it just happening to work out.
- Concerned that the subquery references to columns outside the subquery aren't working

**Comment by cwisecarver** [comment]
Looks like everything is working but bulk. I'll keep digging.

**Comment by cwisecarver** [comment]
Fixed bulk. Tests passed locally, should pass on travis.

http://localhost:8000/v2/users/me/nodes/?related_counts=children&embed=contributors&version=2.2
Before: 11847.62 ms (1919 queries including 1914 duplicates ) 
After: 1793.67 ms (522 queries including 515 duplicates )

Still not good but 15% of what it used to be.

@sloria @icereval

**Comment by cwisecarver** [comment]
@icereval @sloria [I added a test for a large number of users.](https://github.com/CenterForOpenScience/osf.io/pull/6903/commits/22e4c0f5d38dad22e9fca54d128a5e68663c142e) If you wouldn't mind checking my logic but it passes locally so... gtg?

**Comment by sloria** [comment]
The added test looks good to me.

**Comment by sloria** [comment]
Doh, I accidentally closed and reopened. This is the relevant build: https://travis-ci.org/CenterForOpenScience/osf.io/builds/205867302

**Pull request merged**
