### PR TITLE
[Feature] Add links to the components and projects on file trees

### PR DESCRIPTION
**Pull request by hmoco**
## Purpose 
Components and projects should have links to their base page just like files have links for file pages, as per #3593.

## Changes
Added function gotonode that opens the window with the node clicked, be it project or component. Also, made the row clickable like files.

## Side-Effects
All trees created with fangorn that use the method _fangornMakeRow to create its rows will have links for its projects and components.

### CODE REVIEW

**Comment by sloria** [comment]
Rather than using javascript to redirect to the node page, why not render the title as a proper anchor tag? That way, we don't break common link behavior (e.g. right-clicking, Cmd-click, etc.)?

**Comment by hmoco** [comment]
Not sure, I was simply using the template used by files to redirect to the file view page. Will give using <a> a try and report back @sloria

**Comment by sloria** [comment]
We have to use JS to redirect to file view pages because files don't have URLs until they are viewed for the first time (GUIDs are generated lazily). Projects and components always have a URL, so you should be able to use anchor tags.

**Comment by hmoco** [comment]
Cool, I wasn't aware of that. The latest commit has that change.

**Comment by sloria** [comment]
Nice. :octopus:

**Pull request merged**
