### PR TITLE
[Django Upgrade] [ENG-3947] Remove `password_change` view and route in admin

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

Upgrades password reset for Django 3 [django-password-reset Changealog](https://django-password-reset.readthedocs.io/en/latest/)

⚠️ See if this is being used and where.

https://www.notion.so/cos/10-Django-Reset-Password-Update-View-e34bbfb074d244aba6d12e4a5941c1e2

⚠️ Based on Lozenge's comment I removed the views.

## Changes

- updates requirements.txt and use different import path for urls.

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

### CODE REVIEW

**Review by cslzchen — CHANGES_REQUESTED** [review]
I think we can remove these two routes since they are not used / enabled / working at all. This is not the user facing password reset (either via email link or in user settings) but the admin app.

**Review by cslzchen — APPROVED** [review]
LGTM 🎆

**Comment by cslzchen** [comment]
Rebased and removed all duplicate commits and will merge after checks pass.

**Comment by cslzchen** [comment]
Fyi @Johnetordoff and @jwalz, I added [an extra commit to remove `password_reset` from installed apps](https://github.com/CenterForOpenScience/osf.io/commit/721ef909b91924b031b272f6603e1b815b6ccb26) to the feature branch directly which fixes [a staging3 build failure](https://staging-jenkins.cos.io/job/OSF/job/build/job/osf.io/2080/execution/node/29/log/)

```
ModuleNotFoundError: No module named 'password_reset'
```

**Comment by Johnetordoff** [comment]
Strange that didn't effect unit tests, the staging3 local.py overrides that setting, maybe it's out of date.

**Pull request merged**
