### PR TITLE
Fixed youtube errors in getting started page

### PR DESCRIPTION
**Pull request by PatrickEGorman**
Purpose
Currently, a number of youtube videos in the Getting Started Page have menu bars that disappear on mouseover and have non-functional buttons.

Closes Issue https://github.com/CenterForOpenScience/osf.io/issues/2640

Changes
Put youtube videos in separate containers.  Not sure what this changes but now all the videos work.

Side Effects
Fixes problem but makes code a little more lengthy than I would have wanted

### CODE REVIEW

**Comment by chennan47** [comment]
@PatrickEGorman this bug exists on production, which means your branch should based on master branch. And when you do a hotfix, you need to create a new branch based on that instead of just directly create a pull request from your develop or master branch. Nice work on the comment part tho. 
image

**Comment by sloria** [comment]
ping @caneruguz for review of the markup/CSS for this fix.

**Comment by caneruguz** [comment]
Thanks for taking a look at this @PatrickEGorman ,this is a good first step but before it can be merged there are a few things:

- Row needs to be it's own div; as shown in the Bootstrap guidelines: http://getbootstrap.com/css/#grid
- You don't need to add col-**-12 multiple times, Bootstrap goes from lowest to highest, so if "col-sm-12" is defined then every upper size is also 12. Also in this case "col-xs" is also 12 since 12 is the default for undefined sizes. 
- But more importantly you don't need to add column sizing classes at all since the mako files inside have those already. 

I don't know why this is fixing the youtube issue but there is no clear reason why it should so that's very curious. Can you look into it a bit more?  It seems like adding a separate ```<div class="row"></div>``` might be the thing doing the trick but everything else is redundant.

**Comment by PatrickEGorman** [comment]
@chennan47 I will start working on this right away.

@caneruguz Sounds good.  I toyed with it a lot and though this is kind of ugly, it's the only thing I could get to work.  I'll work on it some more and see if I can't figure out a more efficient way of making them work.

**Comment by PatrickEGorman** [comment]
I've tried ```<div class="row"></div>``` and it's not working.  I'm going to try to simplify the solution as much as I can but it still might look a little strange....

**Comment by PatrickEGorman** [comment]
Just a quick update:  I've managed to simplify some but the aesthetic of the code still isn't ideal.  It is in the format:
``` html 
       <div class="row col-sm-12 col-md-12">
            <%include file="(template)"/>
        </div>
```
I'm not very pleased with the appearance of this and I'm sure others won't be as well.  However, I've tried pretty much everything I could think of and this is the simplest structure that works.  One of the videos is being especially difficult as it is wedged in another template and doesn't respond the same way as the others.  Hopefully I'll figure out something that works soon.

**Pull request closed without merging**
