### PR TITLE
[ENG-5328] Get docker to build image successfully

### PR DESCRIPTION
**Pull request by opaduchak**
## Purpose

Get docker image to build

## Changes
Changed dependencies to minimize code changes and changes some imports in a way for image to successfully buld

## Ticket

[ENG-5328](https://openscience.atlassian.net/browse/ENG-5328)

[ENG-5328]: https://openscience.atlassian.net/browse/ENG-5328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by felliott** [comment]
Hey @opaduchak,

This one isn't building for me. I've rebased and squashed this PR and am working off of this branch[1].  I've tried rebuilding the docker image without using the cache via:

`$ docker -D build --no-cache --progress=plain -t osf-local:beta . 2>&1 | tee docker-build-5.log`

When I do this, the build fails[2] trying to import `osf.utils.migrations`, due to its use of `from past.builtins import basestring`.  Are you not encountering this?  I don't think we need to use `past` anymore, since it is a py2<=>py3 supporting module.

Please try this again and let me know what you encounter. If you're not seeing the same thing, then I'll need to troubleshoot some more.

Cheers,
@felliott

[1] https://github.com/felliott/osf.io/tree/feature/unbreak-dockerfile
[2] Here is the build output:
```
#61 [57/58] COPY ./ ./
#61 DONE 12.9s

#62 [58/58] RUN for module in        api.base.settings        admin.base.settings    ; do        export DJANGO_SETTINGS_MODULE=$module        && python3 manage.py collectstatic --noinput --no-init-app    ; done    && for file in        ./website/templates/_log_templates.mako        ./website/static/built/nodeCategories.json    ; do        touch $file && chmod o+w $file    ; done    && rm ./website/settings/local.py ./api/base/settings/local.py
#62 1.453 WARNING:addons.osfstorage.settings.defaults:No migration settings loaded for OSFStorage, falling back to local dev. module 'website.settings' has no attribute 'MIGRATION_ENV'
#62 1.453 WARNING:addons.osfstorage.settings:No local.py settings file found
#62 1.498 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 1.522 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 1.697 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 1.721 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 1.891 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 1.914 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 1.952 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 1.978 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 2.007 Traceback (most recent call last):
#62 2.007   File "/code/manage.py", line 21, in <module>
#62 2.007     execute_from_command_line(sys.argv)
#62 2.007   File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
#62 2.008     utility.execute()
#62 2.008   File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
#62 2.010     django.setup()
#62 2.010   File "/usr/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
#62 2.010     apps.populate(settings.INSTALLED_APPS)
#62 2.010   File "/usr/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
#62 2.011     app_config = AppConfig.create(entry)
#62 2.011   File "/usr/lib/python3.10/site-packages/django/apps/config.py", line 124, in create
#62 2.015     mod = import_module(mod_path)
#62 2.015   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
#62 2.015     return _bootstrap._gcd_import(name[level:], package, level)
#62 2.015   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
#62 2.017   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
#62 2.017   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
#62 2.022   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
#62 2.024   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
#62 2.025   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#62 2.025   File "/code/osf/apps.py", line 6, in <module>
#62 2.025     from osf.migrations import (
#62 2.025   File "/code/osf/migrations/__init__.py", line 11, in <module>
#62 2.025     from osf.utils.migrations import ensure_schemas, map_schemas_to_schemablocks
#62 2.025   File "/code/osf/utils/migrations.py", line 1, in <module>
#62 2.026     from past.builtins import basestring
#62 2.026   File "/usr/lib/python3.10/site-packages/past/builtins/__init__.py", line 43, in <module>
#62 2.026     from past.builtins.noniterators import (filter, map, range, reduce, zip)
#62 2.026   File "/usr/lib/python3.10/site-packages/past/builtins/noniterators.py", line 24, in <module>
#62 2.027     from past.types import basestring
#62 2.027   File "/usr/lib/python3.10/site-packages/past/types/__init__.py", line 25, in <module>
#62 2.029     from .oldstr import oldstr
#62 2.029   File "/usr/lib/python3.10/site-packages/past/types/oldstr.py", line 5, in <module>
#62 2.029     from collections import Iterable
#62 2.029 ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
#62 2.757 WARNING:addons.osfstorage.settings.defaults:No migration settings loaded for OSFStorage, falling back to local dev. module 'website.settings' has no attribute 'MIGRATION_ENV'
#62 2.757 WARNING:addons.osfstorage.settings:No local.py settings file found
#62 2.795 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 2.804 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 3.021 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 3.029 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 3.208 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 3.231 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 3.268 INFO:RefactoringTool:Skipping optional fixer: idioms
#62 3.287 INFO:RefactoringTool:Skipping optional fixer: ws_comma
#62 3.307 Traceback (most recent call last):
#62 3.307   File "/code/manage.py", line 21, in <module>
#62 3.307     execute_from_command_line(sys.argv)
#62 3.307   File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
#62 3.308     utility.execute()
#62 3.308   File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
#62 3.309     django.setup()
#62 3.309   File "/usr/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
#62 3.309     apps.populate(settings.INSTALLED_APPS)
#62 3.309   File "/usr/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
#62 3.309     app_config = AppConfig.create(entry)
#62 3.309   File "/usr/lib/python3.10/site-packages/django/apps/config.py", line 124, in create
#62 3.310     mod = import_module(mod_path)
#62 3.310   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
#62 3.310     return _bootstrap._gcd_import(name[level:], package, level)
#62 3.310   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
#62 3.310   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
#62 3.311   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
#62 3.311   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
#62 3.311   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
#62 3.311   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#62 3.312   File "/code/osf/apps.py", line 6, in <module>
#62 3.313     from osf.migrations import (
#62 3.313   File "/code/osf/migrations/__init__.py", line 11, in <module>
#62 3.313     from osf.utils.migrations import ensure_schemas, map_schemas_to_schemablocks
#62 3.313   File "/code/osf/utils/migrations.py", line 1, in <module>
#62 3.314     from past.builtins import basestring
#62 3.314   File "/usr/lib/python3.10/site-packages/past/builtins/__init__.py", line 43, in <module>
#62 3.314     from past.builtins.noniterators import (filter, map, range, reduce, zip)
#62 3.314   File "/usr/lib/python3.10/site-packages/past/builtins/noniterators.py", line 24, in <module>
#62 3.314     from past.types import basestring
#62 3.314   File "/usr/lib/python3.10/site-packages/past/types/__init__.py", line 25, in <module>
#62 3.315     from .oldstr import oldstr
#62 3.315   File "/usr/lib/python3.10/site-packages/past/types/oldstr.py", line 5, in <module>
#62 3.315     from collections import Iterable
#62 3.315 ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
#62 ERROR: process "/bin/sh -c for module in        api.base.settings        admin.base.settings    ; do        export DJANGO_SETTINGS_MODULE=$module        && python3 manage.py collectstatic --noinput --no-init-app    ; done    && for file in        ./website/templates/_log_templates.mako        ./website/static/built/nodeCategories.json    ; do        touch $file && chmod o+w $file    ; done    && rm ./website/settings/local.py ./api/base/settings/local.py" did not complete successfully: exit code: 1
------
 > [58/58] RUN for module in        api.base.settings        admin.base.settings    ; do        export DJANGO_SETTINGS_MODULE=$module        && python3 manage.py collectstatic --noinput --no-init-app    ; done    && for file in        ./website/templates/_log_templates.mako        ./website/static/built/nodeCategories.json    ; do        touch $file && chmod o+w $file    ; done    && rm ./website/settings/local.py ./api/base/settings/local.py:
3.314     from past.builtins import basestring
3.314   File "/usr/lib/python3.10/site-packages/past/builtins/__init__.py", line 43, in <module>
3.314     from past.builtins.noniterators import (filter, map, range, reduce, zip)
3.314   File "/usr/lib/python3.10/site-packages/past/builtins/noniterators.py", line 24, in <module>
3.314     from past.types import basestring
3.314   File "/usr/lib/python3.10/site-packages/past/types/__init__.py", line 25, in <module>
3.315     from .oldstr import oldstr
3.315   File "/usr/lib/python3.10/site-packages/past/types/oldstr.py", line 5, in <module>
3.315     from collections import Iterable
3.315 ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
------
Dockerfile:163
--------------------
 162 |     
 163 | >>> RUN for module in \
 164 | >>>        api.base.settings \
 165 | >>>        admin.base.settings \
 166 | >>>    ; do \
 167 | >>>        export DJANGO_SETTINGS_MODULE=$module \
 168 | >>>        && python3 manage.py collectstatic --noinput --no-init-app \
 169 | >>>    ; done \
 170 | >>>    && for file in \
 171 | >>>        ./website/templates/_log_templates.mako \
 172 | >>>        ./website/static/built/nodeCategories.json \
 173 | >>>    ; do \
 174 | >>>        touch $file && chmod o+w $file \
 175 | >>>    ; done \
 176 | >>>    && rm ./website/settings/local.py ./api/base/settings/local.py
 177 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c for module in        api.base.settings        admin.base.settings    ; do        export DJANGO_SETTINGS_MODULE=$module        && python3 manage.py collectstatic --noinput --no-init-app    ; done    && for file in        ./website/templates/_log_templates.mako        ./website/static/built/nodeCategories.json    ; do        touch $file && chmod o+w $file    ; done    && rm ./website/settings/local.py ./api/base/settings/local.py" did not complete successfully: exit code: 1
329  /usr/local/bin/dockerd --containerd /run/containerd/containerd.sock --pidfile /run/desktop/docker.pid --swarm-default-advertise-addr=eth0 --host-gateway-ip 192.168.65.254
github.com/moby/buildkit/executor/runcexecutor.exitError
	/root/build-deb/engine/vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go:375
github.com/moby/buildkit/executor/runcexecutor.(*runcExecutor).Run
	/root/build-deb/engine/vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go:336
github.com/moby/buildkit/solver/llbsolver/ops.(*ExecOp).Exec
	/root/build-deb/engine/vendor/github.com/moby/buildkit/solver/llbsolver/ops/exec.go:373
github.com/moby/buildkit/solver.(*sharedOp).Exec.func2
	/root/build-deb/engine/vendor/github.com/moby/buildkit/solver/jobs.go:911
github.com/moby/buildkit/util/flightcontrol.(*call[...]).run
	/root/build-deb/engine/vendor/github.com/moby/buildkit/util/flightcontrol/flightcontrol.go:121
sync.(*Once).doSlow
	/usr/local/go/src/sync/once.go:74
sync.(*Once).Do
	/usr/local/go/src/sync/once.go:65
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
```

**Comment by opaduchak** [comment]
Now docker builds should be working, I don't know how it worked before, but now it should be good
[docker-build.log](https://github.com/CenterForOpenScience/osf.io/files/14420012/docker-build.log)

Just in case I'm attaching logs

**Comment by felliott** [comment]
LGTM! Merging.

**Comment by felliott** [comment]
Weird. This PR has been rebased and merged, but the usual git trick of mentioning "Closes #<pr-number>" in the commit message didn't seem to take. Nevertheless, this has been merged as of https://github.com/CenterForOpenScience/osf.io/commit/ea146eb35c33861e91aa4923351953c7c39d960a

**Pull request closed without merging**
