### PR TITLE
Fix button capitalization

### PR DESCRIPTION
**Pull request by geeksnglitter**
Delete component button leaves word "component" lowercase.

### CODE REVIEW

**Comment by sloria** [comment]
This fix is incorrect; the `.capitalize()` call is outside the mako `${}`. 

Also, I'm -0 on title-casing button text. Convention seems to be capitalizing only the first word:

GitHub

fix_button_capitalization_by_geeksnglitter_ _pull_request__3830_ _centerforopenscience_osf_io

centerforopenscience_osf_io

options

Dropbox

dropbox

account_-_dropbox

Google

foo_-_google_search

Closing this for now.

**Comment by sloria** [comment]
@caneruguz Would be worth documenting a guideline for this.

**Comment by geeksnglitter** [comment]
The convention shown through the style guide is title case.

**Comment by caneruguz** [comment]
@geeksnglitter that's not an explicit guideline statement, we still have some place to address this other than examples. Do you want to start an issue in styleguide to discuss?

**Comment by sloria** [comment]
@geeksnglitter There was no explicit decision to use title-case for any of the buttons on the current site; any (in)consistency is happenstance. 

As Caner points out, an issue on the style guide seems to be the next step here.

**Pull request closed without merging**
