### PR TITLE
[Feature] Point to new styles commit [OSF-8515]

### PR DESCRIPTION
**Pull request by fabmiz**
## Purpose

Update styles bower dependency

## Changes

Pin to the latest styles commit 
at https://github.com/CenterForOpenScience/styles/commits/master

## QA Notes

See the main PR for this ticket

## Ticket

[OSF-8515](https://openscience.atlassian.net/browse/OSF-8515)

### CODE REVIEW

**Comment by brianjgeiger** [comment]
I'm afraid your good deed has landed you a little more work. A couple of tests are failing, my guess because of quirks about how we test all the many many citations. Could you look into those? https://travis-ci.org/CenterForOpenScience/osf.io/jobs/312005908 

```
____________________ TestCiteprocpy.test_passing_citations _____________________
[gw2] linux2 -- Python 2.7.13 /home/travis/virtualenv/python2.7.13/bin/python
tests/test_citeprocpy.py:38: in test_passing_citations
    citeprocpy = render_citation(node, k)
api/citations/utils.py:58: in render_citation
    bib_style = CitationStylesStyle(path, validate=False)
../../../virtualenv/python2.7.13/lib/python2.7/site-packages/citeproc/frontend.py:60: in __init__
    raise ValueError("'{}' is not a known style".format(style))
E   ValueError: '/home/travis/build/CenterForOpenScience/osf.io/website/static/vendor/bower_components/styles/international-journal-of-gynecology-and-obstetrics.csl' is not a known style
____________________ TestCiteprocpy.test_failing_citations _____________________
[gw1] linux2 -- Python 2.7.13 /home/travis/virtualenv/python2.7.13/bin/python
tests/test_citeprocpy.py:22: in test_failing_citations
    citeprocpy = render_citation(node, k)
api/citations/utils.py:58: in render_citation
    bib_style = CitationStylesStyle(path, validate=False)
../../../virtualenv/python2.7.13/lib/python2.7/site-packages/citeproc/frontend.py:60: in __init__
    raise ValueError("'{}' is not a known style".format(style))
E   ValueError: '/home/travis/build/CenterForOpenScience/osf.io/website/static/vendor/bower_components/styles/insectes-sociaux.csl' is not a known style
============================ pytest-warning summary ============================
```

**Comment by brianjgeiger** [comment]
@fabmiz Could you pull from develop and try running those tests locally to see if maybe the recent styles migration helped with that?

**Comment by fabmiz** [comment]
@brianjgeiger The tests ran fine locally even before the styles migration, so I will just pull from develop and push, travis will tell.

**Comment by brianjgeiger** [comment]
@fabmiz So what I think is happening here is that the json file that was generated to test the data has some styles that they've since removed from the styles repo. You can probably remove those two lines and it should work fine.

**Comment by fabmiz** [comment]
I figured that was the case, they moved those to the dependent folder. But it's more complicated than anticipated. Lots of styles got updated, around 94, hence the `test_passing_citations` fails. So I am updating the `/website/static/citeprocpy_test_data.json` with the new styles. Another problem is that some of styles got renamed. One last major problem is that some styles (we currently have in db with `has_bibliography` set true) don't have the bibliography anymore because they are inheriting from some new file.

**Comment by brianjgeiger** [comment]
Okay, I think I'll bump this from the release and let you do additional development on it for our next release.

**Comment by fabmiz** [comment]
Okay. Yes, I think that's a reasonable move.  Also, if we want to cover the new styles in tests, we will probably need to add more than 1000 new lines in `/website/static/citeprocpy_test_data.json`. so this should be done in a rush.

**Comment by brianjgeiger** [comment]
Agreed. I believe Henrique used a script of some sort to generate that, though I don't know if it's checked in or how it works. Ideally, you run that, it separates out the successes from the failures, you verify the failures to be for valid reasons, and you have a json file.

**Comment by mfraezz** [comment]
Merged via faf55c1aac3c08b90561550b74df7cb4d4cbbc24, closing

**Pull request closed without merging**
