### PR TITLE
Institutions Search

### PR DESCRIPTION
**Pull request by hmoco**
## Purpose

Allow institutions to be findable by search.

### Search Specs:
 - A user can type the name of the institution ('University of Notre dame') or pieces of the name ('notre'), and that will find the institution itself, and all public nodes with that institution as its primary institution (later affiliated institution). 
 - A user can type the university id, which is often its initials, to find the institution itself. ('nd' will return Notre Dame). 
 - Searching the word 'institution' will also find all institutions.
 - There is also a filter on the left bar for Institutions.

Add an institution category and serialize them.
screen shot 2016-04-22 at 4 33 29 pm
screen shot 2016-04-22 at 4 33 21 pm

## Ticket

https://openscience.atlassian.net/browse/OSF-6085

### CODE REVIEW

**Comment by sloria** [comment]
@hmoco Can you post a screenshot of what the search results look like?

**Comment by hmoco** [comment]
yep, this is also a WIP, I need to figure out why search is buggy on staging (probably migration needed)

**Comment by hmoco** [comment]
@sloria, ready for you.

**Comment by sloria** [comment]
Looks good. Cherry-picked into `release/0.68.0`.

**Pull request closed without merging**
