### PR TITLE
[OSF-7606] Speed up /user/me/nodes

### PR DESCRIPTION
**Pull request by chrisseto**
See commit messages

### CODE REVIEW

**Comment by sloria** [comment]
Getting an error locally when visiting `/users/me/nodes/?embed=contributors&embed=parent`. Looking into it.

**Comment by chrisseto** [comment]
@sloria with this branch only?

**Comment by sloria** [comment]
@chrisseto Yes.

**Comment by sloria** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/code/api/base/serializers.py", line 936, in to_representation
    self.child.to_representation(item, envelope=envelope) for item in data
  File "/code/api/base/serializers.py", line 1133, in to_representation
    result = self.context['embed'][field.field_name](obj)
  File "/code/api/base/views.py", line 112, in partial
    ret = view.handle_exception(e).data
  File "/code/api/base/views.py", line 109, in partial
    ret = view.paginator.get_paginated_response(ret).data
  File "/code/api/base/pagination.py", line 206, in get_paginated_response
    response = super(NodeContributorPagination, self).get_paginated_response(data)
  File "/code/api/base/pagination.py", line 117, in get_paginated_response
    reversed_url = reverse(view_name, kwargs=kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'node-contributors' with arguments '()' and keyword arguments '{'node_id': u'bsun2', 'parent_obj': <Node: (title=u'Existence grotto classification unique composition laser dissolution kilometer.', category=u'project') with guid u'bsun2'>, 'version': u'v2'}' not found. 1 pattern(s) tried: [u'(?P<version>(v2))/nodes/(?P<node_id>\\w+)/contributors/$']
[28/Mar/2017 12:09:30] "GET /v2/users/me/nodes/?embed=contributors HTTP/1.1" 500 59
```

**Comment by chrisseto** [comment]
I'll double check that I didn't eat any commits.

**Comment by chrisseto** [comment]
```
(osf) ~/D/C/osf.io git:feature/performance-enhancements ❯❯❯ g df origin/feature/makfastpls --stat
(osf) ~/D/C/osf.io git:feature/performance-enhancements ❯❯❯
```
And to rephrase for clarity, the behavior of this branch is different than #7011 ?

**Comment by sloria** [comment]
Oh, I'm haven't checked if the ug is on #7011. I'll take a look.

**Comment by sloria** [comment]
The issue doesn't appear on #7011

**Comment by chrisseto** [comment]
:wat:

**Comment by sloria** [comment]
Bah, I can't reproduce the error now... I'll poke around a little more, but I think this is good to merge.

**Comment by sloria** [comment]
Hm, now I'm getting a 500 when visiting contributor detail endpoints:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/site-packages/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 676, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/code/api/base/renderers.py", line 28, in get_context
    context = super(BrowsableAPIRendererNoForms, self).get_context(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 619, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 521, in get_raw_data_form
    if not self.show_form_for_method(view, method, request, instance):
  File "/usr/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 419, in show_form_for_method
    view.check_object_permissions(request, obj)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 329, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/code/api/nodes/permissions.py", line 80, in has_object_permission
    assert isinstance(obj, (AbstractNode, User)), 'obj must be User or Node, got {}'.format(obj)
AssertionError: obj must be User or Node, got Contributor object
```

I'll look into this before crying wolf again.

**Comment by sloria** [comment]
Looks like the above bug could only be triggered through the browse-able API. Fixed in https://github.com/chrisseto/osf.io/pull/20/files

**Pull request merged**
