### PR TITLE
Upgrade MathJax

### PR DESCRIPTION
**Pull request by samchrisinger**
## Purpose

Upgrade MathJax and resolve https://openscience.atlassian.net/browse/OSF-5876

## Changes

MathJax#2.5 -> MathJax2.6

Before (notice trailing |)
screen shot 2016-04-13 at 11 56 38 am
After
screen shot 2016-04-13 at 11 58 57 am

### CODE REVIEW

**Comment by samchrisinger** [comment]
@sloria @brianjgeiger 
From the MathJax changelog:
> Semi-slim MathJax repository for bower. You can now use bower install components/MathJax to install a fork of MathJax without PNG fonts. Many thanks to @minrk from the IPython/Jupyter team and to the team at components!
> MathJax via npm. You can now use npm install mathjax to install a copy of MathJax without PNG fonts.

Do either of these seem like they're worth investigating?

**Comment by brianjgeiger** [comment]
In general, we prefer npm. Either would be awesome.

**Comment by samchrisinger** [comment]
Sorry **minrk** for accidental spam.

**Comment by samchrisinger** [comment]
I tried the npm installed version and it seems like it's not going to be webpack friendly. Perhaps for now, just stick with the bower version. Sounds like this is targeted for MathJax#3.0 https://groups.google.com/d/msg/mathjax-users/UT9qMPPwbzg/N5mnj3ORBQAJ

**Comment by brianjgeiger** [comment]
Awesome. Can you add two screen shots of without and with the fix (and maybe the text tag to put into the wiki) so QA will be able to easily test?

**Comment by brianjgeiger** [comment]
Once we have that, this is ready to merge.

**Comment by samchrisinger** [comment]
@brianjgeiger ready

**Pull request merged**
