### PR TITLE
[Ready for Review] Node Refactor ProjectOrganizer

### PR DESCRIPTION
**Pull request by samchrisinger**
## Purpose

Originally included in https://github.com/CenterForOpenScience/osf.io/pull/2360/commits, now split into a separate PR dependent on https://github.com/CenterForOpenScience/osf.io/pull/2544.

Focuses on updates to ProjectOrganizer frontend and backend. 

## Changes

Add the ability to show project structure without revealing sensitive information. Before if a node was orphaned due to permissions issues it simply showed as a top level element of 'All My Projects'. Now a tree is constructed that shows the minimal set of nodes necessary to reach each node the user is a contributor on. Nodes that user can't see grayed-out and show no information. 

screen shot 2015-04-22 at 11 20 16 am

screen shot 2015-04-22 at 11 19 49 am

## Side Effects

These changes are largely restricted to ProjectOrganizer.

### CODE REVIEW

**Comment by brianjgeiger** [comment]
That greying is a little extreme and looks like a highlight. We should consider some other way of representing that data. Maybe everything is the same except the text is in italics, and perhaps some sort of icon overlay if we can find something that will work well?

**Comment by brianjgeiger** [comment]
If we do italics, we'll have to change the Smart Collections styling to something else. We could just replace the icon with a lock icon and leave the styling the same.

**Comment by samchrisinger** [comment]
Ok, I like the idea of a lock. Updating to reflect these comments

**Comment by sloria** [comment]
@samchrisinger Can this PR be closed?

**Comment by samchrisinger** [comment]
@sloria the referenced issue: https://github.com/CenterForOpenScience/osf.io/issues/2677 is still unaddressed.

**Comment by sloria** [comment]
OK, thanks Sam; will keep this open for now. @GaryKriebel @lbanner Let's get this in the queue, probably next epic.

**Comment by GaryKriebel** [comment]
Noted for next epic.

**Pull request closed without merging**
