### PR TITLE
Refresh page after generating DOI and ARK.

### PR DESCRIPTION
**Pull request by rohan-bajaj**
# Purpose

Currently when you generate a DOI and ARK for your project the citation widget does not update to include the identifiers until the user refreshes the page. This confuses some users and with this pull request they do not have to know when they must click refresh. Furthermore with this pull request any other uses of identifiers on the project page that may be added later would also be updated.

Closes issue: https://github.com/CenterForOpenScience/osf.io/issues/2486

# Changes

After the user asks to generate identifiers, if the identifiers are created the page refreshes thereby updating all places that would use identifiers.

# Side Effects 

Because of this change the unit test is sent into a loop and fails because it does not realize that you can only create identifiers once for a public project/registration. Therefore, a refresh will only be called once on that page.

### CODE REVIEW

**Comment by samanehsan** [comment]
Can you look into why tests won't run locally? It doesn't seem to be directly related to this change but it happens to me as well when I check out your branch. Are you up to date with develop?

**Comment by samanehsan** [comment]
Can you look into the failing tests? Thanks!

**Comment by rohan-bajaj** [comment]
Yeah I'm working on fixing those tests.

**Comment by sloria** [comment]
Ideally, we shouldn't refresh the page just to update the citations text. Sam says in https://github.com/CenterForOpenScience/osf.io/issues/2486#issuecomment-93411634 that you should be able to re-fetch the citations data. @rohan-bajaj, can you look into this and send a separate PR?

**Comment by rohan-bajaj** [comment]
Yeah I'll look into it.

**Pull request closed without merging**
