### PR TITLE
[Ehancement] Apply new style guide osf-loader

### PR DESCRIPTION
**Pull request by haoyuchen1992**
### Purpose
Replace the new osf-loader whose image is created by data URI

### Change
1) Update OSF style guide version
2) Replace spinner with the new osf-loader

### Side Effect
None

### CODE REVIEW

**Comment by sloria** [comment]
The `-xl` size is large enough to be distracting on most pages; it should be used sparingly. I'm not sure that size is appropriate in all these places. 

Thoughts, @caneruguz ?

**Comment by haoyuchen1992** [comment]
@sloria Because we updated the spinner size, so xl is not that big now. Here is the update PR -- https://github.com/CenterForOpenScience/osf-style/pull/80

**Comment by caneruguz** [comment]
@sloria  the xl is not going to be bigger than what these spinners were before. But @haoyuchen1992 this might be a good opportunity to see if we should rather use smaller sizes for some of these pages. Now that we can utilize the size differences we can use different size spinners. It may not be necessary but worth taking a look.

**Comment by haoyuchen1992** [comment]
@caneruguz OK,  I will look at the usages and see whether the size should be adjusted.

**Comment by haoyuchen1992** [comment]
@caneruguz  I reduce the size of spinners on wiki menu, notification settings and citation.

**Comment by sloria** [comment]
Went ahead and merged so that other devs can begin to migrate their code if need be.

**Pull request merged**
