### PR TITLE
[Fix] Success alert for forks

### PR DESCRIPTION
**Pull request by barbour-em**
# Purpose
To give a more obvious visual notification that a fork was successfully created 

# Changes
* Add bootbox alert on a successful fork that redirects to the new fork after being closed or hitting 'OK'
* Addresses #4118

# Side effects

* User has to click before being redirected to their new fork

### CODE REVIEW

**Comment by sloria** [comment]
I'm not sure an additional modal is the proper solution to this, as it interrupts the user's flow. A non-modal solution is preferred. 

@erinmayhood may have feedback on this.

**Comment by barbour-em** [comment]
@sloria, is using a success GrowlBox a better solution?

**Comment by erinmayhood** [comment]
@barbour-em yes, I believe the GrowlBox is a better solution in this case. The user already receives a modal to confirm their desire to create the Fork so receiving another could interrupt the flow. 

Requirements:
This is a success message (so green)
It should be dismissible

Thanks.

**Comment by barbour-em** [comment]
@sloria @erinmayhood made this change :heavy_check_mark:

**Pull request merged**
