### PR TITLE
[Ready to Review] MFR Share and Embed

### PR DESCRIPTION
**Pull request by revanthkolli**
# Purpose
 The modular file renderer embeddable enables users of the OSF to share their files, via links and embeddable objects, so that they can reach a larger audience. Upon completion, users will be able to obtain and distribute links for their documents in public projects on the OSF so others can then view the same rendered files.  In addition, users will also be provided two different methods of embedding those documents, one in which the iFrame is dynamically rendered and another which provides the iFrame directly.

# Changes 
One button would be added to the existing row of buttons on the page in which files are currently rendered, next to the download button. The button, labeled “Share”, will toggle a popover component containing two tabs, one for the share link and one for the necessary information for embedding the rendered document (CSS style link and HTML/JavaScript). The tab for embedding provides two methods along with a show more button, which expands UI for the user to customize the height and width of the iFrame for the second embedding option. There are also tooltips that appear on hover of the titles for the two embed options that describe the differences.

The button will have a popover component, where the data content will contain the different information necessary for sharing/embedding. For sharing, the url portion of the download link that already exists needs to be provided. For embedding dynamically, the mfrIframe that renders the current document needs to be provided, as well as the script and stylesheet code (from view_file.mako and index.js respectively). For direct embedding, the iFrame itself needs to be provided directly. 
Popover components are features that are provided by bootstrap and enabled via JavaScript with the popover() function and the id or class of the element, which in this case are the two different buttons. The placement of the popover and its content can then be set using the tags data-toggle, data-placement, and data-content in the element. To enable the popover, the user would click on the button. The popover will then be available with the relevant information until the user clicks on the button again to disable it. 

Two options are being provided for embedding documents because of a difference in preference. The first option dynamically renders the iFrame so that various attributes, such as  the height of the iFrame, can be determined using JavaScript. The second option allows the user to customize the height and width of the iFrame so that it fits their needs and provides a scrollable iFrame for that reason. We would prefer users to use the first option more, but the second option is also needed for those users who would prefer not to link to an external JavaScript file for security reasons or would prefer customized sizing of the iFrame they are embedding. 

# TODO 
- [x] Create two buttons with popovers 
- [x] Add necessary information to popovers 
- [x] Combine buttons into one Share button with tabs for Share and Embed within one Popover
- [x] Disable button for private projects 
- [x] Customizable height and width (Show More)
- [x] Two different options for Embed 
- [x] Tooltips to help users differentiate between two embed options

### CODE REVIEW

**Comment by lbanner** [comment]
Nice :+1:

**Comment by GaryKriebel** [comment]
@revanthkolli ... what do you mean by "Style"?
screen shot 2015-06-30 at 12 00 31 pm

**Comment by revanthkolli** [comment]
@GaryKriebel I had that there to differentiate between the code that should be put in the body and the css style link that should be put in <head></head>.

**Comment by revanthkolli** [comment]
@sloria Ready for review/feedback

**Comment by lbanner** [comment]
Nice @revanthkolli .... @lyndsysimon, how a out 1st pass on this one? Thanks.

**Comment by GaryKriebel** [comment]
I like the updated definition:
screen shot 2015-06-30 at 4 16 17 pm

**Comment by lyndsysimon** [comment]
I don't think we should be requiring the user to copy/paste multiple code blocks - one should be fine. CSS can be linked anywhere in the document, as well, so these can probably just be concatenated together.

**Comment by lyndsysimon** [comment]
The above said - is there a reason this couldn't be accomplished with an iframe and an associated endpoint?

For instance, this could be the code the user should paste into their site:

```html
<iframe src="https://osf.io/abcde/embedded/" width="100%" height="100%"></iframe>
```

The result would be the page at the URL directly rendered into their site. That endpoint on the OSF would need only to pass through the content returned from the MFR endpoint - the content displayed on the external site would be the exact same code as is used to display it on the OSF.

Some improvements to the above might be made to handle cases where iframes are not allowed by providing a text link to the page on the OSF, but that needn't be looked at until the basic functionality works.

**Comment by hmoco** [comment]
@lbanner @lyndsysimon with this addition, and mine (#3724), should we be worried about button creep? There will be a crapton of buttons on file-view page, making it if the screen is smaller than full-size, it will get pretty close to needing 2 rows of buttons

**Comment by lbanner** [comment]
Hey @hmoco -- good insight, and yes we should worry about button creep. This was also noted by @nicipfeiffer and @erinmayhood today -- We are aiming to look at this in a more holistic fashion. Same time, I think, we'll not want this review to be an obstacle to improved functionality in the meantime.

**Pull request merged**
