### PR TITLE
[Feature Fix] IE template dropdown not shown 

### LINKED ISSUE #1504: [staging & production] [onboarder] Template dropdown does not display on IE
# Steps
1. Log into your account on IE
2. Go to the Dashboard and click *Create a project* on the onboarder
3. Enter a new title and try to template from another project

# Expected 
As the description suggests, you should be able to search within your own projects via the dropdown menu or search for public projects.

# Actual
There is some formatting error and no dropdown menu or search bar is displayed (there's just a blank line instead)
screen shot 2015-01-15 at 3 51 05 pm

### PR DESCRIPTION
**Pull request by haoyuchen1992**
# Purpose
The change will make template selection shown on IE when creating project on dashboard.  Resolve #1504 .

# Changes
The change is quit simple. It only replace id selector -`#createNodeTemplates` with class selector-`.select-template`.

#### Before-Change:
screen shot 2015-05-27 at 5 55 59 pm

#### After-Change:
screen shot 2015-05-27 at 5 54 48 pm

# Explanation
The change is very small, but the reason is very subtle. 

The selection bar is based on JQuery Library -[Select2](https://select2.github.io/). It needs to select input DOM and insert a new div DOM above that input DOM. In our case, input DOM is defined in mako template file with the ID -`#createNodeTemplates`. In IE, it will search unique ID starting from template. So it will insert the new DOM in template, which will not be shown. However, the other browsers will search unique ID from the shown HTML and consequently the inserted DOM will be shown. 

In order to getting ride of the side effect of using ID in template, the solution here is to replace a unique Id with a unique class. Therefore, it could be shown in all the browsers. 

# Side Effects
None. It only replaces the selector. And also the class name is new and unique, it will not influence others.

### CODE REVIEW

**Comment by caneruguz** [comment]
@haoyuchen1992 the class name is a bit general. Is there a reason you didn't use selector ```(".createNodeTemplates")```
Also is the reason for this documented elsewhere, i.e. on stackoverflow or as an issue for select2?

**Comment by haoyuchen1992** [comment]
@caneruguz  Originally, I was afraid that the existing ID has also been used in other setting. I just searched the ID name in the project folder. It is only used for this dropdown menu. Yes, it's better to change the class name as the original ID name.

**Comment by caneruguz** [comment]
@Saman this looks good to merge.

**Comment by sloria** [comment]
Any sort of special-casing like this should be accompanied by a code comment explaining why it is necessary. @haoyuchen1992 Can you add this?

**Comment by haoyuchen1992** [comment]
@sloria It's hard to explain in short word. Can I add the url of pull request to the comment? For example"

    // IE won't select template with id correctly. so we replace #createNodeTemplates with .createNodeTemplates
    // More explanation -- https://github.com/CenterForOpenScience/osf.io/pull/2858
    $('.createNodeTemplates').select2({
        allowClear: true,
        placeholder: 'Select a project to use as a template',
        query: self.query
    });

**Comment by sloria** [comment]
@haoyuchen1992 That is fine.

**Pull request merged**
