### PR TITLE
[Ready for review] Add smart folder for watched projects.

### PR DESCRIPTION
**Pull request by MPNussbaum**
# Purpose
Resolves issue #710.

Add smart folder on user dashboard to show all projects watched.

# Changes.
Modify website/util/rubeus.py, website/view.py, and website/settings/defaults.py to support listing watched smart folder. 

# Side effects.
None that I can think of.

### CODE REVIEW

**Comment by lbanner** [comment]
@MPNussbaum -- was this in response to an OSF GitHub issue?

**Comment by MPNussbaum** [comment]
@lbanner -- yes, it resolves issue #710.

**Comment by lyndsysimon** [comment]
Tested, works - ready for you, @sloria.

**Comment by sloria** [comment]
Would be good to have a views test for this added functionality. Once that is added, this is good to merge.

**Comment by sloria** [comment]
The Travis build is failing. @MPNussbaum Can you look into this?

**Comment by sloria** [comment]
The dashboard is currently undergoing significant design changes. Closing this for now.

**Pull request closed without merging**
