### PR TITLE
[Ready for Review] api read only fields test modification

### LINKED ISSUE #4086: API Validator not complaining if you try to update a read-only field
Steps
-------
1. Enable all asserts for tests/api_tests/nodes/test_views/test_writing_to_public_field
2. Run the test

Expected
------------
Tests would pass

Actual
--------
The assertion that you would get a 403 when trying to update the public field, which is currently read-only, passes with a 200.

### PR DESCRIPTION
**Pull request by billyhunt**
Fixes #4086

Purpose
-------

Currently api_tests/nodes/test_views/test_writing_to_public_field has a commented out status code assertion.  That assertion is no longer needed as it is a feature of the django rest framework.

Also, in the same test, changes "public_field" (the mongo field) to "public" (the django rest framework field) 

Changes
------------

Remove commented out line 573 and 574 of test_views
change "public_field" to "public" twice in the test.

### CODE REVIEW

**Comment by HarryRybacki** [comment]
[#OSF-4190](https://openscience.atlassian.net/browse/OSF-4190)

Jira ticket was closed -- pinged @lbanner for clarification on whether this PR should also be closed or not.

**Comment by lbanner** [comment]
This PR is still open and tied to this issue ticket in JIRA: https://openscience.atlassian.net/browse/OSF-4127

[#OSF-4127]

Thanks @HarryRybacki

**Comment by samchrisinger** [comment]
@lbanner I've pulled the parts of this PR relevant to https://openscience.atlassian.net/browse/OSF-4127 into a new PR (https://github.com/CenterForOpenScience/osf.io/pull/4237). 

Not sure what the scope or status of the rest of this PR is.

**Comment by billyhunt** [comment]
Updated to new PR #4239

**Comment by lbanner** [comment]
Cool -- Thanks @billyhunt and @samchrisinger

**Pull request closed without merging**
