### PR TITLE
[feature] Notify contributors when added to a component whose parent project is private

### PR DESCRIPTION
**Pull request by samanehsan**
Continuation of https://github.com/CenterForOpenScience/osf.io/pull/3385

Purpose
----------
If a project has a component with a sub-component, and a user is added to both the top-level project and the sub-component but not the component, the user would only receive one email about being added to the project. However, when viewing the project page, they will just see a private component and may not realize that they were also added to a sub-component in that private component.

Changes
------------
Notify contributors if they have been added to a component if the parent project is private. So in the example above, the user would receive two emails: one for the top-level project and another for the sub-component.

### CODE REVIEW

**Comment by sloria** [comment]
Discussed in person: conditionally sending the `contibutor_added` signal might not be the best approach. Signals are meant to be "fire-and-forget"; they shouldn't know about their listeners' needs (e.g. preventing too many emails from being sent).

I believe it would make more sense to move the check in the listener function.

**Comment by sloria** [comment]
Also, when you make the above change, can you add a comment about why the check is necessary? This seems like one of those things that we'd easily forget the reasoning for. =)

**Comment by sloria** [comment]
Pass finished. :mahjong:

**Comment by samanehsan** [comment]
Done making that change @sloria! :whale:

**Pull request merged**
