### PR TITLE
[Ready to Review] Fix profile urls per Issue #4457

### PR DESCRIPTION
**Pull request by TomBaxter**
Purpose
The purpose of this change is to fix three URLs in /osf.io/framework/auth/core.py .

I do not yet have a full setup for testing. I was able to verify that the URLs requested in issue #4457 are correct.

### CODE REVIEW

**Comment by GaryKriebel** [comment]
Tom,
Thanks for the PR.  We will get this into our code review cycle and they will let you know of any updates that might need to be made.

**Comment by chennan47** [comment]
CR1 done. Looks good.

**Comment by abought** [comment]
CR2 complete. Good catch on the Github and Scholar links!

That said, I'm having trouble getting the new LinkedIn link to work:  http://linkedin.com/in/abought works, but http://linkedin.com/abought does not

There seem to be a few link formats/ allowed identifiers that LinkedIn allows. @GaryKriebel , can you lend some clarity on which link format we should use? We should probably update the profile page UI to match.

Note for testers/ QA: the broken URLs are used in the search page, and control the links that appear in search results when you search for a given user. (see screenshot below) In some cases you may need to run `inv rebuild_search` to make the new values appear when running locally.

screen shot 2015-10-26 at 10 46 32 am

**Comment by TomBaxter** [comment]
I should have looked a little deeper before creating the PR. I assumed
there would only be one form of identifier for user profile. Now that I
look at the OSF -> settings -> profile info -> social I see that at least
three forms are allowed...

in/userID, profile/view?id=profileID, or pub/pubID

... I'm not sure if these options represent different profile options
in LinkedIN or if all three formats are valid for all users. If all
are valid for all then perhaps limiting the users to one format will
clear up the confusion.

  The OSF user that opened the ticket specified that his link went to...

https://www.linkedin.com/*profile/view?id=pub*/taylor-salo/a7/3b7/323

  and that he expected...

https://www.linkedin.com/*pub*/taylor-salo/a7/3b7/323

    I was able to verify that his expected link worked and updated the
code accordingly. If we wish or if it is required to allow all three
forms of profile identification then a more elaborate fix will be
required.

-Tom Baxter


On Mon, Oct 26, 2015 at 11:10 AM, Andy Boughton <notifications@github.com>
wrote:

> CR2 complete. Good catch on the Github and Scholar links!
>
> That said, I'm having trouble getting the new LinkedIn link to work:
> http://linkedin.com/in/abought works, but http://linkedin.com/abought
> does not
>
> There seem to be a few link formats/ allowed identifiers that LinkedIn
> allows. @GaryKriebel <https://github.com/GaryKriebel> , can you lend some
> clarity on which link format we should use? We should probably update the
> profile page UI to match.
>
> Note for testers/ QA: the broken URLs are used in the search page, and
> control the links that appear in search results when you search for a given
> user. (see screenshot below) In some cases you may need to run inv
> rebuild_search to make the new values appear when running locally.
>
> [image: screen shot 2015-10-26 at 10 46 32 am]
> <https://cloud.githubusercontent.com/assets/2957073/10732415/4c05adc8-7bd0-11e5-960c-c9270386b5d8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/pull/4472#issuecomment-151168589>
> .
>



-- 
....... ___o
........\<,\
..... ()/() \o

**Comment by TomBaxter** [comment]
This post seems to indicate that there are at least two valid profile syntaxes
https://help.linkedin.com/app/answers/detail/a_id/49315
Also it appears that users can customize there public profile URL
https://help.linkedin.com/app/answers/detail/a_id/87/ft/eng

**Comment by TomBaxter** [comment]
I have a dev environment set up now and was able to test. The pub/pubID format definitely works and I expect the other two formats would work as well, though after a little searching I was unable to find an example of the other two formats. I looked through about 20 linkedin profiles and they all had the pub/pubID format. Do we have any examples of the other two formats I could test with?

**Comment by abought** [comment]
> I have a dev environment set up now and was able to test. The pub/pubID format definitely works and I expect the other two formats would work as well, though after a little searching I was unable to find an example of the other two formats. I looked through about 20 linkedin profiles and they all had the pub/pubID format. Do we have any examples of the other two formats I could test with?

Thanks for the followup! http://linkedin.com/in/abought works for me as an example of the alternate format.

But I agree that for the user, it's confusing to have to include the link prefix for your chosen format; I'd expect I could just type in my ID and the rest would be taken care of. Standardizing on one option would make it much easier to create links that reliably work. 

I'll defer to Gary for the decision on that (both implementation, and whether that's in scope for this PR).

**Comment by GaryKriebel** [comment]
Actually, we should allow for all of the instances as we have a number of users using each kind of LinkedIn profile URL currently on the OSF.

**Comment by TomBaxter** [comment]
In that case I believe this PR is ready for further review.

**Comment by GaryKriebel** [comment]
Thanks, Tom.  I'll move it along for merging and QA review.

**Pull request merged**
