### PR TITLE
Add Pointer Class Cursor to View Files Page

### LINKED ISSUE #3734: [staging & production] file tree collapse icon needs pointer class
#### Steps
- View a file on the OSF
- Collapse the file tree, notice that when you do so your cursor changes.
- Expand the file tree, notice that your cursor does not change.

[Gyazo](http://gyazo.com/84ac2124a8d38b76555994298ebdf35e)

#### Expected
- When expanding the file tree, the cursor should change the same way it does when collapsing the file tree.

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h1> Purpose </h1>
Make view files cursors consistent for opening and closing tab. Close #3734.
<h1> Changes </h1>
Simple html.
<h1> Side Effects </h1> 
None.

### CODE REVIEW

**Comment by sloria** [comment]
I am not able to reproduce the original issue on develop. Are you sure this change is necessary?

**Comment by Johnetordoff** [comment]
@sloria I appear to be up to date, but It's probably some weirdness on my end.

**Comment by Johnetordoff** [comment]
@sloria I think I'm up to date, I did you read the issue carefully because the tab closes with the pointer, but doesn't open with it, so you could easily miss that.

**Comment by sloria** [comment]
Yes, I verified that the pointer is correct for both the collapsed and expanded states:

wiki2

**Comment by sloria** [comment]
Ah, I was looking at the Wiki page, not the View file page. I see. Disregard previous comment.

**Pull request merged**
