### PR TITLE
[HotFix] User Unclaimed Record Key Error `expires` [#OSF-7088]

### PR DESCRIPTION
**Pull request by cslzchen**
## Purpose

HotFix, please refer to the ticket.

## Changes

If `expires` is not in user's unclaimed record, only check `token`.

## Side effects

No

## Ticket

https://openscience.atlassian.net/browse/OSF-7088

### CODE REVIEW

**Comment by brianjgeiger** [comment]
This should be good once the merge conflict is fixed.

**Comment by cslzchen** [comment]
https://github.com/CenterForOpenScience/osf.io/commit/69ea4bf6309b6e2e96785fce6bb6237a6f6d55b4 fixed this issue and added a test as well. This PR (after fix merge conflict) improves the code and add one more test.

**Comment by brianjgeiger** [comment]
With https://github.com/CenterForOpenScience/osf.io/commit/69ea4bf6309b6e2e96785fce6bb6237a6f6d55b4 does this still need to be a hotfix or could I just put it through the improvements process?

**Comment by cslzchen** [comment]
Agreed. I will close the ticket and pr. This change can be added along with https://openscience.atlassian.net/browse/OSF-6998.

**Pull request closed without merging**
