### PR TITLE
Make User API Endpoint use Underscores/lowercase keys [OSF-6537]

### PR DESCRIPTION
**Pull request by mluke93**
## Purpose

API V2 keys were not correctly cased to be processed by ember-osf.

## Changes

All "Social" keys changed to underscores or all lowercase, instead of camelCasing.

## Side effects

Should be no side effects.

## Ticket

https://openscience.atlassian.net/browse/OSF-6537

### CODE REVIEW

**Comment by brianjgeiger** [comment]
Good for now. The fields are dev only, so no compatibility issues. 🎉 🐧 🎉

**Comment by brianjgeiger** [comment]
Nope, no penguin party. Tests are failing. https://travis-ci.org/CenterForOpenScience/osf.io/jobs/139571991

**Comment by sloria** [comment]
@mluke93 There are still three tests failing. Could you look into those please?

**Comment by mluke93** [comment]
I have been. I told Brian that I was having some trouble and it would take
a little time. I do believe its about done and Ill have another version up
soon.

**Comment by sloria** [comment]
No worries. Thanks!

**Comment by brianjgeiger** [comment]
Looks like there are merge conflicts if you haven't seen that yet. (There's nothing more fun to deal with than a merge conflict)

**Comment by mluke93** [comment]
Yeah... working on that.

**Comment by mluke93** [comment]
Ignore this. Something went wrong. I'm sorry!

**Pull request merged**
