### PR TITLE
[Hotfix] Transact shell

### PR DESCRIPTION
**Pull request by chrisseto**
Makes it harder to destroy your database... or prod's database. *cough*

Second commit contains fixes for https://github.com/CenterForOpenScience/modular-odm/pull/125

### CODE REVIEW

**Comment by sloria** [comment]
@chrisseto Can this be merged without the modm update, or do they need to go in together?

**Comment by chrisseto** [comment]
@sloria The second commit requires the modm update. Want me to split it into a separate PR?

**Comment by sloria** [comment]
Or you could modify the tests to conditionally add the remove_all argument.

**Comment by chrisseto** [comment]
Moved second commit to https://github.com/CenterForOpenScience/osf.io/pull/4538

**Pull request merged**
