### PR TITLE
[ENG-2382] Change registration-actions type to review actions

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

This will make the types correct for ember

## Changes

- simple change to type string

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify the type for registration actions is `review-actions`

## Documentation

🐞 fix, no docs

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-2382

### CODE REVIEW

**Comment by brianjgeiger** [comment]
This is still marked as a draft.

**Comment by brianjgeiger** [comment]
Sorry, I thought this was put in review. Ignore me.

**Comment by Johnetordoff** [comment]
@brianjgeiger yeah should be g2g just being super safe and waiting to for Travis

**Review by brianjgeiger — APPROVED** [review]

**Comment by jwalz** [comment]
drive-by: I think this should also update the `actions_payload_base` in `api_tests/registries_moderation/test_submissions.py`

**Pull request merged**
