### PR TITLE
Update base-page.js

### PR DESCRIPTION
**Pull request by dromero23**
User's password is validated in real time when the users start typing in his/her password.

### CODE REVIEW

**Comment by sloria** [comment]
Thanks for the contribution, @dromero23 . This looks to be a work in progress. Is your plan to validate the length of the input as the user types?

**Comment by dromero23** [comment]
Yes that is the idea, however I am not really familiar with html, so you
may not be able to see the update on the website since I was not able to
find the right .mako file

On Sat, Feb 28, 2015 at 5:45 PM, Steven Loria <notifications@github.com>
wrote:

> Thanks for the contribution, @dromero23 <https://github.com/dromero23> .
> This looks to be a work in progress. Is your plan to validate the length of
> the input as the user types?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/pull/1991#issuecomment-76557454>
> .
>



-- 
Daniel Romero
IT- IEEE UH Branch
B.S. Computer Engineering 2015
Cullen College of Engineering
University of Houston

**Comment by sloria** [comment]
The mako file for the login page is here: https://github.com/CenterForOpenScience/osf.io/blob/ee6c055b57487e388b921d4d158dff87cc5f6ea5/website/templates/public/login.mako

We also have a registration form in `website/templates/index.mako`.

**Comment by sloria** [comment]
Closing this for now until this feature gets picked up again.

**Pull request closed without merging**
