### PR TITLE
[hotfix]Hotfix/issue2460

### PR DESCRIPTION
**Pull request by brandonPurvis**
## Purpose
Currently, when adding a contributor to a project, searching for a name with special characters such as accents yields no results, and logs an error in the console. This PR resolves this issue causing searches to return the relevant users.  

Closes Issue https://github.com/CenterForOpenScience/osf.io/issues/2460(https://github.com/CenterForOpenScience/osf.io/issues/2460)

## Changes
Given a query with special characters, normalizes each word in that query converting all characters to ascii prior to passing the query to elasticsearch.

### CODE REVIEW

**Comment by lbanner** [comment]
:+1: Nice!

**Comment by lbanner** [comment]
@brandonPurvis ..... Why a 'Hotfix?' ... going to ask @sloria can / should this be a 'Hotfix?' -- other option is we commit to 'develop' and fold it into a release, which likley is the better approach.

**Comment by sloria** [comment]
Yep, let's make this a feature rather than a hotfix, as it's not a critical fix.

**Comment by lbanner** [comment]
Cool. @brandonPurvis can you remake this as a request to merge with 'develop' and remove the "[Hotfix]" designation? Thanks.

**Comment by chennan47** [comment]
@brandonPurvis also the travis build fails on flake 8. Fix that pls.

**Comment by chennan47** [comment]
@brandonPurvis pls close this pr since you already submit a new one.

**Pull request closed without merging**
