### PR TITLE
Fix external sites opening in new tabs [#OSF-6426]

### PR DESCRIPTION
**Pull request by erinspace**
## Purpose
- External links from the profile page, OSF for meetings pages, or forward widgets open tabs in a new window, which could lead to some undesirable effects (see tickets for more detail)

## Changes

- Remove "_blank" target from link in forward widget on configured projects
- Remove "_blank" target from log link for changed forward URL
- Remove "_blank" target from link in external websites in the user profile
- Remove "_blank" target from external conference website URL

## Side effects
- None anticipated

## Ticket
https://openscience.atlassian.net/browse/OSF-6426

### CODE REVIEW

**Comment by mfraezz** [comment]
Manual testing indicated that putting `rel="noreferrer"` in the anchor tags instead of removing `target="_blank"` might be a better solution -- it effectively strips `window.opener` from the new tab without removing desired functionality. Given that we're not using `window.opener` anywhere, this shouldn't cause any issues.

**Comment by brianjgeiger** [comment]
I think @billyhunt  checked with @saradbowman, and I believe everyone was okay with losing that functionality in these instances. I'm good with the solution as implemented unless anyone objects.

**Comment by brianjgeiger** [comment]
Unless this solution is less secure, but I don't believe it is.

**Comment by erinspace** [comment]
As I understood it, it also wasn't losing functionality so much as providing a clearer UI by not using a new tab. Happy to change it to whatever though.

**Comment by mfraezz** [comment]
Sara confirmed, desired behavior is implemented. Dropping this in RTM 🀄

**Comment by sloria** [comment]
@erinspace The article you cite is referring specifically to opening new browser *windows* (not tabs), which is 100% terrible.

As far as opening external links in new *tabs*, that's up for debate:

- Point: http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/
- Counterpoint: http://www.aphoenix.ca/why-external-links-should-not-open-in-new-tabs-01/

I was actually surprised to find a Google Docs link that opened a new tab today:

2016_06_06_-_google_docs

I don't feel strongly either way, and I hate to be the one to open bikeshedding season. So unless Sara or Nici have objections, I think this is good to merge.

**Comment by erinspace** [comment]
I am OK with anything - just someone tell me which do to.

**Comment by sloria** [comment]
Ah, just saw Matt's comment. OK, looks like this is good to merge

**Pull request merged**
