### PR TITLE
[hotfix] fix for file render page download via view_only link

### LINKED ISSUE #1748: Apparent Divergence of View-Only Link File Downloads
This is a problem that a user found. 
1) Make a view-only link
2) Try to download files from "Files" tab
3) Try to download files from the individual file's page   

-------
We expect to be able to download files from both the "Files" tab and the individual file's page. 

We found that we could only download files from the "Files" tab, and that trying from the individual file's page leads to: 
screen shot 2015-02-10 at 9 23 40 am

### PR DESCRIPTION
**Pull request by icereval**
Purpose:
Corrects view only link file downloads not working.

Resolves #1748

Cause:
View Only file links are not downloading.

Side Effects:
None

### CODE REVIEW

**Comment by KatyCain526** [comment]
Do we have any idea when will this fix be live?

**Comment by lbanner** [comment]
@sloria @icereval  -- Can we make this a :fire: Fix?

**Comment by sloria** [comment]
@KatyCain526 I will deploy this now.
@lbanner This is already a hotfix.

**Comment by lbanner** [comment]
TY!

**Pull request merged**
