### PR TITLE
[API V2] Fix ListFilterMixin for serializer & boolean fields

### PR DESCRIPTION
**Pull request by samanehsan**
Purpose
------------
When filtering a list view by a boolean or serializer method field, if the field name differs from the source, it results in an Operation Failure `command SON([('rollbackTransaction', 1)]) failed: exception: no transaction exists to be rolled back`

Changes
------------
In `ListFilterMixin.get_filtered_queryset` pass the field_name to `convert_value` instead of the field source.

### CODE REVIEW

**Comment by samanehsan** [comment]
Just want to note that I'm not sure how to write a test for this since we are not currently filtering any lists by boolean or serializer method fields.

**Comment by sloria** [comment]
Looks good. CR1 done.

**Comment by abought** [comment]
CR2 done.

I don't have a clear test case in mind, so wasn't able to run this code to verify that the error would be fixed. Any guidance would certainly be helpful. (tried `nodes/filter[public]=` `true`, `false`, but that worked for me on both develop and this branch)

**Comment by sloria** [comment]
@samanehsan How did you encounter this bug? Is it manifesting itself anywhere in the current API?

**Comment by samanehsan** [comment]
@sloria, when writing API comment routes, I was trying to use `ListFilterMixin` to filter on the deleted field in the comment model. Since the source is `is_deleted` but the field name is `deleted`, when the source gets passed to `convert_value()` it breaks because it actually should be the field name.

**Comment by sloria** [comment]
Thanks for the clarification @samanehsan . Was just checking if there was regression test to be written. For now, this is good to merge.

**Pull request merged**
