### PR TITLE
Anon-view only links show names in prereg registration schemas [OSF-6526]

### PR DESCRIPTION
**Pull request by TomBaxter**
## Purpose:
[OSF-6526](https://openscience.atlassian.net/browse/OSF-6526)
Add facility for removing questions from anonymized VOL to registrations

## Changes:
Update  website/project/views/register.py add logic for removing questions from anon VOLs
Update website/settings/defaults.py add setting ANONYMIZED_TITLES list of titles to remove

## Side effects
Relies on list of titles being accurate and up to date.

[#OSF-6526]

### CODE REVIEW

**Comment by brianjgeiger** [comment]
Seems good. I wouldn't say no to some more descriptive iteration variables, since there are three levels of iteration with two variables each. Is it important what each item is?

**Comment by brianjgeiger** [comment]
Only two levels, sorry.

**Comment by TomBaxter** [comment]
Updated

**Comment by brianjgeiger** [comment]
🎉 🐧 🎉

**Pull request merged**
