### PR TITLE
adds browse new projects to navbar.

### LINKED ISSUE #3326: [Feature] Allow logged in users to access "Browse New Projects" from the navigation bar
Currently, only logged out users can see the "Browse New Projects" link in the top navigation bar. Either this should be added to the bar for logged in users as well, or a "Browse New" link in the "Explore" tab (possibly above the "Registry" link).

**Logged out**
screen shot 2015-06-25 at 10 32 18 am

**Logged in**
screen shot 2015-06-25 at 10 36 36 am

### PR DESCRIPTION
**Pull request by Johnetordoff**
**Purpose**
Allow access to "Browse New Project" navbar link while logged in. Closes #3326.
**Changes**
Just adds html tag
**Side Effects**
None

### CODE REVIEW

**Comment by lbanner** [comment]
@Johnetordoff -- can you note in your description the GH Issue# to which this refers / answers? Thanks!

**Comment by sloria** [comment]
The addition of the new link in the navbar breaks responsiveness at medium screen sizes:

osf___dashboard

I'm wondering if "New Projects" belongs in the "Explore" dropdown (for both logged-in and logged-out users). However, this diverges from the original design given to us. Thoughts, @lbanner @GaryKriebel ?

**Comment by lbanner** [comment]
I think I agree on that -- but it was an intentional choice by designer, I believe -- so might take some discussion to change.

**Comment by GaryKriebel** [comment]
Tough one.... I would have no problem with it under Explore... however,
having it by itself will get more attention from others than if it is
buried.

Can it be by itself not logged in and under Explore when logged in?  Not
ideal... but ...

**Comment by jinluyuan** [comment]
I think renaming it "Public Activity" could help since that's the header title of the page, and it has fewer characters than "Browse New Projects". The page has "new" as well as "popular" projects (registrations too), so "New Projects" is a bit of a misnomer.

**Comment by Johnetordoff** [comment]
@sloria, is this good to go? I addressed the size issue.

**Comment by sloria** [comment]
I'm not sure that renaming to "Browse" is the best solution--it is a bit ambiguous. I still believe that putting the link under "Explore" is a good idea, and +1 to renaming it to "Public Activity" as Jinlu suggested.

But as @lbanner pointed out, this diverges from the design given to us--maybe need to include this in our feedback to the designers? How should we move forward, @lbanner @GaryKriebel ?

**Comment by AndrewSallans** [comment]
How about the following? 

Rename "Explore" to "Browse" and add "New Projects" under that drop-down.  Make unauthenticated and authenticated the same.  

I think browse suggests a relationship with content more than explore, which I might expect to take me to a getting started type page showing features.  Public activity seems too nuanced to me for somebody who just arrived at the OSF for the first time.

**Comment by jinluyuan** [comment]
I like Andrew's idea. We could also add a "Popular Projects" link under "Browse" that anchors to the Popular Projects section of the page, just so users don't have to go through two clicks for it.

**Comment by Johnetordoff** [comment]
Reading these ideas, clearly everyone has a subtly different opinions about how this should look, none of these ideas are bad, but I clearly can't implement all of them. I think we should deffer to the style guide as much as possible, so if you can definitive say this idea is better because more in accordance with the guide, I think that's a more constructive way to form a consensus.

**Comment by jlcohoon** [comment]
+1 to @AndrewSallans's idea

**Comment by sloria** [comment]
OK, any barriers to implementing @AndrewSallan's idea, @lbanner @GaryKriebel  ? Do we need to wait for feedback from the design firm or can we move forward with this?

**Comment by AndrewSallans** [comment]
I don't believe we are seeking feedback from the design firm on this.

**Comment by GaryKriebel** [comment]
If community is fine with the change (and they came up with it), then I am.  They should be aware that any screenshots they use for other purposes will need to be updated again.

**Comment by lbanner** [comment]
:+1:

**Comment by Johnetordoff** [comment]
@sloria This good to go?

**Comment by sloria** [comment]
Merged into Develop. Changed the order so that "New Projects" was first.

**Pull request closed without merging**
