### PR TITLE
[WIP] Update file JSON responses to match JSONAPI 1.0 spec

### PR DESCRIPTION
**Pull request by pattisdr**
<h1> Purpose </h1>

References Issue #3074.   API v2 should be formatting JSON responses to adhere to the JSONAPI v1 specification http://jsonapi.org/.  The JSONAPI v1 spec was released 5-29-15.  This PR modifies the <b> files </b> response to match the new spec.  Other responses will be formatted in subsequent PR's.

<h1> Changes </h1>
Condenses file properties into an attributes field and formats links. Modifies tests to handle new response formatting.

New formatting:
screen shot 2015-07-17 at 11 28 32 am

Old formatting: 
screen shot 2015-07-17 at 11 30 15 am

<h1> Side Effects </h1>
API is now returning files with different formatting.

<h1> TODO </h1>
- [ ] Make sure formatting is correct
- [x] Resource objects must have an id and type http://jsonapi.org/format/#document-resource-objects  I am returning the provider as an id?  What is best here?
- [x] What should pagination look like?  Can meta information ("total" and "per page") remain inside pagination links? http://jsonapi.org/format/#fetching-pagination

### CODE REVIEW

**Comment by brianjgeiger** [comment]
As near as I can tell, we aren't breaking any rules with the pagination, so we should be able to keep it with the meta.

**Comment by brianjgeiger** [comment]
For now, I think the id is the combination of the provider and the path. That may change independently of your PR.

**Comment by pattisdr** [comment]
If id is a mix of provider and path, should I still return both fields as attributes?

**Comment by brianjgeiger** [comment]
Yeah. Like I said, the id will likely change at some point, and we need the other items as their own things as well.

**Comment by pattisdr** [comment]
@jamiehand was asking about metadata formatting.  Right now, I have metadata nested inside attributes, which I think is fine since attributes are allowed complex data structures and the metadata are file properties. http://jsonapi.org/format/#document-resource-object-attributes  What are your thoughts on this @brianjgeiger ?  Another possibility is  metadata could be pulled out of attributes and nested under meta.

screen shot 2015-07-19 at 1 40 48 pm

**Comment by brianjgeiger** [comment]
I think inside attributes is fine.

**Comment by brianjgeiger** [comment]
Although, looking at it… we essentially did it this way because that's how water butler does it. I think it would be better to pull that information out to the main attribute level. size and modified etc would be at the same level as provider and path. Extra would still contain its own set of information.

Oh, and you might as well put osfstorage first in the ID rather than last.

**Comment by pattisdr** [comment]
Moved to #3683

**Pull request closed without merging**
