### PR TITLE
[feature] Set the button type of "Cancel" button in user settings

### PR DESCRIPTION
**Pull request by huangginny**
From CenterForOpenScience/osf#1183
Closes CenterForOpenScience/osf.io#1495

**Problem**
In user settings, change "Education" or "Employment." Clicking "return" does not save your changes, but pops up a modal asking you whether to discard your changes.

**Cause**:
The button type of "Cancel" is, by default, "submit." Therefore, it is triggered by the return key.

**Solution**:
Changed the button type of "Cancel" to "button"

**Side effect**:
None

### CODE REVIEW

**Comment by brianjgeiger** [comment]
I don't believe this is going to fix the social tab, however. Better would be to explicitly define the submit button for the form and to ensure that everything is set up as a proper form.

**Comment by huangginny** [comment]
@brianjgeiger I tried with firefox, and found out that this fix fixes the social tab too...
But I'll go ahead and define the "submit" button.

**Comment by brianjgeiger** [comment]
Cool. If you find that works, it would be better not to change the order of the buttons and just define the submit (and possibly the cancel if that's not working. I haven't tested cancel though).

**Comment by brianjgeiger** [comment]
Also, since the bug report was submitted with Safari and Chrome as the problem cases, it would be good to test those as well. You might have a quick discussion with @chrisseto who fixed a submit-related problem with search on IE to make sure it's going to work there.

**Comment by sloria** [comment]
+1 to @brianjgeiger's suggestion: Relying on the order of the buttons is brittle and breaks UI consistency.  @huangginny Can you experiment with using the `submit` bindng to fix this?

**Comment by chrisseto** [comment]
You could also change the button type? I think is the attribute. By default it is set to submit changing it to button on the cancel button should also fix this issue.

**Comment by chrisseto** [comment]
screen shot 2015-01-15 at 10 54 12

**Comment by huangginny** [comment]
@chrisseto Actually your suggestion is soooo helpful. I changed type to button and then did the trick!
@sloria I'll push again soon. Do you want me to change the order of the buttons back? Or you're okay with Submit before Cancel?

**Comment by sloria** [comment]
Fix looks good. :dart: Could you please resend this as a PR branched off of `release/0.23.0`?

**Comment by sloria** [comment]
@huangginny Scratch that. `develop` is still in sync with `release/0.23.0`, so I can safely merge this into both `develop` and `release/0.23.0`.

**Pull request merged**
