### PR TITLE
[hold] UnicodeEncodeError error in twitter disambiguation page

### PR DESCRIPTION
**Pull request by abought**
Possibly on hold pending #3576.

## Purpose
The new `redirect_to_twitter` disambiguation page (#3408 / #3453) fails when one of the usernames contains unicode. 

Example: I have registered two users on staging with the same twitter handle:
https://staging.osf.io/@occsci/

One of those users is named `Sam Pull string_with_unicode_(͡° ͜ʖ ͡°)`

The page returns "Unable to resolve" instead of a disambiguation page, and Sentry lists the following error:
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-31: ordinal not in range(128)`

## Summary of changes
This includes one proposed fix- simply marking the strings as unicode so that `string.format` inserts unicode data correctly. This works on my local machine.

I have minimal handson experience with unicode issues, so there may well be a more robust way. Feedback welcome. @HarryRybacki ?

## Side notes
The page returns "Unable to resolve" because the exception raised is not an http error message- it's an expected error message not handled by the normal error renderer. (This one? https://github.com/CenterForOpenScience/osf.io/blob/develop/framework/exceptions/__init__.py#L70 )

The error message could do more to make clear that a server error occurred. But that would be a separate issue.

### CODE REVIEW

**Comment by sloria** [comment]
This fix seems correct. Can you add a regression test?

**Comment by abought** [comment]
Pushed the requested regression test, plus cleaned up use of `web_url_for(expect_error)` [sic]. Will revisit once Travis CI builds recover.

**Comment by abought** [comment]
Force-restarted failing tests; passing now.

**Comment by sloria** [comment]
Closing this for now, since this feature is disabled for now, and we will likely remove the disambiguation page.

**Pull request closed without merging**
