### PR TITLE
[Feature] Add AsPredicted metaschema [OSF-5755]

### PR DESCRIPTION
**Pull request by Ghalko**
## Purpose

Add schema for specific registration, AsPredicted Preregistration.

## Changes

- Added a json file: `aspredicted.json`
- Added necessary info to `schemas.py`

## Side effects

Need to run `ensure_schemas` if not normally run in order to get the schema on the database.

Populates API and New Registrations Modal
screen shot 2016-06-16 at 10 22 00 am
screen shot 2016-06-17 at 11 25 46 am

All registration associated functionality should work as well.

## Ticket

https://openscience.atlassian.net/browse/OSF-5755

### CODE REVIEW

**Comment by brianjgeiger** [comment]
Well, that's simple enough. Could you update the screenshot to show the proper order? Also, are there any tests that can be added? 🐧

**Comment by brianjgeiger** [comment]
Also, please do a product demo for David and have him comment on the Jira ticket that it's all wonderful if it is.

**Comment by Ghalko** [comment]
New order picture done. The only tests I can find are in `test_metadata.py` which only has general tests. Should I make more precise tests that will have to be updated every time a schema is added?

**Comment by brianjgeiger** [comment]
If it seems like it will be useful. Think about the problems that could come from, for example, a badly formatted json schema or similar. Are we checking for that? I don't know if we need schema-specific things unless there's a new feature in the schema or something.

**Comment by brianjgeiger** [comment]
I'm still seeing the old picture in the PR description, btw.

**Comment by Ghalko** [comment]
Fine, I forgot to press the update button, the preview was just so convincing.

**Comment by sloria** [comment]
This is good to merge, pending David's feedback on the ticket about the typo in the description.

**Comment by sloria** [comment]
Got David's approval on FD to change the text.

**Comment by evomellor** [comment]
Thanks. I am confirming that the order for the above schema presentation is good. I edited comment on JIRA ticket to be consistent with the order above. https://openscience.atlassian.net/browse/OSF-5755

**Pull request merged**
