### PR TITLE
Feature/font awesome 4

### PR DESCRIPTION
**Pull request by kushG**
<h3> Purpose </h3>
Currently, OSF is having two versions of font-awesome of which the latest version is unused & older version is in use. This PR removes older version of font-awesome & uses new version i.e. font-awesome 4.3.

<h3> Changes </h3>
Most of the update involdes changing icon to fa & icon-* to fa fa-*

<h3> Side Effects </h3>

Some fonts may have been broken due to the fact that not all icons-* gets replaced with fa fa-* but there are a few exceptions as mentioned here https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4.

### CODE REVIEW

**Comment by sloria** [comment]
We prefer `npm` packages to `bower` packages, and there is a distrubution of FA on npm: https://www.npmjs.com/package/font-awesome . @kushG Can you see if you can get the npm package working?

**Comment by sloria** [comment]
We should be able to remove the include here: https://github.com/CenterForOpenScience/osf.io/blob/893d81ba33e8d5bd0f4c911943f026ca026ea713/website/templates/search.mako#L4

**Comment by sloria** [comment]
The +/- icon is not toggling when expanding/collapsing node list items.

issue

**Comment by sloria** [comment]
Icons in the wiki panels are missing

osf___all_addons_wiki

**Comment by lbanner** [comment]
Minor, maybe, but also on Wiki the MENU icon is a darker black then the grey found on staging.

**Comment by sloria** [comment]
@lbanner is correct. @kushG looks like the CSS rule for that icon needs to be updated.

**Pull request merged**
