### PR TITLE
Fixed error with tags not working with symbols and apostrophes

### PR DESCRIPTION
**Pull request by PatrickEGorman**
## Purpose
Allow for "?"," ' " and other symbols / special characters in project tags.
Closes issue https://github.com/CenterForOpenScience/osf.io/issues/2696

## Changes
Changed post request from storing tag in url to creating separate json formatted data value.

## Side Effects
Allows for any symbol I've tested.  I also checked to make sure javscript was escaped.  Since the symbols are unlimited, it might make potential for spam or other unwanted tagging conventions.  I would be interested in taking input on this issue.

### CODE REVIEW

**Comment by PatrickEGorman** [comment]
Looks like it failed some of the tests.  I will examine the tests and see what the problem might be

**Comment by PatrickEGorman** [comment]
Updated tests to fit new post format as well as making them test apostrophes and other special symbols

**Comment by PatrickEGorman** [comment]
Did thorough testing and should work now.  Will be online later to check.

**Comment by samanehsan** [comment]
Could you fix the logs to show apostrophes instead of the html?
screen shot 2015-06-02 at 4 32 33 pm

**Comment by PatrickEGorman** [comment]
Sounds good

**Comment by samanehsan** [comment]
@PatrickEGorman, if you commit to this branch and push your changes to github it will automatically update your pull request. No need to create a new one :smile:

**Comment by PatrickEGorman** [comment]
Even though it's from a deleted repository?  I messed up my develop branch really bad about a week ago so I needed to delete it and start again

**Comment by samanehsan** [comment]
Actually in this case you do need to create a new PR from a new branch-- l just noticed the deleted repository!

**Pull request closed without merging**
