### PR TITLE
[hold] Issue#1202 removed parent notf

### PR DESCRIPTION
**Pull request by Johnetordoff**
**Purpose**
closes Issue #1202 
**Changes**
 Creates a modal which allows mass contributor removal on child components on a component by component basis. Alerts user when they remove from single component only.
**Side Effects**
None that I know of.

image

Remove Button

screen shot 2015-06-08 at 4 44 43 pm

Select contribs page

screen shot 2015-06-08 at 4 45 00 pm

Select components page

### CODE REVIEW

**Comment by samanehsan** [comment]
Can you bring this up to date with develop? Thanks! :sunny:

**Comment by samanehsan** [comment]
Since this involves UI changes, can you include screenshots along with your PR description?

**Comment by Johnetordoff** [comment]
image

Remove Button

screen shot 2015-06-08 at 4 44 43 pm

Select contribs page

screen shot 2015-06-08 at 4 45 00 pm

Select components page

**Comment by lbanner** [comment]
@Johnetordoff @samanehsan ... this seems a bit beyond the scope of #1202, Yes?

**Comment by chennan47** [comment]
The redesign and update of sharing page is in this epic. Although not sure who is going to take that piece, @lbanner

**Comment by Johnetordoff** [comment]
@lbanner It is kind of out of scope, but figured if the redesign and update of sharing page is in this epic, then I might as make some more changes. Would should I talk to about the redesign? hopefully I can fold in some of these changes in to that.

**Comment by brianjgeiger** [comment]
I have Opinions on the UI in this, primarily stemming from how much I dislike the nested list of checkboxes. But small changes aren't going to fix this UI, so I would lean towards not trying to do piecemeal things with it.

**Comment by lbanner** [comment]
OK @Johnetordoff -- we are going to hold on this PR relatively briefly -- regroup on direction for the sharing page this Epic, and come back to it. Can checkin with @JeffSpies, but maybe we give you that project. Thanks.

**Pull request closed without merging**
