### PR TITLE
[WIP] Feature/addons error handling

### PR DESCRIPTION
**Pull request by samchrisinger**
## Purpose

For some addons when OAuth (or other creds) are revoked on the third party site uncaught errors were causing 500's on OSF. Also UI was not catching these errors and was providing no or poor user feedback.

## Changes

- Extends Mendeley and Zotero models to cache configured folder name. This allows for serializing the addon settings without making an API call.
- Add website/oauth/decorators.py and the api_call decorator. Also the citations addon provider now has an abstract property api_error_classes. Combined these are used to decorate and catch errors in potentially error throwing methods.
- Add front-end support for catching errors 

## Side effects

We should discuss the implications of saving the folder name. This now gets updated whenever the node config is saved, but may lead to staleness of the folder name.

### CODE REVIEW

**Comment by samchrisinger** [comment]
This PR only addresses a small portions of the addons that are affected by this issue. Rather than addressing this on a case-by-case basis it would be better to implement other addons using the new ExternalAccount/ExternalProvider patterns. @lyndsysimon no doubt has thoughts on this, and more discussion is definitely needed here.

**Comment by samchrisinger** [comment]
@GaryKriebel @lbanner ,
it may be worthwhile to consider this PR for upcoming releases. Some work remains to be done here, but work done by @kushG and @harrismendell might help fill in some of our gaps.

**Comment by lbanner** [comment]
OK @samchrisinger  --  is that previous work by @kushG and @harrismendell, or are you suggesting they could jump in here to help with remaining work? Thanks.

**Comment by samchrisinger** [comment]
This will be some extra work for both of them, but both have recently implemented some of the new addon patterns using ExternalProvider/ExternalAccount. 

The most important piece here is the addition of the the api_call decorator for handing errors on the server. This allows us to handle errors from 3rd party services in a relatively generic way. 

For Kushagra and Harris this would mean:
- adding an ```api_error_classes``` property to their subclasses of ExternalProvider
- decorating classmethods of that subclass that make API calls with the api_call decorator 

We'd need to coordinate with Steve too to get a subset of this PR merged into develop sooner rather than later.

**Comment by harrismendell** [comment]
I can look into this tomorrow for sure.

-Harris

**Comment by sloria** [comment]
After discussing with @samchrisinger , closing this for now.

**Pull request closed without merging**
