### PR TITLE
Prevent changing attached DraftRegistration file [OSF-5585]

### PR DESCRIPTION
**Pull request by atelic**
## Purpose

Prevent users from changing an attached file when prereg form is in progress. 
## Changes
- Any file attached to a DraftReg becomes "checked-out" when the preregistration form is submitted.
- The files become "checked-in" when the registration is approved or sent back as rejected.
- If the user tries to check-in an attached file before the DraftReg is approved, they receive a warning that this action will cancel their submission. If they continue, any DraftReg with that file attached will be rejected and all files attached to it become checked-in.
## Side effects
- Expose /reject/ route on front end. I don't like this so I'd like suggestions on the best way to handle it. 
- Checking in an attached file can do a lot if the user doesn't read the warning. 
## Ticket

https://openscience.atlassian.net/browse/OSF-5585
Depends on #5280

### CODE REVIEW

**Comment by whit537** [comment]
##### Investigations—for @whit537

**Comment by whit537** [comment]
##### Punchlist—for @barbour-em

**Comment by whit537** [comment]
(Reposting from Jira since I'm not sure which channel is best ...)

> users are experiencing registration failure when they change a file attached to a preregistration form while the registration is under review (in progress).

@barbour-em Could I get steps/expected/actual for this? I'm trying to reproduce the original bug so I can verify that this PR fixes the bug. Thanks! :-)

**Comment by whit537** [comment]
Here's where I'm at so far:

1. create a new project
1. add a file ({{foo.txt}}, contents `Cheese!`)
1. Registrations > [ New registration ] > open-ended [ Create draft ] > "blah text" [ Preview for submission ]

**Comment by barbour-em** [comment]
What I was able to do:

1. Create project
2. Add a file `foo.txt`
3. Registration > New Registration > **Prereg Challenge** > Attach `foo.txt` to at least one question that allows file attachments (e.g. Design Plan->Study Design)
4. Complete Prereg Registration > Preview for submission > Submit for review
5. Edit `foo.txt` while the registration is pending approval
6. Approve registration via admin interface

**Comment by whit537** [comment]
> **Prereg Challenge**

Gotcha ... lessee ...

**Comment by whit537** [comment]
Eternal spinner on a file upload widget, investigating ...

screen shot 2016-04-15 at 1 18 05 pm

**Comment by barbour-em** [comment]
Have you pulled from dev since #5280 was merged?
https://github.com/CenterForOpenScience/osf.io/blob/e731c4c1598f2118195528f8b818bd99dfc7dcad/website/static/js/registrationEditorExtensions.js#L170

**Comment by whit537** [comment]
No! Good idea. :-)

**Comment by whit537** [comment]
Hrm ... but I'm actually on `develop`. That's maybe what you meant, though, ya?

**Comment by barbour-em** [comment]
Oops, yes that is what I meant

**Comment by barbour-em** [comment]
Travis failures seem odd; all the tests pass locally. The log also includes this gem:

> ERROR: Failure: MultipleResultsFound (Query for find_one must return exactly one result; returned 1)

**Comment by whit537** [comment]
Alright, I'm able to reproduce the bug on `develop` at 643bb27.

screen shot 2016-04-18 at 10 12 02 am

Oh wait ... looks like it's actually a perms error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__ 
    response = self.get_response(request)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/whit537/workbench/cos/osf.io/admin/pre_reg/views.py", line 123, in approve_draft
    draft.approve(user)
  File "/Users/whit537/workbench/cos/osf.io/website/project/model.py", line 4681, in approve
    self.approval.approve(user)
  File "/Users/whit537/workbench/cos/osf.io/website/project/model.py", line 4476, in approve
    raise PermissionsError("This user does not have permission to approve this draft.")
PermissionsError: This user does not have permission to approve this draft.
```

I did go through [the prereg instructions](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#prereg) ...

**Comment by whit537** [comment]
[Looks like](https://github.com/CenterForOpenScience/osf.io/blob/643bb2781378beee830d34bff2588cfe38a4c924/website/project/model.py#L4475) there's a setting for this, which is `prereg_admin` [by default](https://github.com/CenterForOpenScience/osf.io/blob/643bb2781378beee830d34bff2588cfe38a4c924/website/settings/defaults.py#L442). The [docs](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#prereg) specify `prereg_group` instead.

**Comment by whit537** [comment]
I added an empty `prereg_admin` group and added my admin user to that group. I still get the same permissions error. Interestingly, `system_tags` is empty:

```
(Pdb) l
4471                    'TODO: add a generic email template for registration approvals'
4472                )
4473    
4474        def approve(self, user):
4475            import pdb; pdb.set_trace()
4476 ->         if settings.PREREG_ADMIN_TAG not in user.system_tags:
4477                raise PermissionsError("This user does not have permission to approve this draft.")
4478            self.state = Sanction.APPROVED
4479            self._on_complete(user)
4480    
4481        def reject(self, user):
(Pdb) user
<User(u'foo@example.com') with id u'ahn93'>
(Pdb) user.system_tags
[]
(Pdb) 
```

**Comment by whit537** [comment]
> Approve registration via admin interface

@barbour-em What are the steps to do this? I've tried following [these docs](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#prereg) and am hitting the permissions error described above.

**Comment by barbour-em** [comment]
@whit537 Interestingly I'm having the permissions problem now too, I could approve before. I guess for now you could do
(in `inv shell`)
```
In[1]: from website.settings import PREREG_ADMIN_TAG
In[2]: user = models.User.load('ahn93')
In[3]: user.system_tags.append(PREREG_ADMIN_TAG)
In[4]: user.save()
Out[4]: {'system_tags'}
In[5]: commit()
Transaction committed.
New transaction opened
```

This fixed the issue for me

**Comment by whit537** [comment]
Alright, I've manually added `PREREG_ADMIN_TAG` to my `user.system_tags`. However, I'm not able to produce a failure from [Step 6: Approve registration via admin interface](https://github.com/CenterForOpenScience/osf.io/pull/5464#issuecomment-210551106). I'm going to try again, maybe I missed or messed up a step or something ...

screen shot 2016-04-18 at 2 44 29 pm

**Comment by whit537** [comment]
##### Steps

1. Start with `develop` at 643bb27 
  1. Reset Mongo for osf.io.
  1. Reset SQLite for admin.
1. Create a new osf.io account.
1. [Create](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#how-to-run-the-admin-interface) a new admin account.
 1. [Configure for prereg work, part 1](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#prereg)
 1. [Configure for prereg work, part 2](https://github.com/CenterForOpenScience/osf.io/pull/5464#issuecomment-211408126)
1. Create a project.
1. Add a `foo.txt` file.
1. Registrations > New registration > Prereg Challenge
 1. `asdf` for all required textareas
 1. ...

**Comment by whit537** [comment]
I'm back at https://github.com/CenterForOpenScience/osf.io/pull/5464#issuecomment-210552553 for all eight file widgets on the prereg form.

**Comment by whit537** [comment]
Hrm ... "Save as Draft" and then "Edit" seems to reset the file upload widgets to a working state ... until the fifth one, which is Design Plan > Study Design. After failing to load that widget on the page, I go back to the four previous file upload widgets and they're all now broken.

If I navigate to "Design Plan" and reload the page, the 5th file upload widget works.

**Comment by whit537** [comment]
If I navigate to "Variables" (the previous pseudo-page) and back, the 5th file upload widget is broken again.

**Comment by whit537** [comment]
Alright, whatever. This is all on `develop`, so out of scope here. Just trying to figure out how to work around this bug so I can test here ...

**Comment by whit537** [comment]
##### Steps

1. Start with `develop` at 643bb27 
  1. Reset Mongo for osf.io.
  1. Reset SQLite for admin.
1. Create a new osf.io account.
1. [Create](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#how-to-run-the-admin-interface) a new admin account.
 1. [Configure for prereg work (part 1)](https://github.com/CenterForOpenScience/osf.io/tree/643bb2781378beee830d34bff2588cfe38a4c924/admin#prereg).
 1. [Configure for prereg work (part 2)](https://github.com/CenterForOpenScience/osf.io/pull/5464#issuecomment-211408126).
1. Create a project.
1. Add a `foo.txt` file, contents `Cheese!\n` (8 bytes).
1. Registrations > New registration > Prereg Challenge
 1. Enter `asdf` for all required textareas.
 1. Use [workaround](https://github.com/CenterForOpenScience/osf.io/pull/5464#issuecomment-211542666) to select `foo.txt` for Design Plan > Study design. 
screen shot 2016-04-18 at 3 35 48 pm
 1. Preview for submission.
 1. Submit for review.
 1. "Make registration public immediately"
1. Check admin, prereg is "Pending Approval": screen shot 2016-04-18 at 3 39 41 pm
1. Clicking "Approve" at this point should result in green "Approved". But ... !
1. Files > OSF Storage > Upload > `foo.txt`, contents `Bread!\n` (7 bytes):  screen shot 2016-04-18 at 3 43 12 pm screen shot 2016-04-18 at 3 43 30 pm
1. Back to admin ...
1. Approve > Approve: screen shot 2016-04-18 at 3 45 41 pm

##### Expected

Failure to approve. A 500? A red "Failed" status?

#####

Approved.

screen shot 2016-04-18 at 3 46 17 pm

**Comment by barbour-em** [comment]
@whit537 These are the steps that I have used before to cause this issue, I re-ran them this morning with the same results as you. It should have given a 500. Checking the database the registration seems to point to the updated file. 

Maybe the bug was fixed elsewhere? Or the error was a result of something else that has been fixed between now and when I started work on this?

Either way, I'm not sure what to do with this PR if we can't reproduce. What are your thoughts?

**Comment by whit537** [comment]
@barbour-em I would say spend up to an hour tracking down *why* the issue is resolved. If we can't answer the question in a reasonable amount of time then we should just let it go. Either way it looks like we'll be able to retract this PR.

**Pull request closed without merging**
