### PR TITLE
Fix profile page initials error for strange names

### PR DESCRIPTION
**Pull request by abought**
Tied to #2933 / #3635 .

## Purpose
Fix a front-end error that occurs when entering a middle name with two consecutive spaces. (edge case, but was hindering some other QA work on that page)

## Summary of changes
- Only calculate initials from non-empty parts of a tokenized string.
- Add regression test to ensure function works as intended.

## Side effects
- Exposes the `initials` function in NameViewModel to allow for unit testing. Updates calls to this function to avoid breaking existing functionality.

### CODE REVIEW

**Comment by sloria** [comment]
A more concise general solution would be to split on any number of whitespace characters:

```js
names
    .split(/\s+/)
    // ...
```

**Comment by sloria** [comment]
Pass finished. :sandal:

**Comment by abought** [comment]
> A more concise, general solution would be to split on any number of whitespace characters:

Ideally, yes. That assumes that $.trim() is called before `initials`, as otherwise trailing spaces would be output as empty tokens. How about this?

```javascript
    var initials = function(names) {
        names = $.trim(names);

        return names
            .split(/\s+/)
            .map(function(name) {
                return name[0].toUpperCase() + '.';
            })
            .filter(function(initial) {
                return initial.match(/^[a-z]/i);
            }).join(' ');
    };
```

**Comment by sloria** [comment]
@abought Sure.

**Pull request merged**
