### PR TITLE
[feature] add minimal base template

### PR DESCRIPTION
**Pull request by HarryRybacki**
## Purpose
Single use forms e.g. two factor auth, forgot password, and login, don't need many of the things packaged in the current `base.mako` template. `minimal_template.mako` strips the excess and leaves only the necessary components for the aforementioned and similar forms.

## Changes
One new template

## Side Effects
Faster loading times for singe use forms or pages with similar needs

## Notes
* Depends on PR: #2140

### CODE REVIEW

**Comment by HarryRybacki** [comment]
@sloria working example of the minimal_base template. I stripped the things from `base.mako` that I knew were not needed but there is a lot of things going on. Just ping any chunks that I can gut or raise a flag on anything I should look into deeper and I'll refine it.

**Comment by sloria** [comment]
@HarryRybacki Can you update with develop/?

**Comment by HarryRybacki** [comment]
@sloria sorry, thought I'd done that already. Re-pushed.

**Comment by sloria** [comment]
I'm going to hold off on merging this one. There is more duplication here than there was previously. Let's explore another solution: `minimal_base.mako` could inherit from `base.mako` and override the `stylesheets()` def to include the hiding rules. The auth forms would then inherit from `minimal_base.mako`.

**Comment by sloria** [comment]
@HarryRybacki The above is only a suggestion. I'm open to other ideas as well.

**Comment by HarryRybacki** [comment]
Was there other stuff from the template that could be removed? I **only** removed things I knew could be chucked.

**Comment by sloria** [comment]
@HarryRybacki Probably, but I think there will inevitably be a lot of duplication with `base.mako` even after paring the new template down, which isn't ideal.

**Pull request closed without merging**
