### PR TITLE
[feature] Add Explanatory Text to Wiki Version Dropdown [OSF-7635]

### PR DESCRIPTION
**Pull request by caseyrollins**
#### Purpose
- Display "Wiki Version: " next to the version list dropdown on the wiki page to make it clear to users what the dropdown controls.  

#### Side effects
- None expected.

#### Screenshots
- Before:
screen shot 2017-03-20 at 3 53 09 pm

- After:
screen shot 2017-03-20 at 3 52 16 pm

#### Ticket
- [OSF-7635](https://openscience.atlassian.net/browse/OSF-7635)

### CODE REVIEW

**Comment by alexschiller** [comment]
@caseyrollins Agreed, 👍 I'll file it as a deferred improvement.

**Comment by caseyrollins** [comment]
@alexschiller, sounds good. Also worth noting that discussion from Product might be needed (i.e. should we hide the version picker when the columns fall below a certain width?).

**Comment by brianjgeiger** [comment]
@caseyrollins Merge conflicts, and there may be another batch of merge conflicts with another wiki ticket in this release that has merge conflicts. So it may be a race between you and @chennan47 to see who can get merged first. https://openscience.atlassian.net/browse/OSF-7437

**Comment by caseyrollins** [comment]
Failing test is the MLA citation test. Travis is all good otherwise.

**Pull request merged**
