### PR TITLE
[WIP] JSONAPI Content Negotiation

### PR DESCRIPTION
**Pull request by pattisdr**
<h1> Purpose </h1>

We are changing the formatting of JSON responses in the API to match the JSONAPI v1 spec http://jsonapi.org/format/.  References Issue #3074.

This PR sends JSON data with the header `Content-Type: application/vnd.api+json`. 

<h1> Changes </h1>

Adds custom content negotiation for when `application/json` in acceptable media types. Enforces JSONAPIRenderer, which has the media_type `application/vnd.api+json`.   Custom content negotiation helped get around issues with Swagger docs. https://github.com/marcgibbons/django-rest-swagger/issues/271

New Response Headers
screen shot 2015-07-23 at 11 45 55 am

Old Response Headers 
screen shot 2015-07-23 at 11 46 14 am

### CODE REVIEW

**Comment by brianjgeiger** [comment]
I don't think we're going to return anything that's not JSON or HTML, but it might be better to return the JSON if the request type is a json requesting type, so if we added, I dunno, yaml or XML or something, it won't send the json type. That being said, if it looks like it's going to be A Thing to do that, then we can mark it as a potential future improvement.

**Comment by brianjgeiger** [comment]
Also, if you get this out of WIP before anyone else reviews the other related issues, we might as well just roll them all up into that one PR.

**Comment by pattisdr** [comment]
Custom content negotiation is now the same as DefaultContentNegotation except when `application/json` in acceptable media types. Then, the JSONAPIRenderer with media_type `application/vnd.api+json` is enforced.

Otherwise, it checks acceptable media types against the renderer, same as always.

**Comment by brianjgeiger** [comment]
Woo woo!

**Comment by pattisdr** [comment]
Merged with #3683

**Pull request closed without merging**
