### PR TITLE
Fix Flashing Change Cancel Buttons

### LINKED ISSUE #3649: Change category button flashes for parent project
# Steps
1. Go to a parent project for which you have admin access
2. Go to the settings page
3. Immediately as the page loads, pay attention to the Configure Project container at the top of the page

# Expected
Since this is a parent project and thus the category cannot be changed, I would expect that there would be no option to change the category, no matter how briefly it may appear.

# Actual
When the page first loads, buttons to change the category of the project appear for a split second:
parent project change button

Quickly, it goes away and the page appears as it is supposed to:
parent project no button

It would be ideal if the Change/Cancel buttons do not appear *at all* on the page

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h1> Purpose </h1>
Stop the change/cancel buttons on the project setting from briefly flashing during loading. Close #3649...Again.
<h1> Changes </h1>
This issue was a lot more problematic then expected, for some reason simply putting a ko containerless conditional statement around the buttons doesn't cut it, so this was the best I could come up with.
<h1> Side Effects </h1>
None that I know of.

### CODE REVIEW

**Comment by Johnetordoff** [comment]
@lyndsysimon does this look merge-worthy?

**Comment by lyndsysimon** [comment]
Check out the class "scripted" that is applied to HTML elements elsewhere in the OSF, where Knockout is being used.

**Comment by lyndsysimon** [comment]
Looks great to me :)

:star:

**Comment by lbanner** [comment]
:star2: :star2: ..... Good work @Johnetordoff

**Pull request merged**
