### PR TITLE
Remove backrefs for OSF-[5896, 5898, 5899, 5900, 5901, 5906, 5907, 5909]

### PR DESCRIPTION
**Pull request by abought**
Refs various, general parent is https://openscience.atlassian.net/browse/OSF-5674 

## Purpose
We are attempting to reduce the number of unused backrefs on our models, as backrefs create side effects (record locking) that are not ideal.

This PR is intended to encompass the low-hanging fruit: simple backrefs that can be easily replaced with small queries.

## Summary of changes
- Remove various unused backrefs (see diff)
- Replace usages of these backrefs with direct database queries

## Side effects/ testing notes
If all goes well, there will be no user-facing side effects, and OSF functionality will not change. Below is a list of features that could be affected by these changes.

- Make sure the list of active registrations appears correctly (eg for registrations tab on project pages)
- Watch (or unwatch) a project. Reload the page and make sure the number of watchers updates correctly. Make sure that you correctly receive updates about projects you are watching.
- Do something that would trigger a notification email (transactional or digest) on a project. Make sure that you receive the email correctly with no errors.
- Fork a project. Ensure the list of forks displays correctly, and the fork button updates with the correct fork count.
- Create a new project, using another project as a template. (fork button--> "copy project structure"). Verify that the "templated from" counter in the modal updates to show the correct count. 
- Node links should still work

There may be some issues with deletion as well. We don't really delete many things (users and nodes just get hidden via a flag), but try things like unwatching a node, and see if that gives errors.

## Subtasks
https://openscience.atlassian.net/browse/OSF-5896
https://openscience.atlassian.net/browse/OSF-5896
https://openscience.atlassian.net/browse/OSF-5898
https://openscience.atlassian.net/browse/OSF-5899
https://openscience.atlassian.net/browse/OSF-5900
https://openscience.atlassian.net/browse/OSF-5901
https://openscience.atlassian.net/browse/OSF-5906 (badges, unused)
https://openscience.atlassian.net/browse/OSF-5907 (badges, unused)
https://openscience.atlassian.net/browse/OSF-5909

### CODE REVIEW

**Comment by abought** [comment]
This PR deliberately omits changes to node/ NodeLog relations, which are handled separately (and in more detail) in https://github.com/CenterForOpenScience/osf.io/pull/4950

**Comment by abought** [comment]
Note to reviewers: per @brianjgeiger request, I have added several further commits, to deal with User and Badge models. 

I don't think this has been reviewed yet, so the change shouldn't affect any previous review efforts.

**Comment by brianjgeiger** [comment]
Could you check into the merge conflicts? I expect a vast majority of the codebase has recently changed.

**Comment by abought** [comment]
Fortunately there were only two (small) merge conflicts, so I've pushed resolutions. It seems that tests are failing broadly right now, so I've rerun them later once the develop branch has been sorted out.

**Comment by mfraezz** [comment]
```
Searching 3177 files for "attr\(.*, ['|"](merged|watched|recently_added|connected|creator|assertion|awarded|none|email_digest|email_transactional|_pointed|registered|tagged|forked|registrations|template_node|citations|shared|created)['|"]\)" (regex)

/Users/matt/Devel/osf.io/tests/test_models.py:
  747:         assert_true(hasattr(self.user, 'recently_added'))

1 match in 1 file


Searching 3177 files for "__(merged|watched|recently_added|connected|creator|assertion|awarded|none|email_digest|email_transactional|_pointed|registered|tagged|forked|registrations|template_node|citations|shared|created)" (regex)

/Users/matt/Devel/osf.io/CHANGELOG:
   40: - Dev: Remove node__contributed and node__created backrefs to improve performance and prevent locking errors.

/Users/matt/Devel/osf.io/scripts/migrate_guid.py:
  210:     for idx, fork in enumerate(node.node__forked):
  214:                 node.node__forked[idx] = record._primary_key
  216:     for idx, registration in enumerate(node.node__registrations):
  220:                 node.node__registrations[idx] = record._primary_key

5 matches across 2 files
```

* `<user>.recently_added` is a field, though there was a backref of the same name, so that's fine. 
* `scripts/migrate_guid.py` hasn't been needed since 2013.

:+1:

**Comment by mfraezz** [comment]
LGTM. Didn't see any weird edge cases when looking over it, and it doesn't look like you missed any backref accesses. Dropping it in RTM when the build is passing again. :checkered_flag:

**Comment by abought** [comment]
Unrelated CI failures were the main blocker; can someone with Travis Button Permissions please restart the build?

**Pull request merged**
