### PR TITLE
Have /help/ display the /faq/ page [#OSF-4039]

### PR DESCRIPTION
**Pull request by DanielSBrown**
## Purpose

- As of now, the osf.io/help/ page has not been made, and is a dead end

- Displays the /faq/ page on attempting to reach the /help/ page

## Changes

- Added to a Rule in routes.py, where going to /help/ will display the /faq/ mako template.

- Added a test case that tests to make sure the page is reached in test_views.py

## Ticket
https://openscience.atlassian.net/browse/OSF-4039

### CODE REVIEW

**Comment by DanielSBrown** [comment]
I am not sure if the test case is comprehensive.  I compared the HTTP status code with 200, which may not be enough.  Please let me know if I should add other assert statements/change the status code check.

**Comment by brianjgeiger** [comment]
This is good. 🎉 🐧 🎉

**Comment by sloria** [comment]
I'm thinking we should redirect `/help/` to `/faq/`, rather than having `/help/` return a 200. Having multiple URLs point to the same resource is an antipattern.

Also, `/help/` should be removed from the old Rule (https://github.com/CenterForOpenScience/osf.io/blob/35514cbb6112e64ecf676213db21f6423c70ccd5/website/routes.py#L255).

**Comment by sloria** [comment]
Pass finished.

**Pull request merged**
