### PR TITLE
[WIP] Implement OAuth scopes in APIv2

### PR DESCRIPTION
**Pull request by abought**
## Purpose 
When third parties log in to access OSF data on behalf of users (#3323), there should be a way to restrict how much power the third party has over the user's account. 

Sample limitations: A stats-gathering application should not be able to add/remove contributors from a project, and a service that verifies user identity should not need the power to delete files.

Scopes can also be used to restrict routes to internal use only. (for private data, such as email addresses, that we never intended to be exposed to the outside world) This will be helpful as we move more of the internal OSF behavior to the new standard API going forward.

Requires APIv2 release + #3082 to be useful. The release of scopes in this PR will require updates to the docs that live in #4150.

Also depends on associated CAS changes currently in testing phase.

## Status
Work in progress; not yet ready to be merged.

## Summary of changes
TODO: Add 

## Deployment considerations
- CAS draws the list of recognized scopes from a new database collection. The script `scripts/register_oauth_scopes.py` will need to be run as part of deployment to the server.

- [ ] Confirm that no unit tests break when running fakecas and all views remain accessible when OSF oauth token response behavior is changed.

## TODO
- [x] Write script to add these scopes to a mongo collection, and make that script part of the release/ rollout process alongside the updated CAS.
- [x] Finalize list of accepted scopes (see gdoc proposal)
- [x] Add tests to verify that scopes work as intended
- [ ] Refactor existing views to obey access restrictions per design intent (eg do not give less information than an unauthenticated request)

- [ ] Verify that `osf.admin` scope can not be requested by third parties

### CODE REVIEW

**Comment by abought** [comment]
List of granular permissions and how they map to composed scopes. (see diff for which granular permissions are attached to each API view). @erinmayhood 

{'osf.admin': ['applications+read',
                         'applications+write',
                         'nodes.basic+read',
                         'nodes.basic+write',
                         'nodes.children+read',
                         'nodes.children+write',
                         'nodes.contributors+read',
                         'nodes.contributors+write',
                         'nodes.files+read',
                         'nodes.files+write',
                         'nodes.links+read',
                         'nodes.links+write',
                         'nodes.registrations+read',
                         'nodes.registrations+write',
                         'users+read',
                         'users+write'],
 'osf.full+read': ['nodes.basic+read',
                             'nodes.children+read',
                             'nodes.contributors+read',
                             'nodes.files+read',
                             'nodes.links+read',
                             'nodes.registrations+read',
                             'users+read'],
 'osf.full+write': ['nodes.basic+read',
                              'nodes.basic+write',
                              'nodes.children+read',
                              'nodes.children+write',
                              'nodes.contributors+read',
                              'nodes.contributors+write',
                              'nodes.files+read',
                              'nodes.files+write',
                              'nodes.links+read',
                              'nodes.links+write',
                              'nodes.registrations+read',
                              'nodes.registrations+write',
                              'users+read',
                              'users+write'],
 'osf.nodes.access+read': ['nodes.contributors+read',
                                             'nodes.registrations+read'],
 'osf.nodes.access+write': ['nodes.contributors+read',
                                              'nodes.contributors+write',
                                              'nodes.registrations+read',
                                              'nodes.registrations+write'],
 'osf.nodes.all+read': ['nodes.basic+read',
                                      'nodes.children+read',
                                      'nodes.contributors+read',
                                      'nodes.files+read',
                                      'nodes.links+read',
                                      'nodes.registrations+read'],
 'osf.nodes.all+write': ['nodes.basic+read',
                                       'nodes.basic+write',
                                       'nodes.children+read',
                                       'nodes.children+write',
                                       'nodes.contributors+read',
                                       'nodes.contributors+write',
                                       'nodes.files+read',
                                       'nodes.files+write',
                                       'nodes.links+read',
                                       'nodes.links+write',
                                       'nodes.registrations+read',
                                       'nodes.registrations+write'],
 'osf.nodes.data+read': ['nodes.files+read'],
 'osf.nodes.data+write': ['nodes.files+read', 'nodes.files+write'],
 'osf.nodes.metadata+read': ['nodes.basic+read',
                                                'nodes.children+read',
                                                'nodes.links+read'],
 'osf.nodes.metadata+write': ['nodes.basic+read',
                                                 'nodes.basic+write',
                                                 'nodes.children+read',
                                                 'nodes.children+write',
                                                 'nodes.links+read',
                                                 'nodes.links+write'],
 'osf.users+read': ['users+read'],
 'osf.users+write': ['users+read', 'users+write']
}

**Comment by HarryRybacki** [comment]
@abought please append, [#OSF-4208], to the latest commit message to ensure the correct Jira ticket is tracking this PR. Furthermore, if there is any information missing in the [Jira ticket](https://openscience.atlassian.net/browse/OSF-4208) please update it so CR/QA will have everything they need.

[#OSF-4208](https://openscience.atlassian.net/browse/OSF-4208)

**Comment by lbanner** [comment]
Thanks for the find @HarryRybacki -- I'm going to remove OSF-4208 from JIRA as it's a PR -- and actually @abought please add to your commit message [#OSF-4274] -- that now represents the parent issue in progress.

**Comment by HarryRybacki** [comment]
@lbanner, @erinmayhood and I have been deleting the Issue tickets and keeping the PR tickets -- I suppose it doesn't matter as long as one is tied to the PR

**Comment by lbanner** [comment]
Yeah -- I've been doing it the other way around : )

**Pull request merged**
