### PR TITLE
Fix title description category inconsistency

### PR DESCRIPTION
**Pull request by zkraime**
<b>Purpose:</b>
To fix issue #2686 - project title and description could only be edited in the dashboard page as inline editables. 
<b>Changes:</b>
Title and description can now be edited in the project settings page as normal text and textarea inputs,
as shown: 
1-
screen shot 2015-06-11 at 11 53 27 pm
2-
screen shot 2015-06-11 at 11 53 50 pm
3-
screen shot 2015-06-11 at 11 54 10 pm
4-
screen shot 2015-06-11 at 11 54 42 pm

<b>Side effects:</b>
One thing I noticed was that if you enter html as input for title, it saves and the title appears blank:

screen shot 2015-06-12 at 12 03 20 am
screen shot 2015-06-12 at 12 03 35 am

The validation for title probably needs to be refactored anyway. I wanted to use changeMessage.js for the title and description alert messages but wasn't sure how to do so since it seems like the messages can only bind to one element (category). So, I just made it display an error message in case of a failure:
screen shot 2015-06-12 at 12 13 17 am

### CODE REVIEW

**Comment by samanehsan** [comment]
Looks like you have some extra commits/changed files not related to this fix. Can you undo those changes or resubmit this with just the relevant commits? Thanks!

**Comment by zkraime** [comment]
@samanehsan I guess I did something wrong but I could have sworn I didn't make those commits (Fix navber overlap on Getting Started page,  fix warning message update error, etc) while on the fix_title_description_category_inconsistency branch so I'm not sure why they're showing up here. I did make a commit when I thought I had fixed the issue (I took away the inline editability in the dashboard page and moved it to the settings page), but then I had to redo it and revert some changes but I didn't actually undo any commits. 
I would need to undo those older commits while on this branch, right?

**Comment by samanehsan** [comment]
Maybe these commits were on your develop branch?

**Comment by zkraime** [comment]
@samanehsan If I made commits to a branch and then merged it with my develop, would that explain it? Because that definitely happened

**Pull request closed without merging**
