### PR TITLE
[No ticket] Project overview: Collection info

### PR DESCRIPTION
**Pull request by futa-ikeda**
## Purpose
- Address small changes for Project Overview's Collection info area before development

## Changes
- A11y
  -  Use semantic `<button>` for toggling collection specific metadata and preprint's supplemental material dropdown
  - Added aria-label, as this button has no visible text
  - Styling
- Show character-lab specific metadata: school-type and study-design

## Screenshot
Before: missing school type and study design
image

After: school type and study design included
image

Better accessibility for collections metadata dropdown and preprint supplemental materials dropdown
image

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify that projects submitted to CharacterLab (or really any collection-provider that has options for "School Type" and "Study Design" show this information in the project overview page where is says "Included in CharacterLab's Collection"
- Verify that the button to toggle the collection-specific metadata passes A11y standards

What are the areas of risk?
- Just A11y related issues maybe?

Any concerns/considerations/questions that development raised?

## Documentation
- NA

## Side Effects
- I addressed another dropdown for Preprints that link to a given project for supplemental materials as well that could use better a11y

## Ticket
NA

### CODE REVIEW

**Comment by Johnetordoff** [comment]
@futa-ikeda is this still needed?

**Comment by futa-ikeda** [comment]
Yea, this will be needed to fix an issue with the CharacterLab specific metadata fields. If it's easier to take these changes and put them into a different PR, that's fine by me

**Comment by Johnetordoff** [comment]
@futa-ikeda But other then [this button](https://github.com/CenterForOpenScience/osf.io/pull/10079/files#diff-89e5cfea80432a55e0de1b335ca4043cfca80905fb1643c4fab6aa27d704a2e0R393) all these elements are changing with: https://github.com/CenterForOpenScience/osf.io/pull/10115/files

**Comment by futa-ikeda** [comment]
Ahh, ok, will close!

**Pull request closed without merging**
