### PR TITLE
[feature fix] stop logged-out users from seeing project buttons

### LINKED ISSUE #3249: Duplicate and Watch buttons should not be visible to logged out users
This issue was caught by an OSF user, and then was logged in the community repo: https://github.com/CenterForOpenScience/community/issues/258

<h4>Steps</h4>
1. Visit any OSF project while logged out
2. Look at the upper right hand of the project overview page

<h4>Current behavior</h4>
1. The watch button is greyed out, indicating no action can be taken, but it is still present.
2. The duplicate button is active and users can click on it, though the options to fork/template/link are unavailable.

screen shot 2015-06-22 at 12 02 49 pm

<h4>Expected behavior</h4>
1. The watch button and the duplicate button should not be visible to users who are not signed in; at the very least, the duplicate button should not be clickable by users who are not signed in.

### PR DESCRIPTION
**Pull request by XTech2K**
### Purpose
Fixes #3249

Everybody, including people who were not logged in, was seeing the buttons in the upper right of the main project screen for every project. All of these are completely useless to a non-user as the project would have to be public for them to see it, and the buttons do nothing unless you are logged in.

### Changes
Add a check for user_name before showing any of the buttons.

### CODE REVIEW

**Comment by lyndsysimon** [comment]
Looks great; verified working. Good to merge.

**Comment by lyndsysimon** [comment]
On second thought - @jlcohoon, could you confirm that the intention here is to remove all buttons from the top right, including the "public" one?

**Comment by jlcohoon** [comment]
I'm outnumbered: Most people say they think they should be inactive but visible and a tooltip on hover to say "Must be logged in to duplicate a project" rather than totally remove them.

**Comment by XTech2K** [comment]
Replaced by #3307, which renders buttons inactive instead of removing them, and also adds a tooltip.

**Pull request closed without merging**
