### PR TITLE
Change Default Language on Wiki without Content[#OSF-7437]

### PR DESCRIPTION
**Pull request by chennan47**
## Purpose
Change Default Language on Wiki without Content

## QA notes:
1. create a new project without any wiki
2. go to the project overview page and watch the wiki widget
before change:
screen shot 2017-02-22 at 10 23 21 am
after change:
screen shot 2017-03-22 at 10 35 57 am

## Ticket
https://openscience.atlassian.net/browse/OSF-7437

### CODE REVIEW

**Comment by brianjgeiger** [comment]
@chennan47 Your after screenshot doesn't show the change; it cuts off too high.

**Comment by chennan47** [comment]
correct screenshot updated.

**Comment by brianjgeiger** [comment]
Merge conflicts

**Comment by brianjgeiger** [comment]
@chennan47 That diff looks all wrong. Could you cherry-pick your commits into a fresh pull from develop or similar?

**Comment by chennan47** [comment]
closed in favor of https://github.com/CenterForOpenScience/osf.io/pull/7175

**Pull request closed without merging**
