### PR TITLE
[Ready] [Style] wiki dialog style update

### PR DESCRIPTION
**Pull request by caneruguz**
## Purpose
The wiki uses dialogs for adding link and adding image. This change brings the style of these dialog boxes to look like modals without using modal syntax but using the modal classes

Addresses issue: https://trello.com/c/YPSBca7A

## Changes 
The static vendor file in wiki/static/pagedown-ace/ was changed to use modal classes

## Side effects
This is a change in vendor library but it's not installed with package manager and I think it's stable enough but we need to keep an eye on this in case the markdown file is replaced. 

#### BEFORE:
screen_shot_2015-07-09_at_2 20 27_pm

#### AFTER: 
screen shot 2015-07-14 at 9 44 25 am

### CODE REVIEW

**Comment by sloria** [comment]
Please remove the "Need free image hosting". Also, the example can probably be a placeholder for the input.

Once that's finished, this is good to merge.

**Comment by sloria** [comment]
Also, I don't think "Apply" is the correct word for adding an image. How about "Add"?

**Comment by caneruguz** [comment]
I'm not sure about adding the example as a placeholder for input. I think it's too much and better to leave the input cleaner. What do you think Steve?

**Comment by sloria** [comment]
I think it's fine either way.

**Pull request merged**
