### PR TITLE
[feature] Remove Large File Uploads

### PR DESCRIPTION
**Pull request by caseyrollins**
- Allows rejected files to be cancelled.
 - Adds failed uploads (files that exceed the maximum upload size) to the list of uploaded files that can be cancelled. 
- [OSF-5410]

### CODE REVIEW

**Comment by whit537** [comment]
Reviewing ...

**Comment by whit537** [comment]
https://openscience.atlassian.net/browse/OSF-5410

**Comment by whit537** [comment]
Funny ... such a small PR, but it's gonna take me a bit to review this because I haven't actually set up filestorage locally yet(!). :-)

**Comment by whit537** [comment]
I'm not finding a `file` or `storage` target in [`tasks/__init__.py`](https://github.com/CenterForOpenScience/osf.io/blob/ec5a4d8e4668e12f58b9610287cf7cc71c44620d/tasks/__init__.py).

**Comment by whit537** [comment]
Oh, right! [Waterbutler](https://github.com/CenterForOpenScience/osf.io/tree/4cadc319786d12b2526d1ab5e282cc9473537fd6#waterbutler)!

**Comment by whit537** [comment]
I've cloned waterbutler and installed it into a virtualenv with `inv install --develop`. I get the following traceback from `inv server`. Maybe I need to configure it betterer?

```
WARNING:root:No '/Users/whit537/.cos/waterbutler-test.json' configuration file found
Traceback (most recent call last):
  File "/Users/whit537/workbench/cos/waterbutler/env/bin/inv", line 11, in <module>
    sys.exit(main())
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/invoke/cli.py", line 438, in main
    dispatch(sys.argv)
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/invoke/cli.py", line 431, in dispatch
    return executor.execute(*tasks)
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/invoke/executor.py", line 100, in execute
    task=task, name=name, args=args, kwargs=kwargs, config=config
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/invoke/executor.py", line 153, in _execute
    result = task(*args, **kwargs)
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/whit537/workbench/cos/waterbutler/tasks.py", line 81, in server
    from waterbutler.server.app import serve
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/server/app.py", line 12, in <module>
    from waterbutler.server.api import v0
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/server/api/v0/__init__.py", line 1, in <module>
    from waterbutler.server.api.v0 import zip
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/server/api/v0/zip.py", line 4, in <module>
    from waterbutler.server.api.v0 import core
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/server/api/v0/core.py", line 11, in <module>
    from waterbutler import tasks
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/tasks/__init__.py", line 2, in <module>
    from waterbutler.tasks.copy import copy
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/tasks/copy.py", line 5, in <module>
    from waterbutler.core import utils
  File "/Users/whit537/workbench/cos/waterbutler/waterbutler/core/utils.py", line 7, in <module>
    import aiohttp
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module>
    from . import hdrs  # noqa
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/aiohttp/hdrs.py", line 2, in <module>
    from .multidict import upstr
  File "/Users/whit537/workbench/cos/waterbutler/env/lib/python3.5/site-packages/aiohttp/multidict.py", line 285, in <module>
    class _ItemsView(_ViewBase, abc.ItemsView):
  File "/usr/local/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
TypeError: multiple bases have instance lay-out conflict
```

**Comment by whit537** [comment]
Or maybe I need to drop back to Python 3.4?

**Comment by whit537** [comment]
Gosh, that's an obscure error. :flushed:

**Comment by whit537** [comment]
Looks like a bug in `aiohttp`? What version do I have installed? Can't import to find out ...

**Comment by felliott** [comment]
@whit537, if you're running `develop`, python 3.4 is required.

**Comment by whit537** [comment]
Waterbutler's [`requirements.txt`]() specifies 0.14.1 ... is that what I have? Looks like `setup.py` defers to `requirements.txt` ...

**Comment by whit537** [comment]
@felliott I'm using Python 3.5. I wouldn't expect dropping back to 3.4 to resolve this, but maybe ...

**Comment by felliott** [comment]
It definitely will.  We've run into this one a lot.

**Comment by whit537** [comment]
Gosh, okay! Thanks for the tip. :-)

**Comment by whit537** [comment]
Looks like `aiohttp` adapted in https://github.com/KeepSafe/aiohttp/pull/289. Presumably that's included in newer releases (current is 0.21.2).

**Comment by whit537** [comment]
Got it! Thanks @felliott. :-)

screen shot 2016-03-11 at 1 09 39 pm

screen shot 2016-03-11 at 1 10 27 pm

**Comment by whit537** [comment]
Yessssssssssss.

screen shot 2016-03-11 at 1 13 13 pm

**Comment by whit537** [comment]
Okay! Now how do I add files? :confused:

**Comment by whit537** [comment]
Blam. Now for a file that's too large ... how large is too large?

screen shot 2016-03-11 at 1 14 25 pm

**Comment by caseyrollins** [comment]
@whit537 5 GB is too large!

**Comment by whit537** [comment]
@caseyrollins Where is that configured? I'm not finding anything obvious in `settings.py` for osf.io or waterbutler.

**Comment by caseyrollins** [comment]
@whit537, the max size varies for each addon, but for OSF Storage it's configured [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/osfstorage/__init__.py#L36).

**Comment by whit537** [comment]
Gosh. Why is it there instead of in [`settings/default.py`](https://github.com/CenterForOpenScience/osf.io/blob/ec5a4d8e4668e12f58b9610287cf7cc71c44620d/website/addons/osfstorage/settings/defaults.py)? It looks like the `osfstorage` addon has the same [layering](https://github.com/CenterForOpenScience/osf.io/blob/ec5a4d8e4668e12f58b9610287cf7cc71c44620d/website/addons/osfstorage/settings/__init__.py#L7) as `website`, but, as it stands, directly modifying `__init__.py` seems the easiest way to override that setting. Unless I'm missing something?

Oh, well. Forging ahead! :-) :fork_and_knife:

**Comment by whit537** [comment]
I used `mkfile 6m foo` to make a file for testing.

screen shot 2016-03-11 at 3 37 14 pm

**Comment by whit537** [comment]
The cancel button works. I'm trying to get it to not work on `develop`.

**Comment by whit537** [comment]
Success! Now it does nothing. :-)

screen shot 2016-03-11 at 3 50 42 pm

**Comment by whit537** [comment]
Okay! All clear here. Go science! :-)

:+1:

**Pull request merged**
