### PR TITLE
modify the warning language

### PR DESCRIPTION
**Pull request by chennan47**
<b>Purpose</b>
Update the anonymous link warning message. fix https://github.com/CenterForOpenScience/osf.io/issues/2562

<b>Change</b>
before change:
screen shot 2015-04-23 at 10 03 15 am

after change:
screen shot 2015-04-23 at 10 04 03 am

### CODE REVIEW

**Comment by lbanner** [comment]
Suggested language change @nanchen47 : 
Ensure the wiki pages, files, registration supplements you have created, and addons to which you have linked this project do not contain identifying information.

**Comment by chennan47** [comment]
@lbanner Thanks and done.

**Comment by sloria** [comment]
Could be more concise:

> Ensure that wiki page content, files, registration supplements, and add-ons do not contain identifying information.

**Comment by chennan47** [comment]
@sloria Thanks and done in 2019503

**Comment by lbanner** [comment]
Good! Agreed.

**Pull request merged**
