### PR TITLE
[PLAT-493] Allow project files to be embedded/rendered in the wiki

### PR DESCRIPTION
**Pull request by Johnetordoff**
Merged and bumped!
<s>❗️ Once the corresponding markdown-it-video PR (https://github.com/brianjgeiger/markdown-it-video/pull/31) is merged, this PR should point to the new version of markdown-it-video before being reviewed/merged ❗️ </s>

## Purpose

This PR allows users to render files from MFR on the wiki editor by safely including an iframe.

## Changes

- This works by forking the "markdown-it-video" plugin and adding a service to it, MFR. The new fork can be found here: https://github.com/Johnetordoff/markdown-it-mfr/tree/add-service-mfr
- To load MFR javascript for iframe sizing changes to the wiki page and project page makos had to be made.

mfr_embed_better_sizing

## QA Notes

Check that:

- Mfr iframes render when formatted `@[osf](<guid>)` , Note: the guid must be for a file that on prod. - Check for appropriate sizing on different file formats.
- Other video tags like `@[youtube](<id>)` work.

This will also need doc updates at http://help.osf.io.

## Side Effects

- markdown-it-video had a video "doubling" issue discovered while writting this that was wrapped up here: https://github.com/brianjgeiger/markdown-it-video/pull/30

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/PLAT-493

### CODE REVIEW

**Comment by caseyrollins** [comment]
Two initial drive-by comments: 
1. Can the service name be changed from MFR? I don't think Product will be a fan of the `@[mfr](abcde)` syntax. What about `@[file](abcde)`?
2. Why does the guid need to be a file on that project? And does this include that project's components? AFAIK MFR will show "unauthorized" if you don't have permission to view a file. What happens currently if you enter a guid for a file on a different project?

**Comment by Johnetordoff** [comment]
1. Can definitely change it to @[file](abcd), that's 1000% better, though I'll ask product for exact wording first.
2. The guid can be on any file with a guid in production, that you have permissions for.

**Comment by Johnetordoff** [comment]
Product has approved @[file](<guid>) and I've updated the repo this is now ready for peer review.

**Comment by Johnetordoff** [comment]
@caseyrollins This has @[osf] tag, no doubling issue and renders on the project overview page, should be on it's final swoop.

**Comment by caseyrollins** [comment]
@Johnetordoff, this PR just needs a new lockfile generated and it will be RTM (I think the command is just `yarn install`?). 

Excellent work!

**Comment by Johnetordoff** [comment]
@caseyrollins 👍

**Pull request merged**
