### PR TITLE
[RFR][OSF-4338] Clean up gravatar specific methods

### PR DESCRIPTION
**Pull request by TomBaxter**
## Purpose

Abstract hard coded gravatar methods to generalized profile_image methods, to make way for the possibility of using other/multiple avatar providers.

## Changes

website/filters/__init__.py
 - Create profile_image_url function to use filter_providers dictionary to point to gravatar filter

website/settings/defaults.py
 - Create PROFILE_IMAGE_PROVIDER variable for default filter_provider

Change variable names throughout osf.io gravatar --> profile_image
Add --nocapture parameter to test_module task. Allows viewing print statements.
Fix various pep8 infractions

## Side effects

None

## Ticket

[OSF-4338](https://openscience.atlassian.net/browse/OSF-4338)

### CODE REVIEW

**Comment by TomBaxter** [comment]
@brianjgeiger Here's another old approved PR. It had conflicts, which I have resolved.

**Comment by brianjgeiger** [comment]
@TomBaxter If you have a moment this weekend, could you clear up these merge conflicts? We're hoping to get everything merged so QA will be able to test as soon on DjangOlé has been released.

**Comment by TomBaxter** [comment]
@brianjgeiger Sorry I didn't get to this sooner. Merge conflicts addressed and in the Travis queue now.

**Comment by brianjgeiger** [comment]
Tests in branch 2 are failing in a weird way. Can you take a quick look at it?

**Comment by TomBaxter** [comment]
Ok, yeah, saw that. Looked a bit and wasn't obvious how the failures related to my code changes. I'll look harder.

**Comment by brianjgeiger** [comment]
If I see them anywhere else, I'll let it go. So far I don't recall having done so.

**Comment by TomBaxter** [comment]
Fixed. Just passed my Travis, still queued up for COS Travis.

**Pull request merged**
