### PR TITLE
Feature/migrate conference admins

### PR DESCRIPTION
**Pull request by jmcarp**
# Purpose
Add migration script to replace conference administrators with personal addresses (Andrew, Katy) with a staff account (currently configured to be presentations@cos). This will ensure continuity throughout personnel changes on the presentation service.

# Changes
* Add migration script
* Add unit test

# Side effects
None expected

Note @sloria: a `User` with the email address `STAFF_EMAIL` must exist before running this script.

### CODE REVIEW

**Comment by sloria** [comment]
@AndrewSallans @KatyCain526 @saradbowman Will one of you create the account for `presentations@cos.io`?

**Comment by saradbowman** [comment]
I will do this now.

**Comment by JeffSpies** [comment]
Should it be presentations@cos or presentations@osf?

**Comment by JeffSpies** [comment]
Let's go with cos. Easier from an mailgun point of view.

**Comment by saradbowman** [comment]
upon further discussion, @osf is better. So it will be: presentations@osf.io. Creating the account now.

**Comment by saradbowman** [comment]
done.

**Comment by saradbowman** [comment]
I see that this is merged, but I'm still listed as a contributor on projects - can someone check into this?

**Comment by lbanner** [comment]
@sloria ^^ -- Thanks.

**Comment by sloria** [comment]
Just ran the migration script. @saradbowman Can you check again?

**Comment by saradbowman** [comment]
Still a contributor, womp womp.

**Pull request merged**
