### PR TITLE
[WIP] API registration creation

### PR DESCRIPTION
**Pull request by pattisdr**
<h1> Purpose </h1>
Regarding Issue #3046, this code allows users to create registrations through the API through a two-step process.  To confirm the user wishes to register the project, the user is preventing from POSTing all in one go. <ol>

<li> User sends a POST request containing supplemental registration information. </li>
<li> Server returns 400 error with a message telling them they are about to register the project along with a new URL containing a token. </li>
<li> User submits second POST request, this time to new URL, containing supplemental registration information. </li>
<li> Registration is created provided tokens match. </li>
</ol>

<h1> Changes </h1>
<ul>
<li> Added eight new URL's to api/nodes/urls.py

 . There are currently 4 registration types, with 2 URL's each, one with token and one without. </li>
<li> Added a token creator to api/base/utils.py, which generates the token attached to the second URL.
<li> Added views to api/nodes/views.py.  The current views are separated because condensing them into one view calling different serializers for different URL's affects the Swagger documentation. </li>
<li> Added serializers to api/nodes/serializers.py </li>
<li> Added to website/language.py and api/base/settings/defaults.py for warning message and enabling message to be translatable </li>
<li> Added tests for registration creation at test_views.py </li> 

</ul>

<h1> Side Effects </h1>
<ul>
<li> Eight new POST operations in Swagger documentation </li>
screen shot 2015-06-10 at 3 34 06 pm

<li>  User submits supplemental registration information along with request. Submitting the initial POST request for an OSF-Standard Pre-Data Collection Registration is shown here, for example. </li>
screen shot 2015-06-10 at 3 36 31 pm

### CODE REVIEW

**Comment by samchrisinger** [comment]
@GaryKriebel, @lbanner-- the work done here paves the way for some major improvements to the registrations API. Having spoken some with @brianjgeiger about the future of registrations and their relationship to the V2 API, I do have some concerns about parts of this implementation. 

It may be worthwhile for some combination of @brianjgeiger, @pattisdr, @leb2dg, @ericanbaranski, and myself to sit down and discuss the eventual implementation. This all hinges on the completion and review of the Prereg Prize proposal: https://docs.google.com/document/d/1-CdCKQCQFZ_ju5TEWqIKEII7WiellBurb53sGWJduJ0/edit, but there may be early steps we can take now towards the future implementation.

Please advise.

**Comment by lbanner** [comment]
Appreciate the heads-up on this @samchrisinger -- Yes, we will roundtable on this -- We'll set it up. Thanks.

**Comment by brianjgeiger** [comment]
Oh, and I think you mean @barbour-em rather than @ericanbaranski (who I'd be delighted to chat with, but is probably busy with other things).

**Comment by samchrisinger** [comment]
Indeed. Sorry Erica for the unnecessary ping.

**Comment by ericanbaranski** [comment]
No worries. Looks like exciting stuff!

On Thu, Jun 11, 2015 at 12:03 PM, Sam Chrisinger <notifications@github.com>
wrote:

> Indeed. Sorry Erica for the unnecessary ping.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/pull/3052#issuecomment-111240741>
> .
>



-- 
Erica Baranski
Graduate Student
Department of Psychology
University of California, Riverside

**Comment by brianjgeiger** [comment]
Looks like we're not using an import. Could you fix that? Thanks!

screen shot 2015-06-15 at 10 35 30 am

**Comment by pattisdr** [comment]
Closing due to pending changes in registration functionality.

**Pull request closed without merging**
