### PR TITLE
Support test-level database isolation [OSF-7042]

### PR DESCRIPTION
**Pull request by whit537**
## Purpose

Our current testing infrastructure scopes database isolation to the test class level. Better practice is to scope isolation to the test-case level, to avoid interference between one test and another. This PR factors out a `DbIsolationMixin` implementing test-level isolation for use across multiple test classes.

## Changes

No user-visible changes.

## Side effects

No side-effects.

## Ticket

https://openscience.atlassian.net/browse/OSF-7042

### CODE REVIEW

**Comment by whit537** [comment]
👍

Level-set ... here's local results for 337b9d41f2cbef6470feab24d949cda18cadfa2f:

```
osf.io| $ nosetests tests/
[...]
Ran 2096 tests in 1453.654s

FAILED (SKIP=20, errors=86, failures=1)
```

**Comment by whit537** [comment]
Let's find a smaller subset that'll work well for faster iteration ... maybe `test_models.py`?

**Comment by whit537** [comment]
Hmm ... maybe even smaller. :-)

```
osf.io| $ nosetests tests/test_models.py
[...]
Ran 465 tests in 297.314s

FAILED (errors=9)
```

**Comment by whit537** [comment]
Okay, let's work with this:

```
osf.io| $ nosetests tests/test_models.py:TestUser
[...]
Ran 68 tests in 7.377s

FAILED (errors=8)
```

**Comment by whit537** [comment]
Picking up from restricted [Jira](https://openscience.atlassian.net/browse/OSF-7042?focusedCommentId=39216&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-39216) ...

> But are we talking another minute on our test suite, or almost doubling the time?

Looks more like 20x. 😁

```
osf.io| $ nosetests tests/test_models.py:TestUser

[...]
Ran 68 tests in 140.342s

FAILED (errors=8)
```

That's with this diff:

```diff
diff --git a/tests/test_models.py b/tests/test_models.py
index 5558ee4..6b89294 100644
--- a/tests/test_models.py
+++ b/tests/test_models.py
@@ -257,7 +257,9 @@ class TestUserValidation(OsfTestCase):
                 self.user.save()
 
 
-class TestUser(OsfTestCase):
+from tests.base import DbIsolationMixin
+
+class TestUser(DbIsolationMixin, OsfTestCase):
 
     def setUp(self):
         super(TestUser, self).setUp()
```

**Comment by whit537** [comment]
Okay! To the profiler mobile! 🚙

**Comment by whit537** [comment]
http://nose.readthedocs.io/en/latest/plugins/prof.html

**Comment by whit537** [comment]
Nose's profiling plugin uses the [deprecated](https://docs.python.org/2/library/profile.html#introduction-to-the-profilers) `hotshot` module, which seems not to work with the `pstats` browser:

```
osf.io| $ python -m pstats isolated.dat 
ValueError: bad marshal data (unknown type code)
Welcome to the profile statistics browser.
% stats
No statistics object is loaded.
%
```

**Comment by sloria** [comment]
FWIW, our switch to Postgres/Django ORM will come with Django's built-in machinery for test DB isolation. We already have a good chunk of the models and views tests running with pytest and pytest-django.

**Comment by whit537** [comment]
Thanks, @sloria. I figured the switch to Postgres would impact this, hence such a small PR here. I'm looking for the minimum possible to support #6184 along with #6104.

**Comment by whit537** [comment]
```
osf.io| $ python -m cProfile -o isolated.dat env/bin/nosetests tests/test_models.py:TestUser
[...]
osf.io| $ python -m pstats isolated.dat 
Welcome to the profile statistics browser.
isolated.dat%
```

👍

**Comment by whit537** [comment]
```
isolated.dat% sort cumtime
isolated.dat% stats 20
Fri Sep 23 10:13:43 2016    isolated.dat

         7622641 function calls (7473185 primitive calls) in 112.277 seconds

   Ordered by: cumulative time
   List reduced from 11200 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001  112.283  112.283 env/bin/nosetests:4(<module>)
        1    0.000    0.000  111.862  111.862 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:102()
        1    0.000    0.000  111.862  111.862 /usr/local/lib/python2.7/unittest/main.py:72(__init__)
        1    0.000    0.000  107.268  107.268 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:195()
        1    0.000    0.000  107.268  107.268 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:46(r)
      3/1    0.000    0.000  107.264  107.264 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/suite.py:176)
      3/1    0.001    0.000  107.264  107.264 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/suite.py:197)
       68    0.000    0.000  106.009    1.559 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/case.py:44(_)
       68    0.001    0.000  106.009    1.559 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/case.py:115()
       68    0.001    0.000  105.996    1.559 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/case.py:142()
       68    0.000    0.000  105.995    1.559 /usr/local/lib/python2.7/unittest/case.py:392(__call__)
       68    0.003    0.000  105.995    1.559 /usr/local/lib/python2.7/unittest/case.py:295(run)
    27794   96.808    0.003   96.808    0.003 {method 'recv' of '_socket.socket' objects}
    13761    0.154    0.000   95.248    0.007 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/pymongo/mongo_cli)
    27522    0.153    0.000   95.059    0.003 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/pymongo/mongo_cli)
       68    0.002    0.000   83.049    1.221 /Users/whit537/workbench/cos/osf.io/tests/test_models.py:264(setUp)
       70    0.076    0.001   81.198    1.160 /Users/whit537/workbench/cos/osf.io/framework/mongo/handlers.py:103(set_up_storage)
       68    0.001    0.000   80.320    1.181 /Users/whit537/workbench/cos/osf.io/tests/base.py:171(setUp)
    14514    0.121    0.000   78.977    0.005 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/pymongo/collectio)
    11109    0.265    0.000   78.680    0.007 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/pymongo/collectio)
```

**Comment by whit537** [comment]
```
osf.io| $ python -m pstats unisolated.dat
Welcome to the profile statistics browser.
unisolated.dat% sort cumtime
unisolated.dat% stats 20
Fri Sep 23 10:25:29 2016    unisolated.dat

         4443148 function calls (4306087 primitive calls) in 14.525 seconds

   Ordered by: cumulative time
   List reduced from 11194 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001   14.532   14.532 env/bin/nosetests:4(<module>)
        1    0.000    0.000   14.176   14.176 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:102()
        1    0.000    0.000   14.175   14.175 /usr/local/lib/python2.7/unittest/main.py:72(__init__)
        1    0.000    0.000    8.569    8.569 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:195()
        1    0.000    0.000    8.569    8.569 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:46(r)
      3/1    0.000    0.000    8.563    8.563 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/suite.py:176)
      3/1    0.001    0.000    8.563    8.563 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/suite.py:197)
       68    0.000    0.000    7.341    0.108 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/case.py:44(_)
       68    0.001    0.000    7.341    0.108 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/case.py:115()
       68    0.001    0.000    7.329    0.108 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/case.py:142()
       68    0.000    0.000    7.328    0.108 /usr/local/lib/python2.7/unittest/case.py:392(__call__)
       68    0.002    0.000    7.327    0.108 /usr/local/lib/python2.7/unittest/case.py:295(run)
      145    0.005    0.000    5.837    0.040 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/factory/base.py:4)
      132    0.001    0.000    5.763    0.044 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/factory/base.py:7)
  140/132    0.001    0.000    5.761    0.044 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/factory/base.py:5)
        1    0.000    0.000    5.607    5.607 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:142()
      414    0.008    0.000    5.392    0.013 /Users/whit537/workbench/cos/osf.io/framework/auth/core.py:1229(save)
        1    0.000    0.000    5.347    5.347 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/core.py:181()
        1    0.000    0.000    5.347    5.347 /Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/nose/loader.py:46)
        1    0.000    0.000    5.347    5.347 /usr/local/lib/python2.7/unittest/loader.py:126(loadTestsFromNames)
unisolated.dat%
```

**Comment by whit537** [comment]
Alright, well, no surprises here. We could chase this rabbit hole by seeing whether `set_up_storage` or `teardown_database` was more costly and perhaps optimizable. However, in light of @sloria's point about Postgres coming down the pike, it seems better to simply accept the high cost for the few tests affected, and count on the Postgres migration to address the root cause.

> The other thing is that we should have a test to prove this does what we expect it to and that the tests that don't use this mixin don't do what we expect this to do.

I'll work on this next.

**Comment by whit537** [comment]
> The other thing is that we should have a test to prove this does what we expect it to and that the tests that don't use this mixin don't do what we expect this to do.

Done in 3fcaa1f5b984daec4dfa1df1701af6925249347c. Ready for rereview! :-)

**Comment by whit537** [comment]
Per https://github.com/CenterForOpenScience/osf.io/pull/6184#issuecomment-250167766, I'm going to see about optimizing `DbIsolationMixin` here ...

**Comment by whit537** [comment]
https://github.com/CenterForOpenScience/osf.io/pull/6326#issuecomment-249206924 makes it look like `setUp` is worse than `tearDown`.

**Comment by whit537** [comment]
As https://github.com/CenterForOpenScience/osf.io/pull/6326#issuecomment-249206924 suggests, the expensive part is `setUp`, where we call `set_up_storage` multiple times. In `tearDown` we drop the database entirely. I'm seeing promising initial results from adopting a different strategy: emptying collections rather than dropping the database. I hope to push a commit tomorrow ...

**Comment by whit537** [comment]
Pushed! Ready for rereview ...

**Comment by brianjgeiger** [comment]
Emptying collections is generally what we've done by hand and is the thing that everyone is most surprised about learning doesn't happen, so this seems promising. Doe you have updated benchmarks with the new scheme?

**Comment by brianjgeiger** [comment]
I see you do in the other PR.

**Comment by whit537** [comment]
@brianjgeiger Some benchmarks are at https://github.com/CenterForOpenScience/osf.io/pull/6184#issuecomment-250736432. I'll get ones for here ...

**Comment by whit537** [comment]
> Emptying collections is generally what we've done by hand and is the thing that everyone is most surprised about learning doesn't happen, so this seems promising.

I think we may load some documents as part of `setUpClass` (licenses?). I started looking into snapshotting documents during `setUp` to avoid removing them during `tearDown`, but this becomes much more expensive again quickly. The reason 6910640bfc38464b7f38ac62577e2d6123e868d4 runs so quickly is that it only adds a single db call (I'm not sure what we'd do if/when we want a Mongo that has no `eval`, but I figured that's far enough in the future not to worry about; it's possibly even farther than DjangOSF ;). If we have a stable set of documents we could back that into the js we're passing to eval. That's something we'd need to think about if we want to start using this more broadly.

**Comment by whit537** [comment]
#### Time to run `TestUser`*

|   | status quo (sq) | unoptimized | optimized |
|---:|---------:|-------------:|-------------:|
| 1 | 8.555 | 91.881 | 9.724 |
| 2 | 8.437 | 86.083 | 9.073 |
| 3 | 9.027 | 105.891 | 11.159 |
| μ | 8.673 | 94.618 | 9.985 |
| μ / sq μ | 1 | 10.909 | 1.151 |

`* nosetests -sv tests/test_models.py:TestUser`

**Comment by brianjgeiger** [comment]
Very nice!

**Comment by whit537** [comment]
Running afoul of [OSF-6970](https://openscience.atlassian.net/browse/OSF-6970). Closing and reopening to trigger a new build ...

**Comment by whit537** [comment]
💃

**Pull request merged**
