### PR TITLE
[hold] [Style] Fix mfr block into panel in file view page

### PR DESCRIPTION
**Pull request by caneruguz**
## Purpose
Fix this trello card: https://trello.com/c/kh9ClUOc
Also provide icon unity : https://trello.com/c/Z3pMRV5y 
but in this case unity was done by adding icons so that in this step at least we have same functionality as Wiki. we can remove all if that's the desired look. 

## Changes
- Wrap the mfr with panel classes
- Override mfr-logo-spin to make it fit within the space of the panel
- add icons to headers in file view page

## Side Effects
Mfr iframe seems to load normally and the toggle for widths are working.

### CODE REVIEW

**Comment by sloria** [comment]
I'm not sure that adding the extra "View" panel is an improvement In some cases, it looks like there's too many "containers in containers", and the panel header and margins take up screen real estate.

Take PDFs, for example:

Before:

osf___hilldale_final_report-loria_pdf


After:

osf___hilldale_final_report-loria_pdf

I believe "Before" looks better than "After" in this case.

Text files also look a little awkward as a grey box inside a white box:

After:

osf___debian_yml

**Comment by sloria** [comment]
I think this might need further review. @lbanner @GaryKriebel

**Comment by caneruguz** [comment]
Good point @sloria , let's review some of our options before going forward with this. 

It would be possible to override the spacing of the panel-body so that it doesn't feel like a container but we would need to remove the borders as well and at that point maybe it doesn't help to have a view header. I don't know what the best solution is here. Ideas are welcome.

**Comment by caneruguz** [comment]
It looks like this is not going to happen. @lbanner should I close this?

**Comment by lbanner** [comment]
@caneruguz ... it is now represented as https://openscience.atlassian.net/browse/OSF-3748 ... so we should close in any case, which I will do - Thanks.

**Pull request closed without merging**
