### PR TITLE
Make Dataverse Addon Markup Consistent with Default. 

### LINKED ISSUE #3626: Project settings - Dataverse Import Access Token line has too much padding
Reported by @jinluyuan on the 0.42 Trello board:

# Steps
1. Go to a project on which you have admin access
2. Go to the project settings page and click the check boxes to enable all add-ons (besides external link)
3. After pressing Apply, scroll down to see the list of add-ons to be configured

# Expected
I expect that there would be equal spacing for all add-ons.

# Actual
There is too much padding for Dataverse, and it does not match spacing for all other add-ons.

screen shot 2015-07-15 at 2 55 28 pm

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h2>Purpose</h2>
Remove excess row padding for Dataverse import access Token Line. Close #3626 . Generally make DV addon markup more consistent. 
<h2>Changes</h2>
Simple Html change.
<h2>Side Effects</h2>
None that I know of.

### CODE REVIEW

**Comment by chennan47** [comment]
@Johnetordoff next time if you want to work on some issues. Please comment on that issue tag either Larry or Gary or at least say something to let others know you are working on this. Thanks.

**Comment by sloria** [comment]
This still seems to be inconsistent with the markup for other addons. See the default template: https://github.com/Johnetordoff/osf.io/blob/bac96f62cff5eb6be282fa17c55954bf67700c1b/website/templates/project/addon/node_settings_default.mako . @Johnetordoff Can you look into this?

**Comment by Johnetordoff** [comment]
@sloria Sure thing.

**Comment by Johnetordoff** [comment]
@sloria Cleaned it up a bit, is this good enough?

**Comment by sloria** [comment]
"Deauthorize" should be "Disconnect"

osf___w_settings

**Comment by sloria** [comment]
Just a minor change and this should be good to merge. :v:

**Comment by sloria** [comment]
It's still incorrect. See the image above; it should be "Disconnect Account".

**Comment by Johnetordoff** [comment]
D"oh

**Pull request merged**
