### PR TITLE
[ENG-5472] [ENG-5473] Add original_publication_citation to preprints model and serializer

### PR DESCRIPTION
**Pull request by cslzchen**
## Purpose

Add `original_publication_citation` to `Preprints` model and serializer

The expected value for `original_publication_citation` is to hold one customized citation that users have entered for their preprints. As show in the [phase-2 mock-up](https://preview.uxpin.com/15ddd054b6f36cf29931746eccfb6d7abd9311d5#/pages/165616060/simulate/no-panels?mode=i).

Screenshot 2024-03-27 at 12 49 10 PM

In addition, Product team has confirmed that this field doesn't require the `original_publication_date` to be set.

Finally, this is a field without any FE or BE validation, similar to the `custom_citation` on projects.

## Changes

N/A

## QA Notes

N/A

## Documentation

N/A

## Side Effects

N/A

## Ticket

* https://openscience.atlassian.net/browse/ENG-5472
* https://openscience.atlassian.net/browse/ENG-5473

### CODE REVIEW

**Comment by cslzchen** [comment]
@jwalz thanks for the review, PR description updated

**Comment by jwalz** [comment]
Sweet. Does `custom_publication_citation` make more sense than `original_publication_citation` to be less ambiguous? From the name, I couldn't tell if this was a custom citation for this preprint or a manually encoded citation for a published version (i.e. something analogous to `publication_doi`)

**Comment by cslzchen** [comment]
Yes, I agree will make the change. 

BE has `artical_doi`, `original_publication_date` and will have `custom_publication_citation`.
Product prefers `Publication DOI`, `Publication Date` and `Publication Citation` respectively for display on FE. I asked and the response is it's OK.

**Comment by cslzchen** [comment]
@jwalz PR ready for CR again

**Pull request merged**
