### PR TITLE
Fix Growlbox Title Overlaping with 'x'

### PR DESCRIPTION
**Pull request by Johnetordoff**
<h1> Purpose </h1>
Stop growlbox titles from overlaping upper right 'x'. Close issue #3673.
<h1> Changes </h1>
Adds html spaces to title.
<h1> Side Effects </h1>
None that I know of.

### CODE REVIEW

**Comment by Johnetordoff** [comment]
The test this failed seems weird, I don't exactly how to precede because growlbox is a thrid-party thing and this seems like really simple fix.

**Comment by brianjgeiger** [comment]
No, it looks like you changed the parameters that the function would call with without changing the test to expect those parameters. I would expect that test to fail until it's updated.

**Comment by Johnetordoff** [comment]
@brianjgeiger should I just change the test parameters?

**Comment by brianjgeiger** [comment]
Yeah, make the test match the new reality and tell it to accept the non-breaking spaces.

**Comment by Johnetordoff** [comment]
@brianjgeiger this should be good to go.

**Comment by caneruguz** [comment]
@Johnetordoff this is not an ideal fix for the issue. 

Alerts by default have padding that gives 35px to the side so that x does not get covered. This solution does not address why in this case it is broken. And fixing layout spacing issues with actual empty spaces is a very bad practice. 

I recommend looking into this a bit more. Check how it's supposed to work here: http://getbootstrap.com/components/#alerts

@sloria not ready for merge in my opinion.

**Comment by sloria** [comment]
OK, I agree with @caneruguz . @Johnetordoff could you try another approach?

**Pull request closed without merging**
