### PR TITLE
[Feature] Fix placement of download buttons in conference treebeard 

### PR DESCRIPTION
**Pull request by bdyetton**
Purpose: Download buttons were cut off by the sizing of the rows in the conference treebeard. 
Fix: Changing the top margin in conference.js

### CODE REVIEW

**Comment by lbanner** [comment]
@bdyetton -- Does this PR answer a current GitHub issue? If so, can you add the GH Issue# in the description. Thanks.

**Comment by bdyetton** [comment]
Fixed extra committed file from previous issue.

**Comment by bdyetton** [comment]
@lbanner @sloria Ready to be merged

**Comment by lbanner** [comment]
:+1: .... @lyndsysimon can you take a gander, please?

**Comment by sloria** [comment]
@bdyetton Looks like there are unrelated commits in this PR: can you resend the patch without those commits? Does this address an issue? If so, please link to it by including `closes #1234` in the PR description. Also, could you post screenshots of the fix?

**Pull request closed without merging**
