### PR TITLE
Filter the pointers!

### PR DESCRIPTION
**Pull request by samchrisinger**

### CODE REVIEW

**Comment by sloria** [comment]
Looks good to merge since this is a priority. Could use regression tests. Also, would it make sense to make `get_descendants_recursive` filter out pointers by default?

**Comment by samchrisinger** [comment]
I think that's not unreasonable, but the original use case of log aggregation would have to pass ```f(x) = True``` to this function -- seems less than ideal.

**Comment by lyndsysimon** [comment]
The following code snippet is moderately complex, and appears twice - consider refactoring it into a utility function, or to an attribute of the `Node` object?

    itertools.chain([node], node.get_descendants_recursive(lambda n: n.primary))

I admit, I don't even know what it does without looking up the behavior of `itertools.chain`... which is all the more reason to refactor it. Docstrings! :)

**Comment by samchrisinger** [comment]
I've very very happy to add docstrings, comments, and unit tests to this code, but feel it may be a waste of time until the code if less likely to change.

**Pull request merged**
