### PR TITLE
[ENG-3640] Fix issue where file tag modification was forbidden on registrations

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

With the new Files Page redesign we decided to change the old static file tags behavior to allow Registration files to have updatable tags. 

## Changes

- removed Registration Read-only permissions class for file detail
- Re-did logic for permissions so tags are the only update
- changed check-out behavior, so it's no longer required, just to simplify

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Ticket

https://openscience.atlassian.net/browse/ENG-3640

### CODE REVIEW

**Review by brianjgeiger — APPROVED** [review]
Looks good. Is this worth adding a test for?

**Comment by Johnetordoff** [comment]
Merged

**Comment by brianjgeiger** [comment]
@Johnetordoff Where was this merged to?

**Comment by Johnetordoff** [comment]
I thought this got merged with the Quickfiles migration, but forgot to un-close it, sorry!

**Comment by brianjgeiger** [comment]
Looks like there's a merge conflict.

**Pull request merged**
