### PR TITLE
[feature fix] Activate markup-safe rendering in profile pages (markup-2)

### PR DESCRIPTION
**Pull request by abought**
Depends on #2917 and draws from #1308, #2933.

## Purpose
Turn on markup-safe rendering in the profile and settings pages.

See testing notes for route list and examples: (INSERT)

## Future work
There is an implied database migration for old entries in `Node` and `NodeLog`, as some old records may have been markup-escaped before saving to the DB. See https://github.com/CenterForOpenScience/osf.io/blob/30d3b46a2f0030672378ce84b5cc7accae3cb7ad/scripts/consistency/fix_html_entities.py

Some old records may show up incorrectly in the pages where markup-escaping is turned on, until the DB conversion is run (which would be done after all routes were converted).

### CODE REVIEW

**Comment by JeffSpies** [comment]
@abought can this be updated. @lyndsysimon will do first-pass (again). @sloria @lbanner @GaryKriebel this needs to be in the queue with some immediacy.

**Comment by lbanner** [comment]
Got it ... OK @abought ? Thanks.

**Comment by abought** [comment]
PR updated to include profile and settings pages. Did basic QA on each route modified.

Encountered a problem in rendering of addons settings, so bypassed this route until further investigation. Also, mail settings can't be tested locally; mailchimp throws an error about needing an API key.

**Comment by abought** [comment]
Can someone add the (appropriate) milestone so this doesn't get lost?

**Comment by sloria** [comment]
Marked for 0.43.0

**Comment by sloria** [comment]
Looks good. @abought Can you get this up to date with develop? 

Once this is updated, passing to @lbanner and @GaryKriebel for functional review.

**Comment by abought** [comment]
PR updated.

Things I couldn't check while running locally include:
- Email subscriptions
- Verifying that (activated) addon settings blocks render correctly when embedded in a larger template.

Things to test include various special characters. Ampersands (and possibly other symbols like `<` and `>` will look wonky due to how they are stored in the database.

Other notes:
- Escaping in error.mako is turned off because many routes use `message_long` to write custom HTML into the error message.

- Templates rendered in-place are not markupsafe escaped for now, eg https://github.com/CenterForOpenScience/osf.io/pull/2925/files#diff-9a17aeea80afaaf40ef2c902268ec40fR143 . In theory their content is user-specified.

**Comment by lbanner** [comment]
OK - will check in with you @abought re: What I am looking for!!

**Comment by abought** [comment]
> OK - will check in with you @abought re: What I am looking for!!

This PR changes how content is inserted into templates. It makes sure that unsafe strings (like `<script>`) are displayed exactly as intended on the page, rather than treated as code that can change the behavior of the page.

If you don't have direct access to the database, it's currently very hard to get a string *that* unsafe into the back end. But try adding strings with other special characters (like `&`, `<`, or `>`). You're looking for display artifacts: text or GUI features that used to be reasonable, but now are missing or display gibberish. 

HTML-escaped entities (like `&amp;` or `&lt;`) might be interesting. If you see a symbol instead of the text you entered, that's bad.

Known: Regular ampersands (like `Alice & Bob's project`) may look funny due to a database issue.

**Comment by abought** [comment]
## Testing notes for QA
### Purpose of this PR
This PR is designed to make sure that text you type into the OSF is displayed exactly as you entered it (rather than being treated like code that changes how the OSF works).

Most HTML gets scrubbed out (you can't name a project `<i>QA is awesome!</i>` and have the name show up in italics), but some words display things oddly. For example, on project pages, naming something `Sub-component A &copy;` shows up differently than what you typed in:
screen shot 2015-07-15 at 1 51 34 pm

### Incremental!
We realize that changing how things are displayed is a headache to QA, so we are doing this in small chunks- a few pages at a time. This PR covers Profile and Settings pages.

### List of routes affected
All routes are prefixed with `osf.io` as appropriate. `<brackets>` indicate placeholders for the specified value.
- `/profile/`
- `/profile/<user_id>/`
- `/user/merge/` (Not sure if this page is ever used!)
- `/user/<user_id>/<project_id>/claim/` Where people go when asked to "claim" an email address that was added to a project.
- `/user/<uid>/<pid>/claim/verify/<token>/` View that prompts user to enter their password in order to claim contributorship on a project.
- `/settings` 
- `/settings/account/`
- `/settings/addons/`
- `/settings/notifications/`

### What to look out for
Try a variety of fields that display information you entered in. (think profile fields, schools, URLs, etc) This should not change any validation or entry rules- only how what you entered is displayed.

- JavaScript console errors
- Weird sequences of code where you would expect the addon configuration box to go
- Projects (with 1, 2, or n authors) that render weirdly on the profile page "list of public projects"
- Text that isn't displayed exactly as you type it in- including special characters (see below), or unicode

### References
- List of HTML escape characters (`&amp;`, `&gt;`, and `&lt;` are probably sufficient for testing!) http://www.w3.org/html/wg/drafts/html/master/syntax.html#named-character-references
- Unicode emoticons: http://unicodeemoticons.com/
- QA probably has a list of common test strings- try those! I sometimes use this one
`☃Backslash'\d project & name &copy; alert('hello, world!') ¿ " more \\ \backonechar Text > <wbr> &lt;i&gt;Italicized&lt;/i&gt;☃`

**Comment by abought** [comment]
To address questions about ampersands being rendered oddly, I've added a new default_filter to markupsafe mode: it will convert ampersands (stored in the database as `&amp;`) to regular text, so that they can be displayed exactly as the user intended.

Let me know if there are odd behaviors, eg import errors or display artifacts.

**Comment by GaryKriebel** [comment]
I'll re-pull the code and give another look.

**Pull request closed without merging**
