### PR TITLE
Add "delete" button to file view for GitHub folders [OSF-5732]

### PR DESCRIPTION
**Pull request by asanfilippo7**
OSF-5732 [](https://openscience.atlassian.net/browse/OSF-5732)

Issue:

- No delete button was appearing for folders created in the root folder of a GitHub repo linked to an OSF account.

Fix:

- Add a line in githubFangornConfig that displays the Delete button in the UI if the user has the appropriate permissions

### CODE REVIEW

**Comment by samanehsan** [comment]
Looks good to me @asanfilippo7! 🎉

**Comment by brianjgeiger** [comment]
Is there any way to add a unit test for this? I have a suspicion about how well fangorn.js is tested, but it's worth asking.

**Comment by sloria** [comment]
We don't currently don't have tests for components, although they would be nice to have. I think this PR is good to merge for now.

**Comment by sloria** [comment]
@asanfilippo7 This PR is branched correctly, but in the future, please use a git flow tool to create branches.

**Pull request merged**
