### PR TITLE
Update language in "files" section of Getting Started

### PR DESCRIPTION
**Pull request by jolene-esposito**

### CODE REVIEW

**Comment by sloria** [comment]
I am getting an error when viewing Getting Started.

mako_runtime_error

Make sure to not use smart quote characters in the templates. Use the appropriate HTML entities, e.g. `&ldquo;` `&rdquo;` for double quotes.

**Comment by sloria** [comment]
> Clicking on a file's name opens its File Detail page. Most file types will be displayed directly in your browser on this page, so you can view them without downloading.  From this page, you can also:

Suggested edit:

> Click on a file's name to view it. From this page, you can also:

**Comment by sloria** [comment]
> Share your OSF files with others through links or embeddable objects. Clicking the “Share” button will allow you to share links directly to your files or embed the files into your blog or website to reach a larger audience.

Suggested edit:

> Use the “Share” button to links to your files or embed them on your blog or website.

**Comment by sloria** [comment]
> Check out a file to prevent collaborators from making changes to a file while you're working on it. Clicking the “Check out” button will prevent other contributors from editing, deleting or uploading new versions of a file as long as it is checked-out. You can check a file back in at any time. You must have Read and Write or Administrative privileges to check out a file.

Suggested edit:

> "Check out" a file to prevent collaborators from making changes to a file while you're working on it. You must have "Write" or "Admin" privileges to check out a file.

**Comment by sloria** [comment]
> Add tags to your files to enhance discoverability. The Tags widget is found on the bottom left of the screen. Tags are entered free form by typing them in the box.

Suggested edit:

> Tag your files to enhance discoverability. 

If we are doing our job right, users should be able to find the tags widget on their own. =)

**Comment by sloria** [comment]
Pass finished. @jolene-esposito Let me know if you any further feedback about the proposed edits above. Otherwise, I can make those changes myself and fix the Mako error.

**Comment by jolene-esposito** [comment]
Perfect. Let's go with it!

--------------------------
*Jolene Esposito*
Project Manager
Center for Open Science
jolene@cos.io

Need stats help? COS offers free Statistical and Methodological Consulting
services on reproducible research practices. Learn more here
<http://cos.io/stats_consulting/?utm_source=email_sig&utm_medium=email&utm_campaign=stats>
.

**Comment by sloria** [comment]
Changes made during merge.

**Pull request merged**
