### PR TITLE
[bug fix] [rfr] Make prereg form preview preserve paragraphs

### PR DESCRIPTION
**Pull request by barbour-em**
## Purpose

Preregistration form preview should preserve paragraph formatting

## Changes
Add `breaklines` class to value preview

## Side effects

Better looking walls of text

## Ticket

https://openscience.atlassian.net/browse/OSF-5849

### CODE REVIEW

**Comment by whit537** [comment]
Simple enough. Let's see it in a browser ...

**Comment by whit537** [comment]
Not so simple. 😞 

screen shot 2016-04-25 at 4 38 21 pm

**Comment by whit537** [comment]
Gah. Frobulated. Releasing back to the pool, may try again later. 😞 

screen shot 2016-04-25 at 4 44 56 pm

**Comment by barbour-em** [comment]
@whit537 the `self.currentQuestion` and a few other JS errors on the form page have been fixed in #5547 which is now on develop. You might be able to do a functional review now.

Here is a before and after for either you or whomever reviews this later:

### Before
screen shot 2016-04-27 at 11 50 16 am


### After
screen shot 2016-04-27 at 11 51 01 am

**Comment by samanehsan** [comment]
@barbour-em, did your commits get merged into develop somewhere else? The PR says that 0 files were changed :octocat: ❓

**Comment by barbour-em** [comment]
@samanehsan looks like it was a result of poor merging. I've re-added the change.

**Comment by brianjgeiger** [comment]
Fix looks good. Have you tested on Safari, Firefox, and Chrome, and does it look good on all those?

**Comment by brianjgeiger** [comment]
🐧

**Comment by barbour-em** [comment]
@brianjgeiger, this is in additional development but looks good to me in Safari, FF, and Chrome. Is there an issue?

**Comment by brianjgeiger** [comment]
Nope, just verifying.

**Pull request merged**
