### PR TITLE
[Ready] Fixes the osfToggleHeight initialization in user settings 

### PR DESCRIPTION
**Pull request by caneruguz**
## Purpose
Fixes JIRA issue: OSF-4265
Where the application of the osfToggleHeight plugin to addon node list was unreliable. 

## Changes 
There are two types of data load methods for addons
1. Those that get added by backend and mako file addon_permissions.mako
-- For these the document.ready function was used to apply
2. Asyncronous loading with ajax after load 
-- For these the initialization was added where nodes have been applied 

## Side effects
None 

screen shot 2015-09-03 at 12 00 12 pm

### CODE REVIEW

**Comment by caneruguz** [comment]
I'm checking out the travis fail

**Comment by HarryRybacki** [comment]
@caneruguz update this with develop when you get a second and it'll pass the TCI builds

**Comment by HarryRybacki** [comment]
CR 1 looks good :+1: Moving back to `in progress` and assigning @caneruguz. Once brought up to speed with develop it can be moved to CR 2 and await the next reviewer.

**Comment by samanehsan** [comment]
This looks good to me too! Done with second pass @caneruguz :octocat:

**Pull request merged**
