### PR TITLE
[Feature] Set limit to max for citation_list requests

### PR DESCRIPTION
**Pull request by mfraezz**
Purpose
======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3157

Changes
=======
* Add `limit: 500` argument to outgoing Mendeley requests
* Set `limit=100` to Zotero's `client.collections()` call in `citations_list`

Side Effects
=========
Also sets the max for Zotero, not just Mendeley.

Note
====
Pagination would be a more perfect solution, but this has been a user issue for a while.

### CODE REVIEW

**Comment by sloria** [comment]
@GaryKriebel Would you mind doing a functional review of this?

**Comment by GaryKriebel** [comment]
I'll give it a go... may take a while to get to a large number of items/folders.

**Comment by mfraezz** [comment]
@GaryKriebel  Check the testing flow, I did that for you.

**Comment by GaryKriebel** [comment]
Yep... looks to be the cure of the ills.  Thanks @mfraezz.  @saradbowman will be happy when this is deployed.

**Pull request merged**
