### PR TITLE
[HOLD] Fix for API nested attrs and apiv2 Links documentation

### PR DESCRIPTION
**Pull request by alexschiller**
<h1>Purpose</h1>

Partial fix for Issue #3259 to make links slightly less tricky. Mostly adds documentation, and add a _get_deep_attr function to allow for deeply nested attributes to work properly.

<h1>Changes</h1>

Documentation of APIV2 LinksFields functions
Add get_deep_attr
Add error catching when attr_tpls are added to Links fields improperly

<h1>Side Effects</h1>
None that I know of currently.

### CODE REVIEW

**Comment by sloria** [comment]
@alexschiller Build is failing. Can you look into it?

**Comment by alexschiller** [comment]
@sloria fixed, I fail at flak8

**Comment by brianjgeiger** [comment]
Holding on this until the JSON API work has finalized.

**Comment by brianjgeiger** [comment]
This is relevant again. If you merge with develop, you'll see _rapply has been moved out of this scope into the general OSF scope. The rest of the changes will be great to get merged in, though.

**Comment by brianjgeiger** [comment]
Actually, hold off again.

**Comment by sloria** [comment]
The internal API for serializing relationships has changed significantly since this PR. Closing this for now.

**Pull request closed without merging**
