### PR TITLE
Make component give description in ES results [OSF-6332]

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

Make components include their descriptions in ES results. 

## Changes

One line change in JS.

## Side effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/OSF-6332

### CODE REVIEW

**Comment by HalcyonChimera** [comment]
Looks right to me.

**Comment by Johnetordoff** [comment]
screen shot 2016-08-03 at 11 21 47 am

**Comment by brianjgeiger** [comment]
Looks great. 🎉 🐧 🎉

**Comment by Johnetordoff** [comment]
@brianjgeiger this has been demo g2g?

**Comment by brianjgeiger** [comment]
Yup. It's in "Passed Code Review" on Jira.

**Pull request merged**
