### PR TITLE
bolds labels on profile page [OSF-6302]

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

make labels on profile Education and Employment cards bold

## Changes

creates new css class

## Side effects

None

## Ticket
https://openscience.atlassian.net/browse/OSF-6302

### CODE REVIEW

**Comment by brianjgeiger** [comment]
There's a `card-body` CSS class already in use in the OSF. Well, maybe in use. Would it make sense to make this more specific so we don't accidentally bold something on the contributors page?

screen shot 2016-05-17 at 1 52 48 pm

**Comment by brianjgeiger** [comment]
Looks good otherwise. Pass done. 🐧

**Comment by Johnetordoff** [comment]
'card-body' CSS classes on the contributor page aren't actually being used, so I removed them.

**Comment by brianjgeiger** [comment]
Awesome. Could you put before and after screenshots in the Changes section of the PR? That will help QA.

**Comment by brianjgeiger** [comment]
Looks great. 🎉 🐧  🎉 

Don't change it for this, but don't forget to use gitflow and put development-branched branches in feature/branch-name

**Comment by brianjgeiger** [comment]
screen_shot_2016-05-19_at_1_22_15_pm

**Comment by brianjgeiger** [comment]
👍

**Pull request merged**
