### PR TITLE
Update Language about Categories of Components/Projects [OSF-6627]

### PR DESCRIPTION
**Pull request by amyshi188**
Purpose
======

Add more descriptive language when changing Category in components to clarify what Category means to the user.

Changes
======

Added "(for descriptive purposes)" when adding new component and under component settings.

**Before**
image

image

**After**
image

image

Side effects
=========

None

Ticket
=====

https://openscience.atlassian.net/browse/OSF-6627

### CODE REVIEW

**Comment by brianjgeiger** [comment]
There's a lot of jitter for a two-line commit. Could you re-base onto develop? Also, please include before and after screenshots in the Changes section of your PR.

**Comment by brianjgeiger** [comment]
Fix the JS-Hint error and this should be ready to merge. 🐧 

```
jshint /home/travis/build/CenterForOpenScience/osf.io/website/static/js
/home/travis/build/CenterForOpenScience/osf.io/website/static/js/addProjectPlugin.js: line 259, col 38, Strings must use singlequote.
```

**Comment by amyshi188** [comment]
Fixed the JS-Hint error! Let me know if any other problems come up.

**Comment by brianjgeiger** [comment]
Looks great. That test failure is not your doing. 🎉 🐧 🎉

**Pull request merged**
