### PR TITLE
[Feature][Ready for Review] Migration script: GoogleDriveOauthSettings -> ExternalAccounts

### PR DESCRIPTION
**Pull request by mfraezz**
Purpose
=======
Adds script to migrate `GoogleDriveOAuthSettings` objects to `ExternalAccount` objects.

Note
=====
Must go in and be migrated before #4261  

Migration Steps
============
* Ensure that the `user_settings` field of GoogleDriveNodeSettings has been changed to `foreign_user_settings`
```
python -m scripts.googledrive.migrate_to_external_account
```
* [Merge 4261]
* Again, ensure that the `user_settings` field of GoogleDriveNodeSettings has been changed to `foreign_user_settings`
```
python -m scripts.googledrive.connect_external_accounts
```

[#OSF-2272]

### CODE REVIEW

**Comment by mfraezz** [comment]
Build failure expected due to pre-migration field name change.

**Comment by abought** [comment]
As discussed with @mfraezz , a sample migration (connect drive on newest develop, then run 4396, then run 4261) is failing locally. Requesting verification on sample data before continuing with review.

**Comment by samanehsan** [comment]
Can you add a note to the PR description to remove `foreign_user_settings` post-migration?

**Comment by samanehsan** [comment]
This looks good to me @mfraezz! Done with CR2 :palm_tree:

**Pull request merged**
