### PR TITLE
[Hotfix]Move and copy logs

### PR DESCRIPTION
**Pull request by chrisseto**
Bind to html rather than to text in knockout as we send back presanitized data

### CODE REVIEW

**Comment by sloria** [comment]
@chrisseto @icereval Is this PR still necessary?

**Comment by chennan47** [comment]
This maybe fixes https://github.com/CenterForOpenScience/osf.io/issues/2846

**Comment by sloria** [comment]
@chennan47 That issue seems to be separate from this fix. That issue is about misleading language for rename logs. This fix is about displaying sanitized data.

**Comment by chrisseto** [comment]
@sloria This PR is still necessary
Log currently display incorrectly when moving/copying a file in a project with a name containing html entities, <&> etc.

**Comment by lyndsysimon** [comment]
Review complete - looks good.

**Comment by lbanner** [comment]
@lyndsysimon .... Let's also do a 'ping' @sloria when your pass is complete and looks  good. Thanks!

**Pull request merged**
