### PR TITLE
[hotfix] Force tag to be an instance of Tag prior to adding to Node

### PR DESCRIPTION
**Pull request by cwisecarver**

### CODE REVIEW

**Comment by icereval** [comment]
lgtm

**Comment by cwisecarver** [comment]
All checks have passed

**Comment by cwisecarver** [comment]
All checks have passed

**Comment by cwisecarver** [comment]
All checks have passed

**Comment by icereval** [comment]
I clicked them all!

**Comment by chrisseto** [comment]
lgmt

**Pull request merged**
