### PR TITLE
[CR] Feature/api v2 docs revisions 2

### PR DESCRIPTION
**Pull request by felliott**
This PR fixes some typos and issues since the last BAPI doc revision, as well as making sure that all public changes from 291fa6fd5..8a049a9ae94 are captured.  Changes:

1.) Natasha caught a typo in NodeProvidersList
2.) I noted that file move/copy can return either 200 or 201 now.
3.) Fixed a typo in the files docs  "Succes:" => "Success:"
4.) Removed the obsolete spiel from the swagger docs
5.) Node parents structure changed, update doc to reflect this
6.) Document the new node `fork` attribute and `forked_from` relationship
7.) Removed the node `collection` attribute from docs, as that is currently dev-only
8.) JSON-API errors were changed to always include a `source` field.  Doc that and provide example.
9.) Document the `profile_image_size` param for user/contributor endpoints

Relevant: [#OSF-4977]

### CODE REVIEW

**Comment by cwisecarver** [comment]
One tiny note regarding a feature that isn't merged yet. To CR2.

**Comment by brianjgeiger** [comment]
I can't see where this would have been caused by this PR, but in the running for today's least useful error message:

screen shot 2015-11-02 at 11 39 37 am

**Comment by brianjgeiger** [comment]
Also some tests are failing and there are merge conflicts. I expect that the failing tests are a resolved Travis problem. Other than that, looks good. Pass finished. :penguin:

**Comment by felliott** [comment]
> I can't see where this would have been caused by this PR, but in the running for today's least useful error message:
> 

Yeah, `django-rest-swagger` interprets a series of hyphens as the beginning of configuration YAML.  That’s one of the conflicts between it and BAPI.

**Comment by felliott** [comment]
> Also some tests are failing and there are merge conflicts. I expect that the failing tests are a resolved Travis problem. Other than that, looks good. Pass finished. 
> 
Thanks!   I’ve fixed the merge conflicts, and the test failures have been in trunk awhile.  I’ll send this on to R2M.

**Comment by brianjgeiger** [comment]
:+1:

**Pull request merged**
