### PR TITLE
[Hotfix] File (github) revisions

### PR DESCRIPTION
**Pull request by chrisseto**
Insert version into file download urls

### CODE REVIEW

**Comment by chrisseto** [comment]
Note: to be deployed with https://github.com/CenterForOpenScience/waterbutler/commit/a243d8d3c77971c37524942fa532aacb17b23839

**Comment by chrisseto** [comment]
https://openscience.atlassian.net/browse/OSF-4760

**Comment by sloria** [comment]
Please open a new PR to master.

**Comment by sloria** [comment]
Disregard previous comment. This was cherry-picked into master

**Pull request closed without merging**
