### PR TITLE
OSF-4794 Changed button style and text

### PR DESCRIPTION
**Pull request by adlius**
Purpose: Change the button style and text for the modal.
Changed: button style changed from "primay" to "default". Text change from "okay" to "close"
screen shot 2015-10-14 at 16 15 53

### CODE REVIEW

**Comment by sloria** [comment]
@adlius Could you please post a screenshot of what the new modal looks like?

**Comment by chennan47** [comment]
CR1 done. Looks good.

**Comment by abought** [comment]
CR2 complete, no changes requested.

**Comment by sloria** [comment]
@caneruguz Could you take a quick look at this? I'm not sure if we have any grey 'Close' buttons anywhere else. Is this the proper fix?

**Comment by caneruguz** [comment]
Thank you @sloria  for raising the question and thanks @adlius for working on it. This is a bit of a grey area and something that needs additions to the style guide. 

The principle behind not using OK is that actions should have action **verbs**. But this modal is not an action modal, it's giving information, there is nothing the user can do but to close it. However having a CLOSE button by itself is not intuitive to what we want the user to do. In essence we want the buttons to reflect user thinking.  So my recommentation is for cases that use closing action on information to use the button text "Got it". In this way the user sees that clicking this button means they have understood the message, so they have a context. 

This is what I added to the Style Guide:

**For modals that only provide information to the user, use a single button with text "Got it" that closes the modal. Also use the X on top right. Do not use a question mark as modal header.**

Also very important addition: whatever we do, the question at the header "Publish this dataset?" is really bad. We can't have the same question from previous modal there, the users will expect the buttons to answer a questions.  Usually the header says a short form of the message like "Dataset published" and the body of modal explains it. In this case it's very short body so we don't have to use the header necessarily. 

So eventually something like this might work better: 
screen shot 2015-10-15 at 2 41 38 pm

**Comment by sloria** [comment]
Thanks @caneruguz . Only additional suggestion I'd make is to still include a header in the modal for better use of whitespace. Perhaps "Already published".

**Comment by adlius** [comment]
I have changed the text of the button and change the header. See screenshot.
screen shot 2015-10-16 at 11 28 47

**Comment by jinluyuan** [comment]
@adlius Could you change the header to say "Successfully published" - no period?
 "Already published" is confusing because the content was not _already_ published. The user just published it himself.

**Comment by sloria** [comment]
I agree with @jinluyuan 's suggestion. I will make this change when I merge.

**Pull request merged**
