### PR TITLE
Hotfix/nested project read permission

### PR DESCRIPTION
**Pull request by chennan47**
fix https://github.com/CenterForOpenScience/osf.io/issues/2159

<b>Purpose</b>
fix the problem that the 'admin' user lose 'read' permission on nested child project title redirect

<b>Changes</b>
before fix,
The Parent project's name is not displayed in the header - instead, "Private Project" is shown.
The "up to parent project" link in the project navbar is linked to nothing.
image

after fix,
the behavior is correct, admin user on grandparent project can view the parent project title redirect on child project page.
screen shot 2015-03-20 at 4 21 00 pm

### CODE REVIEW

**Comment by sloria** [comment]
Please add a regression test for this. Once that is finished, this is good to merge.

**Comment by chennan47** [comment]
@sloria regression tests added. rdy for view and merge

**Comment by sloria** [comment]
@chennan47 It would also be worth expanding the unit test for `Node#can_view` to account for your change (see [here](https://github.com/CenterForOpenScience/osf.io/blob/1cf15e5cad7aae815a57aff0d02e93e1b0cf761f/tests/test_models.py#L2068)); our current tests did not account for this edge case.

**Comment by chennan47** [comment]
@sloria tests added to Node#can_view. rdy for another pass.

**Pull request merged**
