### PR TITLE
[#OSF-6544]typo in prereg schema

### PR DESCRIPTION
**Pull request by chennan47**
## Purpose

Fix the typo in prereg form

## Ticket

https://openscience.atlassian.net/browse/OSF-6544

### CODE REVIEW

**Comment by mfraezz** [comment]
LGTM. :shipit: 

screen_shot_2016-06-24_at_09_39_07

**Comment by sloria** [comment]
We should probably migrate existing registrations and draft registrations to be consistent with this change. @chennan47 Can you do this in a follow up PR? And similar migration exists here: https://github.com/CenterForOpenScience/osf.io/blob/d58d5c5908158cf86edb15840c0452b391a96752/scripts/migration/migrate_prereg_schema_multiple_choice_responses.py

**Comment by chennan47** [comment]
Will do @sloria

**Comment by sloria** [comment]
Thanks!

**Pull request merged**
