### PR TITLE
[PLAT-208] New wiki resize options

### PR DESCRIPTION
**Pull request by Johnetordoff**
❗️ Corresponding diff that needs review: https://github.com/tatsy/markdown-it-imsize/compare/master...Johnetordoff:676fd0588e3eea40f54eee7dfd65bd15cd6f1c87 ❗️ 

## Purpose

Allow user to specify wiki image markdown sizes as a percent ("=x%") of their parent and "=fill" which fits the image to the parent.

screen shot 2018-02-20 at 2 00 43 pm

## Changes

Changes requirement to forked markdown-it-imsize package. 

## QA Notes

Try images of many different shapes and file formats. We can't vouch for image quality, just that it doesn't overlap text etc.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/projects/PLAT/issues/PLAT-208

### CODE REVIEW

**Comment by sloria** [comment]
Discussed on FD:

- Syntax should be `=50%`
- Percentage sizes might already be supported: https://github.com/tatsy/markdown-it-imsize/issues/4 . Try upgrading to see if we get this out-of-box

Also:

- `fill` is just an alias for `100%`, but it's a useful one for our users. So I think we should still support that. Consider sending that as a PR to `markdown-it-imsize`.

**Comment by Johnetordoff** [comment]
To address the above:
- ✅ Done
- They are but only in =50%x40%) format which doesn't make sense for us because we preserve are aspect ratio using CSS.
- Yep it's still supported for us, I'll hold off making a PR until this gets approved however, it wouldn't be fair to make someone else review something we haven't already approved ourselves.

**Comment by sloria** [comment]
One more comment to address: https://github.com/tatsy/markdown-it-imsize/commit/82e1abd1e4ae3ccd674a187a9c14083355728b2d

**Comment by sloria** [comment]
Talked in person: all that's left to do on this is some git fu.

**Pull request merged**
