### PR TITLE
[Hotfix]Make an analytics task to determine the number of older wiki entries [OSF-6752]

### PR DESCRIPTION
**Pull request by TomBaxter**
## Purpose:
[OSF-6752](https://openscience.atlassian.net/browse/OSF-6752)
Create analytics script to count legacy wikis

## Changes:
Add scripts/analytics/legacy_wikis.py counts legacy wikis and average size
Update  scripts/analytics/tasks.py to reference new script

## Side effects
None

[#OSF-6752]

### CODE REVIEW

**Comment by brianjgeiger** [comment]
I think I'll restart travis on this. I'm not sure who stopped it, but it will let us know if, for example, we created a problem with the install or a import loop or similar. Maybe I'll just do one branch.

**Comment by brianjgeiger** [comment]
Okay, this looks good to me. 🎉 🐧 🎉

**Comment by TomBaxter** [comment]
Sample output. Average size and largest are in bytes.

  total    legacy    average_size    largest
-------  --------  --------------  ---------
     13         0               0          0

**Comment by sloria** [comment]
Got this data to @brianjgeiger , and we don't need to run this weekly, so closing this for now.

**Pull request closed without merging**
