### PR TITLE
[feature] Refactor Retraction to Withdrawal

### PR DESCRIPTION
**Pull request by caseyrollins**
- Changes 'retracted' to 'withdrawn' in user-facing language.
- Refactors routes to /withdraw/ instead of /retraction/
- [OSF-5542]

### CODE REVIEW

**Comment by samanehsan** [comment]
Looks good to me @caseyrollins! Done with CR1 :snowman:

**Comment by sloria** [comment]
The "retracted" language still appears in the API. @caseyrollins Shouldn't this be changed there as well?

**Comment by caseyrollins** [comment]
@sloria Yeah, not sure why I left that in there. Sending a PR for it now.

**Comment by sloria** [comment]
Thanks!

**Pull request merged**
