### PR TITLE
Refactor figshare [OSF-(4993, 5599, 5917, 6712)]

### PR DESCRIPTION
**Pull request by mfraezz**
## Purpose

Figshare is the last remaining third-party service addon to not use the `ExternalAccount` architecture. Also, their v1 API was deprecated in January 2016, and support for it will be removed ... sometime soon, probably, given that their v1 docs were taken down several months ago.
## Changes
- Figshare models updated to comply with generalized conventions, use general architecture.
- Figshare views ″
- Figshare frontend ″
- Figshare serializer added
- Figshare client rewritten to use their v2 API
- Rename log and param for folder selecting (migration added)
- APIv2 folder listing/setting support added
- Generalized OSF/API tests added
- Remove dead `rubeus`-type code
## Side effects

1) All existing Figshare credentials on the OSF will be unusable, and we cannot migrate that data to reauthorize with their v2 API (received confirmation of this from a Figshare developer). This will affect approximately 300 users and 150 nodes.
2) OAuth mechanism may or may not work with figshare, see [ticket 6712](https://openscience.atlassian.net/browse/OSF-6712)
3)  It is unknown whether or not their OAuth2 implementation has expiring tickets -- whether or not we can / need to refresh them. This is difficult to determine because figshare has disallowed non-https OAuth callback urls, effectively prohibiting local development.
## Notes

1) Log migration:

``` bash
python -m scripts.figshare.migrate_folder_logs --dry
```

2) (Reason for **[Hold]**) Currently, Waterbutler does not support the Figshare v2 API, and expects v1 credentials from `serialize_waterbutler_credentials`. Things that rely on WaterButler (file listing, streaming, etc) will not work until it's updated.
## Tickets

[OSF-4933](https://openscience.atlassian.net/browse/OSF-4933)
[OSF-5599](https://openscience.atlassian.net/browse/OSF-5599)
[OSF-5917](https://openscience.atlassian.net/browse/OSF-5917)
[OSF-6712](https://openscience.atlassian.net/browse/OSF-6712)
Maybe more ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by brianjgeiger** [comment]
It's Autumn Cleaning time, so I'm closing this PR. Feel free to re-open when development becomes active again.

**Comment by mfraezz** [comment]
This is blocked by updating the WaterButler provider to figshare's v2 API, which is under active development. @TomBaxter expects that to hit CR sometime next week, maybe sooner. When that happens, this will no longer be blocked.

**Comment by brianjgeiger** [comment]
@mfraezz Conflicts need resolving.

**Comment by mfraezz** [comment]
@brianjgeiger Noted. It looks like just the fact that ownCloud went in recently -- a list in `settings/defaults.py` needs update.

>Conflicting files
> api/base/settings/defaults.py

**Pull request merged**
