### PR TITLE
Hotfix/mobileFixes

### LINKED ISSUE #2781: Navbar refactoring
Expected
-----------
Everything in the navbar should be centered vertically.

Actual
--------
Similar to #2775, the logo is a bit off center on the full site, as is the gravatar/user name.

screen shot 2015-05-21 at 9 56 49 am

### PR DESCRIPTION
**Pull request by ticklemepierce**
Purpose
-----------
These fixes close #2781, #2773, and #2260.  Prior to these fixes, certain elements were not centered in the navbar and the navbar was also wider than it should be on the "Profile" page when on mobile.  Also, the name header on the "Profile page" for mobile was getting obscured/overlapping links previously and this addresses that.  This PR cleans up these misaligned UI elements to create a smoother user experience.

Changes
-----------
* Adjusted line height of the text next to the logo/gravatar to make sure that it was centered with the image
* Adjusted the padding/margins on the images so that they vertically center
* Changed the size of the font and the margins of the name header on the "Profile" page so that the name fits better.
* Removed a class from the table on the "Profile" page that does not seem to do anything other than make the table too wide

Side Effects
----------------
Many of the changes could be made without any performance issues between the full site and the mobile site.   Anything that needed to be different on the two was done using @media tags in the CSS so it would not have any side effects on the other.  Tested on Chrome, Firefox, and Safari.

### CODE REVIEW

**Comment by lbanner** [comment]
Nice @ticklemepierce :+1: 
@caneruguz If you haven't, can you please review these commits? But also, @ticklemepierce -- This should probably not be a "[Hotfix]" rather merge request it to "develop" without that tag -- These are good, but not critical, can should get an opportunity to go through QA combined into a full release.

**Comment by caneruguz** [comment]
@ticklemepierce there is something wrong with this PR, you are probably not following the pull/push logic of the change. Ideally in a PR only your commits should be listed, otherwise that means you haven't synced your local changes properly.

**Comment by chennan47** [comment]
@ticklemepierce Your pr is based on develop which in this case can only be merged into develop instead of master. Again hotfix based on master, feature based on develop.

**Comment by caneruguz** [comment]
Yes so ping us in the new PR that you make so we can take a look at your changes. Thanks!

**Comment by chennan47** [comment]
@ticklemepierce Could you close this pr since you already reopen the other one?

**Pull request closed without merging**
