### PR TITLE
[OSF-6527] Linkify wiki markdown

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

Our current markdown-it settings don't mark-up URL and leave them of plain text. This fix automatically marks-up URL to clickable links in the wiki edit window.

## Changes

Simple js change enabled linkify and disables the "commonmark" markup which forbids linkification.

## Side effects

None that I know of.

## Before

screen shot 2017-08-23 at 1 11 51 pm

## After
screen shot 2017-08-23 at 1 07 29 pm

## Ticket

https://openscience.atlassian.net/browse/OSF-6527

### CODE REVIEW

**Comment by brianjgeiger** [comment]
@Johnetordoff So you can't do commonmark with the exception of linkifying? The only way is to turn it off?

**Comment by Johnetordoff** [comment]
Yes, I'm tested the markup behavior without commonmark and it seems unchanged. Linkify-ing and commonmark are not compatible, as far as I know.

**Comment by brianjgeiger** [comment]
Okay, I'm checking with Nici. If we can't use the commonmark shorthand, then we definitely will need to re-apply all of the individual changes that make up commonmark (other than linkifying) if we go forward with this change.

**Comment by Johnetordoff** [comment]
@brianjgeiger, sorry! false alarm, there was a way to enable linkify with commonmark.

**Pull request merged**
