### PR TITLE
[hold] Restore v2/ to API URLs when appropriate

### PR DESCRIPTION
**Pull request by abought**
## Purpose

Addresses regression in #3251 , plus my own past mistakes.

The api_v2_url function is intended to add configuration-dependent parts onto a URL fragment, eg to turn `/nodes/<pid>` into `http://api.osf.io/v2/nodes/<pid>`

In the process of removing the API_PREFIX variable, route stopped appending API_BASE as well.

Separately, the `absolute_reverse` function was appending `v2` twice (once by Django and once with a helper function), so some routes (eg Link fields) showed `v2/v2` erroneously.

## Summary of changes
Stop appending `v2/` when it is redundant, and resume appending it when it's needed.

TODO:
- [x] QA it by examining links fields and other API output.

### CODE REVIEW

**Comment by abought** [comment]
@brianjgeiger , could you confirm the new behavior matches our intent for which config variables will be relevant in deployment going forward?

(Not urgent; I have a few things to get to first anyway. Enjoy the vacation.)

**Comment by brianjgeiger** [comment]
What you have described is correct once we move things to the sub domains.

**Comment by abought** [comment]
In that case I'll hold this PR until the subdomain move is done. Thanks.

**Comment by brianjgeiger** [comment]
I know it's been forever since we've done this, but things should be more simple once we make this change rather than less. So instead of having {local_domain}/v2 vs {staging_domain}/api/v2, now everything will be {domain}/v2. I recall it being the whole flask vs django dichotomy and so on, but if I'm having trouble remembering, nobody else reviewing will have a good sense for this either. So could you do a couple of examples, of inputs and outputs to show the effect now and after the subdomain is moved?

**Comment by abought** [comment]
I think that this PR, or some version thereof, is currently blocking testing of #3082 on staging2. So, to resurrect the issue, here are some answers for @brianjgeiger :

There are already some examples of current function behavior in the unit tests, showing what comes in and out based on the various parameters: https://github.com/abought/osf.io/blob/f6306ceb903ab54b95c5951eb9343f359281854c/tests/test_utils.py#L67

Since that does not cover every possible use case, I've helpfully posted a small gist that calls the function with arguments and prints the results. Feel free to add your own and experiment.
https://gist.github.com/abought/3a78b86e9d3ce615e2ed

I've also updated the docstring to remind users of the difference between the two similarly named arguments, and pushed the changes to this PR.

**Comment by abought** [comment]
We've gotten this far without using this PR, so I'm closing this to keep the backlog clean.

(Thanks for calling it to my attention during your epic PR rampage, @sloria )

**Pull request closed without merging**
